### ISSUE TITLE
beqs - error when column returns all blanks

### ISSUE THREAD

**Issue by joel23888** [Rblp/Rblpapi#103]
I set up the following screen called "tse_etf1".

-----------------------------

Security universe:
Trading status: Active
Security attributes: show primary ticker only
Security types: ETF
Exchanges: Tokyo

Display only fields:
Relative index
Current market cap
Year to date total return
Current price earnings ratio (P/E)

--------------------------

This error was returned:
> beqs("tse_etf1")
Error: could not convert using R function : as.data.frame

I noticed in the BBG terminal P/E is empty for all results. I deleted P/E and now it works as expected.

A workaround is to remove the columns known to return all blanks but the user may not always know a column in a screen would be all blanks.

**Comment by csrvermaak** [comment]
Hi @joel23888 - this is identical to #99, and has been fixed - patch will be available in the next release.

**Comment by joel23888** [comment]
Apologies. I had searched for the error but should have looked more closely at beqs issues before posting
