### ISSUE TITLE
Error: Year is out of valid range: 1400..10000

### ISSUE THREAD

**Issue by RockScience** [Rblp/Rblpapi#107]
I found another interesting error message, certainly linked to an incorrect conversion of data type, from string of characters to date.

```r
Rblpapi::bdp(securities = "NDSS022 CMPT Index", fields = "LAST_UPDATE")
# returns Error: Year is out of valid range: 1400..10000
```
and as long as "NDSS022 CMPT Index","LAST_UPDATE" is part of the query, the entire query fails: compare the two following code:
```r
Rblpapi::bdp(securities = c("IP Index"), fields = "LAST_UPDATE") # works
Rblpapi::bdp(securities = c("IP Index","NDSS022 CMPT Index"), fields = "LAST_UPDATE") # returns the error
```

This is the result from Excel BBG API:

 | LAST_UPDATE
------------ | -------------
IP Index | 10/31/2015
NDSS022 CMPT Index | 3:59:34 PM

as you can see, we cannot assume that the date is there. For NDSS022 CMPT Index, we get only the time...

I looked at the code of bdp.cpp but couldn't find if this conversion is done in Rcpp or in the bdp.cpp itself. Is there a way to prevent this date conversion to occur? If we keep the data as string of characters, we don't assume that the output of this field in in datetime format, and we should be able to prevent the case where the date is not in a recognisable format.

```
packageVersion("Rblpapi")
[1] '0.2.2.6.2.3'


R.version                       
platform       i386-w64-mingw32            
arch           i386                        
os             mingw32                     
system         i386, mingw32               
status                                     
major          3                           
minor          2.0                         
year           2015                        
month          04                          
day            16                          
svn rev        68180                       
language       R                           
version.string R version 3.2.0 (2015-04-16)
nickname       Full of Ingredients
```

**Comment by eddelbuettel** [comment]
Why are you using this version:

```
packageVersion("Rblpapi")
[1] '0.2.2.6.2.3'
```

**Comment by RockScience** [comment]
Thank you for the recommandation. I installed 3.1 as the windows binary is not available for 3.2. Unfortunately this doesn't help. Do you have the same error on your side?

```r
> packageVersion("Rblpapi")
[1] '0.3.1'
> Rblpapi::bdp(securities = "NDSS022 CMPT Index", fields = "LAST_UPDATE", con = con)
Error: Year is out of valid range: 1400..10000
```

**Comment by eddelbuettel** [comment]
Yes:

```r
R> library(Rblpapi)
R> bdp(securities = "NDSS022 CMPT Index", fields = "LAST_UPDATE")
Error: Year is out of valid range: 1400..10000
R> packageVersion("Rblpapi")
[1] ‘0.3.2’
R> 
```

So someone has to dive in there and examine the returned data more closely.

**Comment by armstrtw** [comment]
@RockScience can you pls test this again.  PR #130 should have fixed it.

**Comment by eddelbuettel** [comment]
Yup, works here:

```r
R> library(Rblpapi)
R> bdp(securities = "NDSS022 CMPT Index", fields = "LAST_UPDATE")
                    LAST_UPDATE
NDSS022 CMPT Index 15:09:53.000
R> 
```

**Comment by RockScience** [comment]
Thanks for the comments and indeed the new version of the code (thanks to @armstrtw ) is not sending an error anymore.

However the format of the output is still a bit weird, I get 
"17:46:42.000"
instead of
"17:46:42" (in Excel I get "5:46:42 PM")

is ".000" a usual convention for times? If yes let me know I will close the thread.
Thank you for the progress on this.

**Comment by eddelbuettel** [comment]
R does not have a native time (as in time-only) type. So we probably just transform this to this string.

When I run this right now (with the GH code), we get Date:

```r
R> library(Rblpapi)
R> bdp(securities = "NDSS022 CMPT Index", fields = "LAST_UPDATE")
                   LAST_UPDATE
NDSS022 CMPT Index  2016-02-29
R> 
```

All this is backend-dependent.  If you don't like the trailing `.000` you can trivially `gsub()` it away at your end.

I recommend that this issue be closed.

**Comment by RockScience** [comment]
Fine for me! Thanks

**Comment by armstrtw** [comment]
Because this field has ftype 'DateOrTime,' we are retrieving it as a string.  So the trailing .000 for times is simply what bbg is sending back when we call Element::getValueAsString().  You're welcome to take it up with them.
