### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by derekholmes** [Rblp/Rblpapi#108]
bdh documentation has the wrong enumeration:  "periodicityAdjustment" s/b "periodicitySelection"
> bdh("SPY US Equity", c("PX_LAST", "VOLUME"),
+     start.date=Sys.Date()-31*6, options=c("periodicityAdjustment"="MONTHLY"))
Error: Enumeration type could not be found for MONTHLY
..
> bdh("SPY US Equity", c("PX_LAST", "VOLUME"),
+     start.date=Sys.Date()-31*6, options=c("periodicitySelection"="MONTHLY"))
        date PX_LAST     VOLUME
1 2015-06-30  205.85 2535242753
2 2015-07-31  210.50 2452757863

**Comment by eddelbuettel** [comment]
Use ``` to format code, not `>` which is used for text quotes.

**Comment by eddelbuettel** [comment]
What version do you refer to?  Version 0.3.2 as well as [current GitHub sources](https://github.com/Rblp/Rblpapi/blob/master/man/bdh.Rd#L57) have `periodicitySelection`.

Closing this.

**Comment by eddelbuettel** [comment]
For the record:

```r
R> library(Rblpapi)
R> opt <- c("periodicitySelection"="MONTHLY")
R> bdh("SPY US Equity", c("PX_LAST", "VOLUME"), start.date=Sys.Date()-31*6, options=opt)
        date PX_LAST     VOLUME
1 2015-06-30 204.785 2535242753
2 2015-07-31 209.411 2452757863
3 2015-08-31 196.647 3734926746
4 2015-09-30 191.630 3279512868
5 2015-10-30 207.930 2536184532
6 2015-11-30 208.690 1924512621
R> packageVersion("Rblpapi")
[1] ‘0.3.2’
R> 
```

**Comment by eddelbuettel** [comment]
This was fixed a few weeks ago, but relase only got out today.
