### ISSUE TITLE
getBars options vector - defaults other than NULL?

### ISSUE THREAD

**Issue by joel23888** [Rblp/Rblpapi#110]
@eddelbuettel I am thinking there should be some defaults for the getBars options vector besides NULL. What do you think?

If I added defaults to the options vector would something like this be acceptable?

```R
getBars(security, eventType = "TRADE", barInterval = 60,  startTime = Sys.time() - 60 * 60 * 6,
endTime = Sys.time(), options = getOption("getBarsOptions", NULL),
verbose = FALSE, returnAs = getOption("blpType", "matrix"), tz = Sys.getenv("TZ", unset = "UTC"), 
con = defaultConnection())
```

Where getBarsOptions would be set as something like:
```R
 options(getBarsOptions = c("gapFillInitialBar"="TRUE", "adjustmentFollowDPDF"="TRUE"))
```

**Comment by eddelbuettel** [comment]
I am not sure. I think I'd want to double check with other API clients and their defaults.

**Comment by joel23888** [comment]
Correct me if I'm wrong but doesn't the use of getOption with a default of NULL allow each user to specify their own preferred set of options?

The other concern I can see is if returnAs were put into an options vector then this may break code that relied on the current returnAs option.

**Comment by eddelbuettel** [comment]
If you override a default of `NULL` with your value ... you get your value?  What am I missing?

**Comment by joel23888** [comment]
My preferred setting in getBarsOptions in a particular project could differ from the default. I am trying to:
* Use getOption to keep preferred options for a project for getBars across different calls, but still be able to override these by passing a vector of options on a particular call
* Have a default if getBarsOptions is not specified. This could be `NULL` or it could be something else like `c("gapFillInitialBar"="TRUE", "adjustmentFollowDPDF"="TRUE")`.. I think following DPDF seems to make sense (and may be safer) as a default because that is what the user has set on their terminal. If the default is `NULL` then the data return would not be adjust for corporate actions irrespective of the DPDF settings. Filling the initial bar is not a necessity for a default

**Comment by eddelbuettel** [comment]
We could do that, but I don't want to put an infinity of values into `options()`.  

As an alternative can you not simply define alternate (local) wrappers:
```r
getBars1 <- function(...) {
   getBars(..., options=c("gapFillInitialBar"="TRUE","adjustmentFollowDPDF"="TRUE"))
}
```
etc possibly setting the option values as function arguments there too?

**Comment by joel23888** [comment]
Yes, that is also fine.
