### ISSUE TITLE
Rblpapi - getTicks resolution

### ISSUE THREAD

**Issue by o869k** [Rblp/Rblpapi#112]
Hi,

Thank you for the package. I started using it for quant ML purposes in R and it looks great.

I was wondering if the time stamp of getTicks can be in higher resolution than seconds (mili seconds, even less?).
The problem is that I can get many ticks that are stamped for the same second. But I want higher resolution than that. Is it possible?

In ‘POSIXct’ I can define the format of %Y-%m-%d %H:%M:%OS or '%Y-%m-%d %H:%M:%OS1'
for a ms value. Is it possible to integrate inside the package?

Regards,
Ori

**Comment by eddelbuettel** [comment]
To the best of our knowledge, this is (intentionally ?) hard-wired by Bloomberg at the back-end.

So by the time _any_ API client receives the data, time stamps have been rounded or truncated to the second.  The ordering is said to be preserved, but multiple events will come at the same time stamp. 

Sorry.

**Comment by o869k** [comment]
Thanks. Nice to know.
I taking my first steps with Bloomberg.

**Comment by eddelbuettel** [comment]
I hope you find the package useful. We do -- and we're always open for good extensions.  

I'll close this as there is in fact little we can do -- but at least it will be searchable here.
