### ISSUE TITLE
Enhancement Request: Rblpapi and Bloomberg SAPI

### ISSUE THREAD

**Issue by smacc76** [Rblp/Rblpapi#113]
The Rblpapi package is great. My colleagues and I make a lot of use of it so thank you for your time developing it.

I’m interested to know if your functions will work with Bloomberg’s Server API as opposed to the Desktop API that most of my colleagues use. I have successfully used the Rblpapi package on a server without Bloomberg installed by providing blpConnect with the correct host and port details of our SAPI server. This returns data under the Server Mode of the SAPI i.e. without the need to enter a Bloomberg UUID.

My question is can blpConnect be modified so that a Bloomberg UUID or a client IP Address can be passed to the SAPI so that the SAPI will operate in User Mode. This would allow a client (PC) to pass user details through the server (running R) to the SAPI and return data back to the client. I understand that the Bloomberg Data Centre would check that the IP Address of the client provided did have a logged in Bloomberg Anywhere Terminal thereby adhering to the Bloomberg data license and providing only the data that the user is entitled to.

An explanation of the differences between Server Mode and User Mode are given here in the Bloomberg API Developer’s Guide:

http://www.bloomberglabs.com/content/uploads/sites/2/2014/07/blpapi-developers-guide-2.54.pdf

Do you think that this is something that you could incorporate? It would add another very useful dimension to Rblpapi.

Thanks.

**Comment by eddelbuettel** [comment]
Can you or your colleague take a stab at this?  This project is pretty open to pull requests...

**Comment by johnlaing** [comment]
This is already incorporated: `?blpAuthenticate`

**Comment by smacc76** [comment]
Our issue is that our firm's expertise is in C# and .NET. So we could use C# and rClr but I'm aware you have built this package in C++ and with Rcpp and was trying to avoid reinventing the wheel. Unfortunately we don't have any C++ resource in the firm.
