### ISSUE TITLE
Issues transitioning from R package Rbbg to Rblpapi in conjunction with missing field values and treatment of non-trading days

### ISSUE THREAD

**Issue by dlincke** [Rblp/Rblpapi#114]
First off all, I would like to extend my thanks for the significant effort expended in producing the Rblpapi package as an improved successor to the previous Java based efforts.

I have recently started to transition some scripts initially implemented using package RBloomberg/Rbbg to Rblpapi (version 0.3.2) and in the process encountered the following issues in conjunction with missing field values and treatment of non-trading days.

Option include.non.trading.days is a bit of a mystery to me as it seems to be doing the exact opposite of what it is purported to do. See output p1 of the included demonstration code which produces a value for a Sunday despite include.non.trading.days set to FALSE. I suspect that there is some interaction going on with API request option ALL_CALENDAR_DAYS. Because in the presence of that option setting include.non.trading.days TRUE actually suppresses output for non-trading days (output p2).

Output P2 demonstrates an additional issue as the unavailability of a field value is not indicated by inclusion of an NA value, but instead the field column is dropped from the function output. This is a deviation in semantics from package Rbbg, and I would assume that I am not the only one whose code broke due to this behavior.

Output p3 illustrates that the dropping of the field column only takes place if values are unavailable for all requested dates. Otherwise, as expected, NA is returned for those dates.

Output p4 demonstrates IMO broken behavior with a symbol for which the requested field does not contain any data for any period. Again, I would have expected NA to be returned for the PX_LAST field for the requested dates.

I would appreciate if the above issues could be addressed in an upcoming version of the package. Please let me know if there is anything else I can do to help track this down.

Thank you and best regards,
David

-------------------
Code output:
```
p1:
        date PX_LAST
1 2000-01-30  1716.5
 
p2:
        date
1 2000-01-30
 
p3:
        date PX_LAST
1 2000-01-28  1716.5
2 2000-01-29      NA
3 2000-01-30      NA
 
p4:
        date
1 2000-05-28
2 2000-05-29
3 2000-05-30
```
-------------------------

Demonstration code:

```R
require("Rblpapi")
require("xts")
 
fld <- "PX_LAST"
sdt <- as.Date("2000-01-30")
edt <- as.Date("2000-01-30")
 
 
p1 <- bdh(securities = "LAH00 Comdty", fields = fld,
         start.date = sdt, end.date = edt,
         include.non.trading.days = FALSE,
         options = c("periodicitySelection" = "DAILY",
                     "nonTradingDayFillOption" = "ALL_CALENDAR_DAYS",
                     "nonTradingDayFillMethod" = "PREVIOUS_VALUE"))
print(p1)
 
 
p2 <- bdh(securities = "LAH00 Comdty", fields = fld,
          start.date = sdt, end.date = edt,
          include.non.trading.days = TRUE,
          options = c("periodicitySelection" = "DAILY",
                      "nonTradingDayFillOption" = "ALL_CALENDAR_DAYS",
                      "nonTradingDayFillMethod" = "PREVIOUS_VALUE"))
print(p2)
 
 
sdt <- as.Date("2000-01-28")
edt <- as.Date("2000-01-30")
 
p3 <- bdh(securities = "LAH00 Comdty", fields = fld,
          start.date = sdt, end.date = edt,
          include.non.trading.days = TRUE,
          options = c("periodicitySelection" = "DAILY",
                      "nonTradingDayFillOption" = "ALL_CALENDAR_DAYS",
                      "nonTradingDayFillMethod" = "PREVIOUS_VALUE"))
print(p3)
 
 
sdt <- as.Date("2000-05-28")
edt <- as.Date("2000-05-30")
 
p4 <- bdh(securities = c("LLF01 Comdty"), fields = fld,
         start.date = sdt, end.date = edt,
         include.non.trading.days = FALSE,
         options = c("periodicitySelection" = "DAILY",
                     "nonTradingDayFillOption" = "ALL_CALENDAR_DAYS",
                     "nonTradingDayFillMethod" = "PREVIOUS_VALUE"))
print(p4)
```

**Comment by armstrtw** [comment]
Yep.  the missing field issue will be fixed soon.  try back in a week or so.

**Comment by dlincke** [comment]
Thanks. What about the semantics of the include.non.trading.days option? In the provided example code it is obviously not behaving as advertised.

**Comment by eddelbuettel** [comment]
Didn't something like that come up before on a now-close issue here? `options` versus `overrides`?

**Comment by eddelbuettel** [comment]
Can this be closed?  Running the provided example code (kudos for that, well done) gets me

```r
R> source("issue114.R")
Loading required package: Rblpapi
Loading required package: xts
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

        date PX_LAST
1 2000-01-30  1716.5
        date PX_LAST
1 2000-01-30      NA
        date PX_LAST
1 2000-01-28  1716.5
2 2000-01-29      NA
3 2000-01-30      NA
        date PX_LAST
1 2000-05-28      NA
2 2000-05-29      NA
3 2000-05-30      NA
R> 
```

**Comment by dlincke** [comment]
I have not tested this again after incorporating a workaround in my time
series retrieval code. But your results certainly suggest that it has been
taken care of, so I agree that this can be closed.

Thanks a lot,
David
