### ISSUE TITLE
Get Field Info

### ISSUE THREAD

**Issue by BastienLuc** [Rblp/Rblpapi#116]
I was wondering if it was possible to load field infos via Rblpapi into R. Using Excel, this would work with the formula `=BFieldInfo("MLI_OAS")`. Up to now I have only been working with commands such as bdh and bdp. The difference now is that I do not have a certain Index. Have I overlooked the existence of such a command? 
Thank you for your help!

**Comment by eddelbuettel** [comment]
Well if it is not there someone has to contribute code for it. Can you?

**Comment by BastienLuc** [comment]
Hm..since I'm still pretty new to R and writing code in general, I must admit that I think I'm not yet able to do things like that. I am just starting to understand how to use existing packages, writing them is another step to take :D

**Comment by joel23888** [comment]
For anyone considering implementing this, Field Information and Field Search requests are supported by the BBG C++ API. See http://www.bloomberglabs.com/content/uploads/sites/2/2014/07/blpapi-developers-guide-2.54.pdf at Section 7.6. Personally I find using the `FLDS` command on my terminal sufficient. If I were to look at implementing this I would do it after https://github.com/Rblp/Rblpapi/issues/117.

**Comment by armstrtw** [comment]
the c++ function is now in the code base.  I'll add a wrapper for it later this week.

**Comment by armstrtw** [comment]
https://github.com/Rblp/Rblpapi/blob/master/R/fieldInfo.R#L35
