### ISSUE TITLE
bds with dates as options does not work

### ISSUE THREAD

**Issue by arorar** [Rblp/Rblpapi#118]
Consider the following lines of code

```R
    library(Rblpapi)
    con <- blpConnect()
    opt <- c("START_DT"="19990101", "END_DT"="20160101")
    bds("CPI YOY Index","ECO_RELEASE_DT_LIST", options = opt, con = con)
    blpDisconnect(con)
```

I get the following error, **"Error: Sub-element '(null)' does not exist."** while executing the code. It has something to do with the options. I can get the data in excel with these options. Also note that without the options I can get a small chunk of data starting 2015. However, the goal is to get all data starting from a particular date.

**Comment by eddelbuettel** [comment]
It "works" when you use `overrides=` instead of `options=`.

Someone needs to volunteer to clean up the code.  Could that be you?

**Comment by joel23888** [comment]
I had a quick look at Rblpapi/src/bds.cpp and it already seems clean in this respect: options are appended as options and overrides appended as overrides. Looking at `CPI YOY Index FLDS` in BBG: `START_DT` and `END_DT` are in fact overrides of `ECO_RELEASE_DT_LIST` so should clearly have been passed as overrides anyway. I would suggest this issue be closed.

**Comment by eddelbuettel** [comment]
Thanks -- and agreed!

**Comment by eddelbuettel** [comment]
I'll add it to the examples section of `bds()` as well.
