### ISSUE TITLE
Error using field "px_volume" in bdh:  "REAL() can only be applied to a 'numeric', not a 'integer'"

### ISSUE THREAD

**Issue by eriknil** [Rblp/Rblpapi#128]
I'm unable to download historical volumes using `bdh`. Everything works well using the CRAN version, but trying the following using the latest version on Github
````r
library(Rblpapi)
blpConnect()
bdh("ERICB SS Equity", "px_volume", start.date = Sys.Date()-10)
```

will return this error message
```
Error in bdh_Impl(con, securities, fields, start.date, end.date, options,  : 
REAL() can only be applied to a 'numeric', not a 'integer'
```

Here's my `sessionInfo()`:
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rblpapi_0.3.2.2

loaded via a namespace (and not attached):
[1] Rcpp_0.12.3
```

I'll see if I can figure out a solution to this. Although I suspect that there's a lot of changes going on at the moment regarding how data.frames are initiated and populated. So maybe this is best left to someone already involved in the development?

**Comment by eddelbuettel** [comment]
Thanks for the report. I can replicate it. We'll take a look.

**Comment by armstrtw** [comment]
gotta love bbg...

> t(fieldInfo("px_volume"))
         px_volume  
id       "PR013"    
mnemonic "PX_VOLUME"
datatype "Int32"    
ftype    "String"   
>

**Comment by eddelbuettel** [comment]
Boost.Lexical_Cast to the rescue, maybe?  See the (very recent) illustration [here](http://stackoverflow.com/a/35568261/143305) based on [this](http://gallery.rcpp.org/articles/a-second-boost-example/).  Just a thought.  I debugged here too and just got this 'irregularity'.   But I won't have more time this a.m. ...

**Comment by eddelbuettel** [comment]
@armstrtw   FWIW it also fails for the plain example from the manual page:

```r
R> opt <- c("periodicitySelection"="MONTHLY")
R> bdh("SPY US Equity", c("PX_LAST", "VOLUME"), start.date=Sys.Date()-31*6, options=opt)
Error in bdh_Impl(con, securities, fields, start.date, end.date, options,  : 
  REAL() can only be applied to a 'numeric', not a 'integer'
R> 
```

**Comment by ClarkHenry** [comment]
FWIW, you can get volumes from getTicks:

`getTicks("ERICB SS Equity")`

Perhaps OP can use this as a work-around for the time being.

**Comment by armstrtw** [comment]
It's a pretty easy fix.  Just need to link the value setter code to our types which we get from fieldInfo, not the returned bbg types.  In this case, it looks like fiedInfo says it's an Int32, but bbg delivers it as a BLPAPI_DATATYPE_FLOAT64.

I bet this happens with many of the fields.  My only worry is that we could potentially overflow a 32bit int if the values bbg returns are large enough...

**Comment by eddelbuettel** [comment]
But the error message was `REAL() can only be applied to a 'numeric', not a 'integer'` which would be  _entirely_ of our making by using `REAL()`.  Methinks just using `Rcpp::NumericVector` would cast from integer, and even here you could just multiply by 1.0, no?

**Comment by armstrtw** [comment]
Dirk, it's here:
https://github.com/Rblp/Rblpapi/blob/master/src/blpapi_utils.cpp#L154
but bbg has told us that field was an int32, so that's how we allocated it originally.  but bbg is delivering it as float64.

Anyway, this all needs to be cleaned up by using RblpapiT in the setter function, not e.datatype().

**Comment by eddelbuettel** [comment]
The fix has been committed.
