### ISSUE TITLE
Hidden Dependencies

### ISSUE THREAD

**Issue by rj919** [Rblp/Rblpapi#134]
I've tried to recreate the Linux environment for the package using Docker and unfortunately, I cannot seem to get Rblpapi to install on Ubuntu. Here is my docker image:
https://hub.docker.com/r/rc42/rblpapi/~/dockerfile/

If I try to install the package (which has been commented out in the Dockerfile), it returns strange error messages which indicate to me that there may be hidden dependencies in your tests which are not declared in the package. Perhaps you can look over Dockerfile and/or try to install package using these instructions and identify why the package fails to install.

I do not have such problems installing either BH or Rcpp upon which the package depends.

**Comment by eddelbuettel** [comment]
That may be networking related when it tries to fetch the Bloomberg headers / library.   That issue is essentially _yours_ so you have to debug that at your end I fear.

We uses this all day long on plain Ubuntu. I do a bit of Docker too, so I can try.  No promises though.

**Comment by rj919** [comment]
Here's a print out of the beginning of the installation errors:

* installing *source* package 'Rblpapi' ...
Setting up compilation for a linux 64-bit system
Error in capabilities()[["libcurl"]] : subscript out of bounds
Calls: cat
Execution halted
./configure: line 66: [: ==: unary operator expected
Error in capabilities()[["libcurl"]] : subscript out of bounds
Calls: cat
Execution halted

After that it reports lots of failures trying to call some variable called "DatatypeT".

When it says subscript is out of bounds, does that refer to the Bloomberg Terminal sub? Does some key from Bloomberg need to be installed on the image prior to installing the package? 

I just assumed that you needed to add your key when you instantiate the library at program run.

**Comment by eddelbuettel** [comment]
Please look at the code.  I do not know how well you know the structure of R packages -- but this is _very standard_ use of a script [configure](https://github.com/Rblp/Rblpapi/blob/master/configure) you can look at, and execute line by line. I suggest you do that.

This may be as simple as you not having a `curl` binary, or as complicated as Docker not allowing you to slurp code in.  In which case you need to patch `configure`.

None of the errors at the _package building stage_ have anything to do with calling Bloomberg.

**Comment by rj919** [comment]
Thanks for the explanation. I will look into how my system is configured and see if I can identify what is causing the errors.

**Comment by eddelbuettel** [comment]
Quick check:  What R version do you use, and what OS (and version) do you use for Docker?

*Very* old R versions do not have libcurl support and cannot do https URLs.  That may be an issue.

**Comment by rj919** [comment]
R 3.0.2
Ubuntu 14.04
Python 2.7.6
Python 3.4.3

**Comment by eddelbuettel** [comment]
Ok, I replicated.  After `apt-get install r-base-core` we get R 3.0.2 (more on that later).  We then have to manually download sources for Rblpapi, Rcpp, and BH.  They install, but then R fails for _the very reason I gave you earlier_:  no libcurl:

```r
Error in capabilities()[["libcurl"]] : subscript out of bounds
Calls: cat
Execution halted
```

The fix is simple.  Go read the [standard README for R Ubuntu binaries at CRAN](https://cloud.r-project.org/bin/linux/ubuntu/README.html) which explains how you **very easily** get .deb binaries for R 3.2.3.  Which is not only much better, has two more years of bug fixes ... but will also install Rblpapi directly from CRAN for you.

**Comment by rj919** [comment]
Thanks. Updating the repository links seems to have done the trick. Now, Rblpapi installs.

However, when I try to load the package inside R, it causes the following fatal error:
```
> library("Rblpapi")
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/site-library/Rblpapi/libs/Rblpa
pi.so':
  libblpapi3_64.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for 'Rblpapi'
> library("Rcpp")
>
```
As you can see, the error does not arise from importing Rcpp. Curiously, when I install Rblpapi from inside R using install.packages("Rblpapi"), it both installs and loads correctly. So, I am left thinking that the Rblpapi package installation creates a soft link to some file outside of Rblpapi which does not get copied over to the site-packages. But, I'm not sure what it is or why, since both BH and Rcpp can be coped to site-packages without problem.

As you can probably figure out, I am bound to install packages using R CMD INSTALL if I wish them to built using the Dockerfile. However, R CMD INSTALL doesn't seem to place installation files in the correct path for them to be seen by R library(). /usr/local/lib/R/site-library/ So, I have moved them to the place they are required. But this is likely causing the problem with Rblpapi being loaded. 

Perhaps you know how to properly invoke R CMD INSTALL so that I do not need to move the files and the packages appear in the correct place.

**Comment by eddelbuettel** [comment]
I really have no time to hold your hand here.  The package is on CRAN, it gets rebuilt every night on a number of different architecture; we also use Travis CI to check.

If it still fails, and you insist on using your Dockerfile, maybe something is wrong with your Dockerfile.

**Comment by eddelbuettel** [comment]
I also happen to support Docker files and containers from R, including the official one,  Using that:

```bash
edd@max:~$ docker pull r-base
latest: Pulling from r-base
a224f8249b32: Pull complete 
1cfa32d83d36: Pull complete 
710d129f5ef8: Pull complete 
227a3bab7ecd: Pull complete 
d7cac4040819: Pull complete 
8809551f14e5: Pull complete 
e889bbf7d1cc: Pull complete 
cac8fcf95d0c: Pull complete 
547f1c479c1a: Pull complete 
82253473f812: Pull complete 
63373a6d0e38: Pull complete 
8b1651d59882: Pull complete 
r-base:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:9bb84bb85235bd3143bf566004ec3c41e78d68818850e9c61012ea282ef3e1d3
Status: Downloaded newer image for r-base:latest
edd@max:~$ 
edd@max:~$ docker run --rm -ti r-base /bin/bash  # I like the cmdline
root@e385adb357ae:/# install.r Rblapi   # a helper from littler
Warning message:
package ‘Rblapi’ is not available (for R version 3.2.3) 
root@e385adb357ae:/# install.r Rblpapi   # a helper from littler
also installing the dependencies ‘Rcpp’, ‘BH’

trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.3.tar.gz'
Content type 'application/x-gzip' length 2374320 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/src/contrib/BH_1.60.0-1.tar.gz'
Content type 'application/x-gzip' length 9618456 bytes (9.2 MB)
==================================================
downloaded 9.2 MB

trying URL 'https://cran.rstudio.com/src/contrib/Rblpapi_0.3.2.tar.gz'
Content type 'application/x-gzip' length 147544 bytes (144 KB)
==================================================
downloaded 144 KB


* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Date.cpp -o Date.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Module.cpp -o Module.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c Rcpp_init.cpp -o Rcpp_init.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c api.cpp -o api.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c attributes.cpp -o attributes.o
g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c barrier.cpp -o barrier.o
g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/Rcpp/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rcpp)
* installing *source* package ‘BH’ ...
** package ‘BH’ successfully unpacked and MD5 sums checked
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (BH)
* installing *source* package ‘Rblpapi’ ...
** package ‘Rblpapi’ successfully unpacked and MD5 sums checked
Setting up compilation for a linux 64-bit system
** libs
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c authenticate.cpp -o authenticate.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c bdh.cpp -o bdh.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c bdp.cpp -o bdp.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c bds.cpp -o bds.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c beqs.cpp -o beqs.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c blpConnect.cpp -o blpConnect.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c blpapi_utils.cpp -o blpapi_utils.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c fieldsearch.cpp -o fieldsearch.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c getBars.cpp -o getBars.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c getTicks.cpp -o getTicks.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I../inst/include/ -I.  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/BH/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c subscribe.cpp -o subscribe.o
g++ -std=c++11 -shared -L/usr/lib/R/lib -Wl,-z,relro -o Rblpapi.so RcppExports.o authenticate.o bdh.o bdp.o bds.o beqs.o blpConnect.o blpapi_utils.o fieldsearch.o getBars.o getTicks.o subscribe.o -lblpapi3_64 -L../inst/blp -Wl,-rpath,/usr/local/lib/R/site-library/Rblpapi/blp -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/Rblpapi/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rblpapi)

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
root@e385adb357ae:/# 
root@e385adb357ae:/# R

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(Rblpapi)
> 
```

As you can see, with a proper Docker container it builds, installs and loads just fine, just as it does on any of the normal supported systems.   

The rest is really your issues.   Try to see if you can replicate what I did here.

**Comment by rj919** [comment]
I very much appreciate your help with this (non-)issue. Believe it or not, it is very useful to see an example of how the installation process performs correctly. Thanks.

**Comment by eddelbuettel** [comment]
Understood. And it is maddening when it fails.

One of the many nice things about packages on CRAN is that you generally assume they work.  So if something fails, simplify, simplify, simplify, ...

**Comment by eddelbuettel** [comment]
And for reference, the underlying [Dockerfile](https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile).

**Comment by rj919** [comment]
Thanks for your help. I finally got it to [build correctly](https://hub.docker.com/r/rc42/rblpapi/). 
The trick seems to have been to use Rscript -e 'install.packages()' to install all the dependencies. Thanks again.

**Comment by eddelbuettel** [comment]
Good to know you got it working too.  And yes,  you generally want `install.packages `
