### ISSUE TITLE
More field type issues

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#135]
Just tried to get expiry/notice dates, here shown with a very well known contract:

```r
R> library(Rblpapi)
R> fieldSearch("First Notice")
     Id        Mnemonic             Description
1 Q2409 FIRST_NOTICE_RT First Notice - Realtime
R> 
R> bds("ESH6 Index", "FIRST_NOTICE_RT")
Error: Attempt to access value of element 'FIRST_NOTICE_RT'(type: 'Date') as 'Element' type.
R> 
```

And of course it works in Excel...

We do get the metadata:

```r
R> fieldInfo("FIRST_NOTICE_RT")
                   id        mnemonic datatype ftype
FIRST_NOTICE_RT Q2409 FIRST_NOTICE_RT Datetime  Date
R> 
```

@armstrtw I presume you know where to adjust this?

(Very fresh build from yesterday afternoon using current GitHub repo sources.)

**Comment by eddelbuettel** [comment]
With a quickly added `verbose` flag:

```r
R>  bds("ESH6 Index", "FIRST_NOTICE_RT", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "ESH6 Index"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                FIRST_NOTICE_RT = 2016-03-18
            }
        }
    }
}
R>
```

**Comment by armstrtw** [comment]
is that normally a bds field?  I thought that was meant for bdp...

**Comment by eddelbuettel** [comment]
In full egg-on-face mode:

```r
R> bdp("ESH6 Index", "FIRST_NOTICE_RT")
           FIRST_NOTICE_RT
ESH6 Index      2016-03-18
R> 
```

How does one decide?  My heuristic was _everything that is not price or trade related is `bds()`_.

**Comment by armstrtw** [comment]
no worries.  there's really no way to tell on the Rblpapi side since the BDH request looks identical.  Maybe bbg keeps a list of the allowable BDS requests somewhere, but I don't know about it if it exists.  They are surprisingly light on documentation.

**Comment by johnlaing** [comment]
My heuristic is: `bdp` for scalars and `bds` for more `data.frame`-like responses.
