### ISSUE TITLE
R connection to Bloomberg 

### ISSUE THREAD

**Issue by afsi** [Rblp/Rblpapi#136]
Im trying to pullout data from Bbg to r, and have tried 
install.packages("Rblpapi")
library(Rblpapi)

And got the following msgs. Any comments? Thank you

> install.packages("Rblpapi")
Installing package into ‘/Users/afsaneh/Library/R/3.1/library’
(as ‘lib’ is unspecified)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 31 3275k   31 1039k    0     0   701k      0  0:00:04  0:00:01  0:00:03  701k 73 3275k   73 2415k    0     0   972k      0  0:00:03  0:00:02  0:00:01  972k100 3275k  100 3275k    0     0  1059k      0  0:00:03  0:00:03 --:--:-- 1059k

The downloaded binary packages are in
	/var/folders/c_/jdgk1bp13x5_58nddh8s2dnh0000gn/T//RtmpOmSj08/downloaded_packages
> library(Rblpapi)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/afsaneh/Library/R/3.1/library/Rblpapi/libs/Rblpapi.so':
  dlopen(/Users/afsaneh/Library/R/3.1/library/Rblpapi/libs/Rblpapi.so, 6): Library not loaded: @rpath/libblpapi3_64.so
  Referenced from: /Users/afsaneh/Library/R/3.1/library/Rblpapi/libs/Rblpapi.so
  Reason: image not found
In addition: Warning message:
package ‘Rblpapi’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘Rblpapi’

**Comment by eddelbuettel** [comment]
Briefly:

- Your report is incomplete.  You don't even state the R version, or the OS and version.
- The report makes no sense, and I fear you only showed partial logs so we have to guess.
- Maybe you have _two_ versions installed and you still get the old one. We cannot tell.  What does `.libPaths()` show? 
- For what it is worth, I just logged a complete and full installation (under Docker) [here](https://github.com/Rblp/Rblpapi/issues/134#issuecomment-189390054)

**Comment by afsi** [comment]
1) OS X V: 10.11.3
 R 3.1.3
 R Studio: Version 0.99.879 (if it matters)
2) I doubt if I have two versions, but

**Comment by afsi** [comment]
OS X V: 10.11.3
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Platform: x86_64-apple-darwin13.4.0 (64-bit)

I removed rblpapi and reinstalled it. The same problem for my both libraries 
library("Rblpapi", lib.loc="~/Library/R/3.1/library")
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/afsaneh/Library/R/3.1/library/Rblpapi/libs/Rblpapi.so':
  dlopen(/Users/afsaneh/Library/R/3.1/library/Rblpapi/libs/Rblpapi.so, 6): Library not loaded: @rpath/libblpapi3_64.so
  Referenced from: /Users/afsaneh/Library/R/3.1/library/Rblpapi/libs/Rblpapi.so
  Reason: image not found
In addition: Warning message:
package ‘Rblpapi’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘Rblpapi’

**Comment by afsi** [comment]
I have meanwhile upgraded R to 3.2.3.  and installed the Rblpapi package again. 
calling the library I get the following msg again: 

library("Rblpapi", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rblpapi/libs/Rblpapi.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rblpapi/libs/Rblpapi.so, 6): Library not loaded: @rpath/libblpapi3_64.so
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rblpapi/libs/Rblpapi.so
  Reason: image not found
Error: package or namespace load failed for ‘Rblpapi’

**Comment by eddelbuettel** [comment]
We need another OS X user to weight in. 

One thing you can (should ?) try is to install from source. Maybe the binary you from CRAN is not right for you.  Try `install.packages("Rblpapi", type="source")`.

**Comment by joel23888** [comment]
FWIW the easiest way to make sure R on OS X is set up correctly to install packages from source is to use a package manager. OS X does not come with one, but one option is to install homebrew (there are also other package managers which I am unfamiliar with). Guides for installing homebrew and then how to install R using it can be found quickly by googling:
* For installing homebrew itself on OS X 11.3 try http://coolestguidesontheplanet.com/installing-homebrew-on-os-x-el-capitan-10-11-package-manager-for-unix-apps/
* For installing R using homebrew try http://www.r-bloggers.com/installing-r-on-os-x-100-homebrew-edition/ 

Disclaimer: I have not used Rblpapi from a Mac, this is just trying to help OP install it from source.

**Comment by eddelbuettel** [comment]
Closing this as it appears to be a local OS X setup issue.
