### ISSUE TITLE
Sub-element error when using bdh

### ISSUE THREAD

**Issue by ravi480000** [Rblp/Rblpapi#137]
I am using version 0.3.2 of Rblpapi.

When I try to use this override, I get a sub-element error:
> bdh("IBM US EQUITY", c("FISCAL_YEAR_PERIOD", "SALES_REV_TURN"), start.date=as.Date("2015-01-01"), end.date=as.Date("2015-12-31"), overrides=c(PER="FQ"))
Error: Choice sub-element not found for name 'securityData'.

When I try to use the override as an option, I get a different sub-element error:
> bdh("IBM US EQUITY", c("FISCAL_YEAR_PERIOD", "SALES_REV_TURN"), start.date=as.Date("2015-01-01"), end.date=as.Date("2015-12-31"), options=c(PER="FQ"))
Error: Sub-element '(null)' does not exist.

The above query works in excel 
=BDH("IBM US EQUITY","FISCAL_YEAR_PERIOD, SALES_REV_TURN","01/01/2015","12/31/2015","PER=FQ")
and produces this output
3/31/2015	2015 Q1	19590
6/30/2015	2015 Q2	20813
9/30/2015	2015 Q3	19280
12/31/2015	2015 Q4	22059

**Comment by eddelbuettel** [comment]
See `help(bdh)` for the worked example of `periodicitySelection`. I guess quarterly would work too, and it does:

 R> opt <- c("periodicitySelection"="QUARTERLY")      
 R> bdh("IBM US EQUITY", c("FISCAL_YEAR_PERIOD", "SALES_REV_TURN"), 
 +           start.date=as.Date("2015-01-01"), end.date=as.Date("2015-12-31"), opt=opt)   
         date FISCAL_YEAR_PERIOD SALES_REV_TURN                          
 1 2015-03-31            2015 Q1          19590                                                          
 2 2015-06-30            2015 Q2          20813                                                          
 3 2015-09-30            2015 Q3          19280                                                          
 4 2015-12-31            2015 Q4          22059                                                          
 R> 

@wmorgan85 Any idea how we can get hold documentation, or anything resembling it, which covers the transition from `PER=FQ` in Excel to `opt <- c("periodicitySelection"="QUARTERLY") ` here?
