### ISSUE TITLE
Order of BDH output

### ISSUE THREAD

**Issue by madcowgoatsmuggla** [Rblp/Rblpapi#139]
I am using `bdh` to pull the closing prices of equity indexes.  I have noticed that the output order does not correspond to the security order input in the function.  For example:

```R
Rblpapi::bdh(securities = c("SPX Index", "CCMP Index", "UKX Index", "DAX Index", 
                            "TPX Index", "SPTSX Index", "CAC Index", "INDU Index", 
                            "HSI Index", "SX5E Index"),
             fields = "PX_LAST", start.date = Sys.Date() - 10, end.date = Sys.Date() - 10)
```

Interestingly the output is not the same order as the input:

```
$`SPX Index`
        date PX_LAST
1 2016-02-19 1xxxx

$`HSI Index`
        date PX_LAST
1 2016-02-19 1xxxx

$`SX5E Index`
        date PX_LAST
1 2016-02-19 2xxxx

$`CCMP Index`
        date  PX_LAST
1 2016-02-19 4xxxx

$`UKX Index`
        date PX_LAST
1 2016-02-19 5xxxx

$`DAX Index`
        date PX_LAST
1 2016-02-19 9xxxx

$`TPX Index`
        date PX_LAST
1 2016-02-19 1xxxx

$`SPTSX Index`
        date PX_LAST
1 2016-02-19 1xxxx

$`CAC Index`
        date PX_LAST
1 2016-02-19 4xxxx

$`INDU Index`
        date  PX_LAST
1 2016-02-19 1xxxx
```
(manually edited out BB price data)

I tried looking into the R and C++ code but I cannot seem to find where it goes wrong.  It looks like it happens in the C++ implementation of `bdh_Impl`.  Perhaps Rcpp just casts it as a list and then R reorganises?

**Comment by eddelbuettel** [comment]
This was previously discussed in another issue, and dismissed.

**Please** search old issue before (effectively re-)reporting the same.

**Comment by pgarnry** [comment]
@madcowgoatsmuggla see #101

**Comment by eddelbuettel** [comment]
Thanks for adding the reference, @parny.   In essence, the story is that we 'merely' give back to you what we get from Bloomberg.  We never promise a particularly sorted order.

I just added a word on that in commit 649be35 which expands the help page ever so slightly.

**Comment by wmorgan85** [comment]
Bloomberg provides a sequenceNumber value in each securityData element of the response. This represents the position of that returned security in the original array of requested securities. This could be used to construct a resultant data frame following the requested order.

**Comment by eddelbuettel** [comment]
Interesting.  PRs welcome.

**Comment by eddelbuettel** [comment]
```r
R> Rblpapi::bdh(securities = c("SPX Index", "CCMP Index"), fields = "PX_LAST", start.date = Sys.Date() - 10, end.date = Sys.Date() - 10, verbose=TRUE)
HistoricalDataResponse = {
    securityData = {
        security = "SPX Index"
        eidData[] = {
        }
        sequenceNumber = 0
        fieldExceptions[] = {
        }
        fieldData[] = {
            fieldData = {
                date = 2016-02-19
                PX_LAST = 1917.780000
            }
        }
    }
}
HistoricalDataResponse = {
    securityData = {
        security = "CCMP Index"
        eidData[] = {
        }
        sequenceNumber = 1
        fieldExceptions[] = {
        }
        fieldData[] = {
            fieldData = {
                date = 2016-02-19
                PX_LAST = 4504.429000
            }
        }
    }
}
$`SPX Index`
        date PX_LAST
1 2016-02-19 1917.78

$`CCMP Index`
        date PX_LAST
1 2016-02-19 4504.43

R> 
```

**Comment by eddelbuettel** [comment]
Seems messy to take care of auxiliary data fields but if somebody has an itch to scratch ...

**Comment by armstrtw** [comment]
bds needs to be refactored eventually to use two passes, one to capture the fields (as bbg does not provide a schema or fieldInfo for bds requests), and one to populate the result using the full rank fieldspace (I hope that makes sense, I can elaborate if I explained that poorly).

So, when that refactoring is done, we can capture the results into a vector by seqNumber which should map to the order of the user request.  It's similar to what was done here:
https://github.com/Rblp/Rblpapi/blob/master/src/bdp.cpp#L62

and a check to make sure we match the user request (in case of errors in the security vector, I didn't know how bbg would handle this)
https://github.com/Rblp/Rblpapi/blob/master/src/bdp.cpp#L65

Anyway, this will be an easy fix in terms of the refactoring we need to do.
