### ISSUE TITLE
question on the BDH

### ISSUE THREAD

**Issue by ianliuzhiruo** [Rblp/Rblpapi#140]
My question is using BDH to download the historical data. My code as following:

> MCD <- bdh(securities = "MCD UN Equity",
             fields='RETURN_COM_EQY',
             start.date = as.Date("2004-01-01"),
             end.date=as.Date("2014-12-31"),
             include.non.trading.days = TRUE
)

the results will give me a lot of NAs, which is different from using EXCEL.
I am not sure if the question is BDH has no options to carry over values.
Please help me

**Comment by eddelbuettel** [comment]
Sorry, but we are not a help desk.  If you have a bug report, please provide a minimally reproducible  example.  This isn't really one.
