### ISSUE TITLE
Does Rblpapi have to be used on bloomberg terminal?

### ISSUE THREAD

**Issue by fzhang612** [Rblp/Rblpapi#143]
Hi, a very preliminary question - at work I have a laptop running R and a bloomberg terminal on the desk next to me. If I'd like to try this package, do I need to install R and Rblpapi on the bloomberg terminal? Or can I just simply use it on my laptop and make it connect to the bloomberg terminal somehow?

Many thanks,

Martin

**Comment by wmorgan85** [comment]
Hi Martin,

The Desktop API requires that you be logged into Bloomberg to retrieve data
so you should install R and Rblpapi on the Bloomberg terminal. The contract
makes it clear that any data you fetch using the API must remain on that
terminal.

There are some other licence types, such as BPipe and Server API, that may
allow you to use a different machine from the Bloomberg terminal to
retrieve data. These are generally reserved for use in team or enterprise
level situations. You might want to talk to your account rep about this.

Morgan

**Comment by fzhang612** [comment]
Hi Morgan,

Your answer is very clear. Many thanks.

I will close this issue then.

Martin
