### ISSUE TITLE
bdp function returns error for BID_YIELD

### ISSUE THREAD

**Issue by hakki13** [Rblp/Rblpapi#148]
bdp("EJ421905 Corp", "BID_YIELD")
Error: Attempt to access value of element 'BID_YIELD'(type: 'Float64') as 'bool' type

trying to understand that error, could someone give insights?

Both of these fields work:
"MTY_YEARS_TDY"
"ASSET_SWAP_SPD_MID"

RQ057	BID_YIELD	Bid Yield
is found with fieldSearch(), is it maybe that field is real-time?

maybe correction would be to add additional fields to package, which are not real-time fields:
YLD_YTM_BID
YLD_YTM_MID
YLD_YTM_ASK

-Markku

**Comment by eddelbuettel** [comment]
This may just be a vanilla error on the Bloomberg side in that is 'lies' to us about the field type.

Or ... it may just be you behind.  The current version works for me:

```r
R> bdp("EJ421905 Corp", "BID_YIELD")
              BID_YIELD
EJ421905 Corp -0.021369
R> 
```

So I guess we can close this.

**Comment by hakki13** [comment]
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252    LC_MONETARY=Finnish_Finland.1252
[4] LC_NUMERIC=C                     LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rblpapi_0.3.3

loaded via a namespace (and not attached):
[1] tools_3.2.4 Rcpp_0.12.3

I should be running all the latest versions, have to try something different. Could it have something to do that I have finnish settings? or can you post sessioninfo() so I could think some way to modify my session?

**Comment by eddelbuettel** [comment]
That is strange.  I actually added a 'verbose' option.  I'll send your updated source to win-builder and post the link here once it has built.  You can then try `bdp("EJ421905 Corp", "BID_YIELD", verbose=TRUE)` and we will more closely what we get.

**Comment by hakki13** [comment]
ok, thanks. Will wait for the link and see what we get then.

**Comment by eddelbuettel** [comment]
Here it is:

```
Dear package maintainer,

this notification has been generated automatically.
Your package Rblpapi_0.3.3.1.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
http://win-builder.r-project.org/b0s5a14lKEB4
The files will be removed after roughly 72 hours.
Installation time in seconds: 137
Check time in seconds: 154
Status: 2 NOTEs
R version 3.2.4 (2016-03-10)

All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)
```

This _may_ have something to do with the underlying version / release of the Bloomberg object code.  Here is what I get now:

```r
R> bdp("EJ421905 Corp", "BID_YIELD", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "EJ421905 Corp"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                BID_YIELD = -0.015399
            }
        }
    }
}
              BID_YIELD
EJ421905 Corp -0.015399
R> 
```

**Comment by johnlaing** [comment]
Weird. Same message, different behavior. On Windows:
```R
> bdp("EJ421905 Corp", "BID_YIELD", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "EJ421905 Corp"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                BID_YIELD = -0.015399
            }
        }
    }
}
Error: Attempt to access value of element 'BID_YIELD'(type: 'Float64') as 'bool' type.
```
Checking why this is happening:
```R
> fieldInfo("BID_YIELD")
             id  mnemonic datatype ftype
BID_YIELD RQ057 BID_YIELD    Float  Real
```
but that's the same as we see on LInux

**Comment by hakki13** [comment]
bdp("EJ421905 Corp", "BID_YIELD", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "EJ421905 Corp"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                BID_YIELD = -0.015399
            }
        }
    }
}
Error: Attempt to access value of element 'BID_YIELD'(type: 'Float64') as 'bool' type.

Here is what I got. Not sure if I'm doing everything correctly, but installed 0.3.3.1 from the link and then run the code. (First time ever handeling something like this)

**Comment by eddelbuettel** [comment]
That makes it a valid bug report.  Let us mull this over.

**Comment by hakki13** [comment]
Thank you and really enjoy the package, so thanks for doing stuff for us.

**Comment by eddelbuettel** [comment]
I _think_ we have 3.8.8.1 everywhere.  I'll try adding a function which emits the API version -- that is usually available in a header somewhere.

**Comment by johnlaing** [comment]
OK, here we are. So, this _seems_ like it's working on Linux:
```R
> (x <- bdp("EJ421905 Corp", "BID_YIELD"))
              BID_YIELD
EJ421905 Corp -0.015399
```
Looks good. But is it?
```R
> x$BID_YIELD
[1] "-0.015399"
```
Wait! That's a string. Hmmmm. Bloomberg tells us this is a Float, but we actually don't handle Float! From `Rblpapi_types.h` we have:
```C++
const std::map<std::string, DatatypeT> stringToDatatypeT {
  {"Bool",DatatypeT::Bool},{"Datetime",DatatypeT::Datetime},{"Double",DatatypeT::Double},{"Int32",DatatypeT::Int32},{"Int64",DatatypeT::Int64},{"String",DatatypeT::String}
};
```
We do a `find` into this map. I would expect to get a pointer to `end()` which we check for. Unclear why this isn't working.

**Comment by hakki13** [comment]
Same thing could be happening with COUPON_RT.

bdp("EJ421905 Corp", "COUPON_RT")
Error: Attempt to access value of element 'COUPON_RT'(type: 'Float64') as 'bool' type.

**Comment by hakki13** [comment]
Thank You. Now maybe a stupid question but this correction will be available in next package update? or how does it work?

**Comment by eddelbuettel** [comment]
I already submitted a new build request to win-builder to have a Windows binary -- with the new code -- produced you can test.

And yes, this will be in 0.3.4 (or whatever number the next release gets) but we don't yet know when we will release that.

**Comment by eddelbuettel** [comment]
Please try [this link](http://win-builder.r-project.org/RuVAjTFSw24L) for a windows build off the current (and hopefully fixed) sources.

**Comment by hakki13** [comment]
Yeah, works with package from that Link, and thanks for info.

**Comment by hakki13** [comment]
Is there possibility to contribute/help constructing this package? I'm fairly new to R but maybe I could learn some simple task? For example, I feel like there is some fields missing that I use in Fixed Income. I could try to help, if adding fields is easy?

**Comment by eddelbuettel** [comment]
Yes it is!   

This thread is in a so-called 'issue' ticket.  You can browse existing ones, both open (which includes some that need work) and closed (both work that has been done as well as things that were discussed but rejected).   Generally you would make a copy of the project ("fork it"), work out your changes and then submit a pull request.   We generally prefer an issue ticket discussion prior to an unsolicited pull request.

And documentation, tests, .... are welcome too.   Maybe start by locally rebuilding the package.

**Comment by hakki13** [comment]
Ok, will try to expand my knowledge. Thanks.
