### ISSUE TITLE
Rblpapi OS X with Bloomberg Anywhere

### ISSUE THREAD

**Issue by dibonaventura** [Rblp/Rblpapi#152]
Dear all,

I was not able to find testimonials on whether Rblpapi works on Mac (OS X 10.10.5) with Bloomberg Anywhere. Installing the package and loading it works fine (R Studio with R 3.2.4) but when trying to connect (blpConnect) I get the following:

```
18MAR2016_11:20:39.659 28963:4478988288 ERROR blpapi_platformtransporttcp.cpp:671 blpapi.session.transporttcp.{6}.<localhost:8194> Connection failed 

18MAR2016_11:20:39.660 28963:4478988288 WARN blpapi_platformcontroller.cpp:371 blpapi.session.platformcontroller.{6} Platform: 0 failed 1 consecutive connect attempts, stopped trying to reconnect. 
Error: Failed to start session.
```

Would you expect Rblpapi to work with Bloomberg Anywhere? If so, could you point me in the right direction?

Thanks in advance,
Sven

**Comment by wmorgan85** [comment]
Hi Sven,

Rblpapi will not work with Bloomberg Anywhere because it requires a locally
installed instance of Bloomberg (and more specifically bbcomm) to access
the API. There is a hosted version of Excel in the Citrix Bloomberg
Anywhere environment on Mac OS, however this will not let you connect
through to Rblpapi. This applies more generally to the Bloomberg API in
fact, regardless of the interface you are using.

Morgan

**Comment by johnlaing** [comment]
Closing as I believe Morgan's reply covers it.

**Comment by hbailer** [comment]
Sorry I like to point out that it **absolutely works** with Bloomberg Anywhere. 

You get that error if you don't have the Bloomberg Excel Add-ins installed.

**Comment by henrywoo** [comment]
@hbailer  I have Bloomberg Excel Add-ins installed, but I still cannot connect with Rblpapi. How did you make it work?

**Comment by hbailer** [comment]
@henrywoo if you run Bloomberg Anywhere directly from the Browser it does not work. You need to install the actual terminal software. Since Bloomberg only provides it for Windows OS you need to install parallels & windows on your PC - what a drag...

**Comment by henrywoo** [comment]
I am using Windows OS directly. Are you sure it will work? Are you really using Bloomberg anywhere? If not, why did you say `absolutely`?
