### ISSUE TITLE
Int32 is not enough for VOLUME data

### ISSUE THREAD

**Issue by BenderOlsson** [Rblp/Rblpapi#159]
Hi
I have spotted that bdh throws an error "Error: Attempt to access value of element 'VOLUME'(type: 'Float64') as 'Int32' type." when downloading volume data. This error can be replicated by using ticker "WMT US Equity" and download the complete history, the maximum value the field can take for this security is 39609958400 so clearly Int32 is not enough. The best solution I have is to support Int64 or return the field value as a numeric or character value in case it fails so that the user can manage the issue afterwards.

**Comment by armstrtw** [comment]
I believe this has been fixed. Try with current master.

https://github.com/Rblp/Rblpapi/blob/master/src/blpapi_utils.cpp#L235

**Comment by eddelbuettel** [comment]
```r
R> zz <- bdh("WMT US Equity", c("PX_LAST", "VOLUME"), start.date=as.Date("2016-01-01"))            
R> head(zz)
        date PX_LAST   VOLUME
1 2016-01-04 61.0084 11989191
2 2016-01-05 62.4576 13325958
3 2016-01-06 63.0830 16564620
4 2016-01-07 64.5521 26430005
5 2016-01-08 63.0731 17767864
6 2016-01-11 63.7481 12653762
R> 

```

**Comment by eddelbuettel** [comment]
Old:

```r
R> zz <- bdh("WMT US Equity", c("PX_LAST", "VOLUME"), start.date=as.Date("1900-01-01"))
Error: Attempt to access value of element 'VOLUME'(type: 'Float64') as 'Int32' type.
R>
```

New:

```r
R> library(Rblpapi)
R> zz <- bdh("WMT US Equity", c("PX_LAST", "VOLUME"), start.date=as.Date("1900-01-01"))
R> max(zz[,"VOLUME"])
[1] NA
R> max(zz[,"VOLUME"], na.rm=TRUE)
[1] 3.961e+10
R> 
```

Looks good!

**Comment by BenderOlsson** [comment]
Yes, doing a clean update of the package solved the issue. Thanks guys for quick feedback.
