### ISSUE TITLE
BDH issue with custom indices

### ISSUE THREAD

**Issue by angit617** [Rblp/Rblpapi#160]
I am running version 0.3.3. I have custom index formulas created using CIXN function that the bdh fails to retrieve (works fine in Excel). For example:

.UVOLR index: UVOL Index / (UVOL Index + DVOL Index)

.UVOLR10 index: (.UVOLR U Index + LAG{.UVOLR U Index, 1} + LAG{.UVOLR U Index, 2} + LAG{.UVOLR U Index, 3} + LAG{.UVOLR U Index, 4} + LAG{.UVOLR U Index, 5} + LAG{.UVOLR U Index, 6} + LAG{.UVOLR U Index, 7} + LAG{.UVOLR U Index, 8} + LAG{.UVOLR U Index, 9}) / 10

.UVOLR10 index is the 10 day moving average of .UVOLR. (BBG unfortunately does not allow in CIX to use something like HT017[.UVOLR10 index])

I can retrieve the historical data in Rblpapi for .UVOLR but not for .UVOLR10 index. Excel API gets both. I get the following error:

```t
sd<-as.Date("2016-03-14")
> test<-bdh(c(".UVOLR10 index"), c("PX_LAST"),start.date=sd,end.date= Sys.Date()-1,include.non.trading.days = TRUE)
> test
[1] date    PX_LAST
<0 rows> (or 0-length row.names)
```

Your help is much appreciated. Thank you

**Comment by eddelbuettel** [comment]
Nothing reproducible here for us as we do not have your indices.

**Comment by angit617** [comment]
Hi. Sorry for the confusion. I provided the indices:

Type CIXN in Bloomberg terminal and under ticker type UVOLR index
In the formula section type : UVOL Index / (UVOL Index + DVOL Index)
Then press Enter and click create button

Similarly:
Second index's name is UVOLR10 index and formula is:
(.UVOLR U Index + LAG{.UVOLR U Index, 1} + LAG{.UVOLR U Index, 2} + LAG{.UVOLR U Index, 3} + LAG{.UVOLR U Index, 4} + LAG{.UVOLR U Index, 5} + LAG{.UVOLR U Index, 6} + LAG{.UVOLR U Index, 7} + LAG{.UVOLR U Index, 8} + LAG{.UVOLR U Index, 9}) / 10

.UVOLR index and .UVOLR10 index are now Bloomberg tickers that you can graph for example:
.UVOLR10 index GP

The BDH does not work for .UVOLR10 index
Let me know if you have any questions. Your help is much appreciated

**Comment by johnlaing** [comment]
You could help us more by providing a better description than "does not work". Does it give an error message? What does the error message say? You could start with a copy/paste from your R console showing the exact commands you've executed and their result.

**Comment by angit617** [comment]
Hi. I included the error and the R commands in my initial post. Sorry I should have added it again. Here it is:

d<-as.Date("2016-03-14")
> test<-bdh(c(".UVOLR10 index"), c("PX_LAST"),start.date=sd,end.date= Sys.Date()-1,include.non.trading.days = TRUE)
> test
[1] date    PX_LAST
<0 rows> (or 0-length row.names)

.UVOLRr index is defined as: UVOL Index / (UVOL Index + DVOL Index)
 and
.UVOLR10 index is defined as: (.UVOLR U Index + LAG{.UVOLR U Index, 1} + LAG{.UVOLR U Index, 2} + LAG{.UVOLR U Index, 3} + LAG{.UVOLR U Index, 4} + LAG{.UVOLR U Index, 5} + LAG{.UVOLR U Index, 6} + LAG{.UVOLR U Index, 7} + LAG{.UVOLR U Index, 8} + LAG{.UVOLR U Index, 9}) / 10

Are you able to replicate the error ([1] date    PX_LAST
<0 rows> (or 0-length row.names))? Is it an issue with Rblpapi or potentially a bug within the C++ API (Bloomberg issue)? Thank you again for your help.

**Comment by angit617** [comment]
Also based on my testing, it seems that the issue is using a bdh with a custom ticker that has as input other custom tickers. In the example provided above, the bdh function works fine with the .UVOLR index but fails with .UVOLR10  index which has as input another custom ticker (.UVOLR).

**Comment by johnlaing** [comment]
Apologies, I overlooked your R output from the OP. Please try again passing `verbose=TRUE` to `bdh`. This will allow us to see the full content of Bloomberg's returned messages and figure out where the problem lies.

**Comment by angit617** [comment]
Thank you for looking into this. Here is what I got with verbose=TRUE. It seems that Bloomberg returns no data at all. Let me know your thoughts (Bloomberg bug?) . Thanks again for all the help. 

test<-bdh(c(".UVOLR10 index"), c("PX_LAST"),start.date=sd,end.date= Sys.Date()-1,verbose=TRUE)

HistoricalDataResponse = {
    securityData = {
        security = ".UVOLR10 index"
        eidData[] = {
        }
        sequenceNumber = 0
        fieldExceptions[] = {
        }
        fieldData[] = {
        }
    }
}

**Comment by armstrtw** [comment]
Why don't you try with another CIX to see if it works.  Perhaps one that's not a CIX of another CIX.

I just tried it on a CIX which is a simple linear combo of two swap series and it worked...

**Comment by angit617** [comment]
The issue is when it's a combo of CIX's. I agree that simple CIXs work fine. The problem is that I have a lot of combos of CIXs :(

It's surprising that the combo of CIXs works fine in the Excel API.

**Comment by joel23888** [comment]
I replicated the issue in R. Then I tested in Excel using BDH and it returns data as expected for .UVOLR but returns an error (no data) for .UVOLR10.

**Comment by joel23888** [comment]
This is not an issue with Rblpapi. OP, try an earlier start date in your `bdh` call. For example:

```
> sd<-as.Date("2016-03-01")
> bdh(".UVOLR10 index", "PX_LAST",start.date=sd,end.date= Sys.Date()-1,include.non.trading.days = TRUE)
         date PX_LAST
1  2016-03-01      NA
2  2016-03-02      NA
3  2016-03-03      NA
4  2016-03-04      NA
5  2016-03-05      NA
6  2016-03-06      NA
7  2016-03-07      NA
8  2016-03-08      NA
9  2016-03-09      NA
10 2016-03-10      NA
11 2016-03-11      NA
12 2016-03-12      NA
13 2016-03-13      NA
14 2016-03-14  0.6403
15 2016-03-15  0.5877
16 2016-03-16  0.5781
17 2016-03-17  0.5765
18 2016-03-18  0.5624
19 2016-03-19      NA
20 2016-03-20      NA
21 2016-03-21  0.5446
22 2016-03-22  0.5699
23 2016-03-23  0.5178
24 2016-03-24  0.5227
25 2016-03-25      NA
26 2016-03-26      NA
27 2016-03-27      NA
28 2016-03-28  0.4894
29 2016-03-29  0.5260
30 2016-03-30  0.5670
31 2016-03-31  0.5440
32 2016-04-01  0.5175
33 2016-04-02      NA
34 2016-04-03      NA
35 2016-04-04  0.4845
```

I figured this out by asking BBG's help desk. It is to do with CIX requiring all your underlying (lagged) custom indices to have valid values. Please ask them if you need more details.

**Comment by joel23888** [comment]
OP, can you try setting your start date in the bdh request to 3/1/2016 or earlier. I believe this should solve the issue. It worked for me.

**Comment by eddelbuettel** [comment]
Thanks _so much _ for that follow-up.  I'll close the ticket now.

**Comment by angit617** [comment]
Thank you for your help. You are correct. I had tested in Excel with an older date. All my custom indices work now with older dates. I really appreciate you taking the time to look into this. Much appreciated!
