### ISSUE TITLE
Change GFUT<go> settings from Rblpapi

### ISSUE THREAD

**Issue by brettmichael9** [Rblp/Rblpapi#162]
I typically deal with a lot of futures data and this requires changing the futures (GFUT <go> in the Bloomberg terminal) quite frequently. Currently, in order to do this, before I run the code in R I need to go to the terminal and change the GFUT<go> settings and then run the code. It would be very useful to be able to change those settings within R so the code can run seamlessly without any interruptions in having to go to the terminal.

**Comment by johnlaing** [comment]
I'm not aware of any Bloomberg functionality to support this. However, frequently you can achieve certain behavior (like roll convention) by using decorators on the ticker. I think @armstrtw might have more to say on this since he trades futures.

**Comment by eddelbuettel** [comment]
For some functions, both `options()` and `overrides()` are available and somewhat documented in the [developer's guide](http://www.bloomberglabs.com/files/2014/07/blpapi-developers-guide-2.54.pdf).  That said, AFAIK terminal settings take precedence in many (most? all?) cases.   

We would probably need someone from Bloomberg to weigh in on this.

**Comment by armstrtw** [comment]
We all pay a high price for the privilege of being able to use the very capable bbg help desk. I suggest you reach out to them, or consult this doc:

DOCS #2072138 <GO>

**Comment by armstrtw** [comment]
will you please close this now?
