### ISSUE TITLE
bds returns null when requesting portfolio data

### ISSUE THREAD

**Issue by kriskumar** [Rblp/Rblpapi#169]
bds function returns null when you request portfolio data.

The call bds("U13140014-39 Client","PORTFOLIO_DATA") returns portfolio details in excel but returns NULL in R.

**Comment by eddelbuettel** [comment]
Is there a chance you could turn this into something reproducible?  

I doubt we can see `U13140014-39 Client`, can we?

**Comment by johnlaing** [comment]
I spoke to Kris about this before he opened the issue and he shared the portfolio with me:
```
> bds("U1340014-39 Client", "PORTFOLIO_DATA", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "U1340014-39 Client"
            eidData[] = {
            }
            securityError = {
                source = "2407::bbdbl15"
                code = 15
                category = "BAD_SEC"
                message = "Unknown/Invalid Security  [nid:2407] "
                subcategory = "INVALID_SECURITY"
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
            }
        }
    }
}
NULL
```

I'll troubleshoot further myself, just wanted to log it here

**Comment by kriskumar** [comment]
The new version works like magic thanks!
