### ISSUE TITLE
Error when using beqs

### ISSUE THREAD

**Issue by killitmore** [Rblp/Rblpapi#170]
I got this error when using beqs for screen not from general folder in bloomberg
Choice sub-element not found for name 'data'
Please help me or an explanation is great.

**Comment by eddelbuettel** [comment]
There is nothing for us to go on here.  Consider the tips in [how to make a great reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).

**Comment by johndog64** [comment]
I can reproduce this error, and resolve it.

I get the same error with the following:
```
head(beqs("Exchanges: Australia","GLOBAL",date=as.Date("2015-09-30")),20)
Error in beqs_Impl(con, screenName, screenType, group, datestr, language,  : 
  Choice sub-element not found for name 'data'.
```
At the time, I thought screen name was simply the selection criteria I entered to get the results I wanted within the bloomberg terminal. 

However, if I am smarter, and I save my screen within the bloomberg terminal (under actions menu), and then use the ```PRIVATE``` screen type in the ```beqs``` call, then I get the result I want:
```
head(beqs(screenName="era australia",screenType="PRIVATE",date=as.Date("2015-09-30"),
            language = "ENGLISH",group="",verbose=TRUE,con=conn),20)
```
Debugging was helped with ```verbose=TRUE```. The issue initially was thus a miss-specified or non-existent ```beqs``` argument value, that returned the ```Choice sub-element not found for name 'data'``` message.

Close the ticket?

**Comment by csrvermaak** [comment]
The beqs() user guide states the input parameters:

`screenName` - A character string with the name of the screen to execute. It can be a user defined EQS screen or one of the Bloomberg Example screens on EQS

Unless you have a saved screen called "Exchanges: Australia", there won't be any data. (as an aside, I have to add that EQS is quite sensitive to screen names, thus I'm not sure it would like a colon in the screen name)

The `group` argument is used to specify the folder, if not in "General"

The documentation is clear in my view - please close the ticket if you agree.

**Comment by johndog64** [comment]
If you read carefully my response is didactic, as I was trying to help out killitmore, and others who face the debugging message:
```Choice sub-element not found for name 'data'```
The issue isn't the package documentation, it is the fact one gets an overly cryptic error message, when a much simpler one would do. E.g. 
```screenName is misspecified```
In fact, you don't get a good debugging message until you do ```verbose=TRUE```

**Comment by eddelbuettel** [comment]
@johndog64 We were not passing judgement on your message, we were cleaning up a dangling issue ticket which is, as @csrvermaak pointed out, addressed.

If you want to improve _documentation_ a small PR to the _documentation_ strikes me as a better way than leaving comments here.  Your call.

**Comment by csrvermaak** [comment]
@johndog64 - appreciate that. But Rblpapi is just a very light wrapper around the BBG api, and the `Choice sub-element not found for name 'data'` message is passed through from BBG. There is no way of checking if a screen exists before submitting the request. You could follow up with BBG to refine the error message on their side.

**Comment by armstrtw** [comment]
haha, you can follow up w/ bbg on your time.  That's a fools errand in my opinion.

However, I think we can catch the errors and display them.  they are part of the node structure that comes back, but we're not attempting to find them at the moment.

**Comment by johndog64** [comment]
The ticket question was:
I got this error when using beqs for screen not from general folder in bloomberg
Choice sub-element not found for name 'data'
Please help me or an explanation is great.

The response was:
provide a reproducible example

I simply gave you an example reproducing the debugging message, provided an explanation as to why it occurs and recommended closing the ticket.

I didn't see the subsequent question as addressing the initial question so I said as  much. Sorry if I rubbed you up the wrong way.

Armstrtw is on the money and straight up and down - I wouldn't want to translate the api debug messaging for bbg either unless I got paid to :P
