### ISSUE TITLE
Error: Attempt to access value of element 'VOLUME'(type: 'Float64') as 'Int32' type

### ISSUE THREAD

**Issue by cestob** [Rblp/Rblpapi#172]
Running the example code verbatim from the bdh {Rblpapi} documentation
opt <- c("periodicitySelection"="MONTHLY")
Rblpapi::bdh("SPY US Equity", c("PX_LAST", "VOLUME"), start.date=Sys.Date()-31*6, options=opt)

I get the following error
Error: Attempt to access value of element 'VOLUME'(type: 'Float64') as 'Int32' type.

**Comment by johnlaing** [comment]
What version are you using? Works fine for me.

**Comment by cestob** [comment]
R version [64-bit] C:\R\R-3.2.3
Rblpapi 0.3.3

**Comment by eddelbuettel** [comment]
Please use the [ghrr drat repository](http://ghrr.github.io/drat/) for an updated package _including a Windows binary_.

**Comment by eddelbuettel** [comment]
Rblpapi 0.3.4 has been released so closing this.
