### ISSUE TITLE
system requirement to have a valid Bloomberg installation in order to use this library?

### ISSUE THREAD

**Issue by Ivanaz916** [Rblp/Rblpapi#174]
CRAN documentation states a system requirement is to have a valid Bloomberg installation in order to use this library.

I thought the idea behind the Bloomberg open api was to remove this requirement, and allow both Bloomberg subscribers and non subscribers access?(http://www.bloomberglabs.com/api/faq/)

"Bloomberg subscribers, non-Bloomberg customers, vendors and software developers can use this technology as an alternative to proprietary interfaces for market data distribution."

Can this be clarified?  If I don't need the Bloomberg subscription what are the initial steps to take in order to begin retrieving market data with the Rblpapi package?

**Comment by eddelbuettel** [comment]
You do need a Bloomberg subscription to retrieve data from Bloomberg.

The Open API, as I understand, is a mechanism ("plumbing" if you wish) for others to contribute data.

**Comment by Ivanaz916** [comment]
Great, thanks.
Reviewing the documentation on how to retrieve a unique user id token (p.66 of http://www.bloomberglabs.com/api/content/uploads/sites/2/2014/07/blpapi-developers-guide-2.54.pdf)

I guess I need to use C++ to request generation of the token for the uuid?
