### ISSUE TITLE
Cant download any data after updating rcpp

### ISSUE THREAD

**Issue by BenderOlsson** [Rblp/Rblpapi#175]
Hi
I've just updated to the latest rcpp package that came out 2 days ago. After doing that the Rblpapi package stopped working.

After connecting and running this simple line I get the following error.
bdp("SPX Index","PX_LAST")
Error: Choice sub-element not found for name 'securityData'.

Any advice what to do?
Regards
Tom

**Comment by eddelbuettel** [comment]
What OS? What version?  How did you install (binary or source) ?

**Comment by BenderOlsson** [comment]
I'm on win7, 64 bit OS, started with the Rstudio update function on both R 3.2.4 and the new R.3.3.0. After the initial issues I removed all the required packages and did a clean new installation directly from R. Have only tried from source so far.

**Comment by eddelbuettel** [comment]
Appreciate the follow-up. I am a little puzzled.  Especially from _source_ things should just work--I tend to upgrade Rcpp and other packages all the time without side effects.

Can you try some local debugging at your end?

**Comment by BenderOlsson** [comment]
sure, what do you want me to run

**Comment by BenderOlsson** [comment]
I think we can drop this issue, I ran som diagnostics directly from the c++ api against Bloomberg and looking at the response message I have hit a data limit and since Rblpapi doesn't currently read those messages properly they looked at something else.

I know you have a request about managing Limit exceptions and since I'm apparently hit a limit, could I assist in some other way by sending some samples for you to work on?

**Comment by eddelbuettel** [comment]
Sorry was in a meeting.  And sorry to hear about your limits being hit -- happened to us too a while back.  I think turning on the verbose flag can help.
