### ISSUE TITLE
Rblpapi in the era of R in SQL Server 2016

### ISSUE THREAD

**Issue by aoeusnth** [Rblp/Rblpapi#177]
SQL Server 2016 (just released 6/1/16, gotta love the palindrome) has an in-built R implementation through the purchase of Revolution Analytics. I'm going to get a trial of it soon, but I do not anticipate any problems loading and running the Rblpapi package.

The main advantage is to be able to call R data analytics on SQL data sitting right "next door", all from within a single stored procedure call.

What I wonder is how to pass a valid Bloomberg license token through to the SQL server. The idea is to allow any given user, having already logged into a Bloomberg Terminal on his/her own PC, to run a piece of R code that called for Bloomberg data via said SQL stored procedure.

The alternative of having one user log into a Bloomberg Terminal the SQL Server box wouldn't work in general: if a bunch of users were calling the R code (via SP) then you'd probably abut Bloomberg data limits pretty rapidly. And also, every user has different default sources, etc.

**Comment by eddelbuettel** [comment]
You have not explained what has to do with us. 

Rblpapi is written in a generic fashion for all R engines.  If you want or need something from a particular engine,  contact its vendor. 

I plan on closing this unless you provide compelling reasons not to.

**Comment by johnlaing** [comment]
I think you're looking for `?blpAuthenticate`. You may also want to look at Bloomberg's Server API product, which sounds like a fit for what you're trying to do.

**Comment by aoeusnth** [comment]
Apologies: I do not foresee any issues with running Rblpapi on a server running SQL Server 2016.

I was looking for something like blpAuthenticate; I'll do some tests. Basically the goal is to connect using another user's Bloomberg credentials.
