### ISSUE TITLE
Using Options in BDH

### ISSUE THREAD

**Issue by anmolsethy** [Rblp/Rblpapi#178]
Hi, 
I am trying to use bdh with a set of options (the eqvt query used to work in Rbbg), but here I am getting 
Error: Sub-element '(null)' does not exist 
Will appreciate your help.

So this seems to work fine:

 bdh("NKY Index", "PX_LAST",as.Date("2011-12-31"),as.Date("2015-12-31"))
     date PX_LAST
1  2012-01-04 8560.11
2  2012-01-05 8488.71
3  2012-01-06 8390.35
4  2012-01-10 8422.26

Now, suppose I use a set of options defined as

opt <- c("FX"="USD","Per"="CM","Fill=P")

I get:

 bdh("NKY Index", "PX_LAST",as.Date("2011-12-31"),as.Date("2015-12-31"),options=opt)
Error: Sub-element '(null)' does not exist.

**Comment by anmolsethy** [comment]
I continued some  other methods. and got success.
Just mentioning my corrections here so that it might help in the future-

1. So for one thing, one cannot directly use the Excel fields, one needs to use the API field names.
For eg for FX, it is actually called currency.

So this one works
ovr <- c("Currency"="USD")

bdh("NKY Index", "PX_LAST",as.Date("2011-12-31"),as.Date("2015-12-31"),overrides = ovr)

2. I still dont know how to find out, but some fields go in as overrides and some as options.
So this one also works perfect

 ovr <- c("Currency"="USD")
 opt <- c("periodicityAdjustment"="CALENDAR","periodicitySelection"="MONTHLY" )
 bdh("NKY Index", "PX_LAST",as.Date("2011-12-31"),as.Date("2015-12-31"),overrides = ovr,options=opt)

Thanks
Anmol

**Comment by Mas2345** [comment]
I had this issue too, but I'm trying to set different options. Where can you find the list of available API options?
