### ISSUE TITLE
BTSM function

### ISSUE THREAD

**Issue by maximedb** [Rblp/Rblpapi#181]
Hello, 

Thank you for this great library. I use it almost everyday. 

Is there any plan on developing something similar to the BTSM function in Excel ? It is used to download accounts' positions from Bloomberg AIM (Bloomberg PMS).

Thank you in advance,
Maxime.

**Comment by johnlaing** [comment]
I wasn't aware something like this existed. Interesting idea, and I see how it works in Excel. There doesn't seem to be any reference to this in the standard doc. I'm asking Bloomberg, we'll see what they can come up with.

**Comment by maximedb** [comment]
I did not find any documentation either.. a colleague of mine told me about it. 
Here is how I get it to work on Excel:
=BTSM("PRICING_NUMBER: DATABASE_NAME","PRICING_NUMBER","Account","ID_CUSIP","SecFmt=ST","SecFltr=AL","ResBy=SC","PosBy=C","PosIn1K=No","SecRisk=No","IncCash=No")

replace PRICING_NUMBER & DATABASE_NAME

**Comment by armstrtw** [comment]
This function looks really interesting, and I'd love to use it.  Being able to use it in excel means the services are exposed in the api, but just not documented.

I was going to suggest wiresharking the protocol and trying to pull out the exact service calls, but I really think that is a path fraught w/ serious difficulty.

I think the only way to implement this would be if BBG provides documentation or if you crack the excel add-in and actually see the calls that are being made.  The former seems unlikely, and the latter may violate the end user agreement, I haven't really looked into that sort of thing.

I did glance at the source for the python api, and I didn't find the string 'btsm' anywhere in the source, but that was the extent of my attempt to find it.

Happy to discuss more.

**Comment by johnlaing** [comment]
I spoke with Bloomberg about this -- it turns out that trading services are handled by a separate backend service and therefore not available via our API connection. The Excel add-in does have this connection but we are out of luck.
