### ISSUE TITLE
bds: attempt to access value of element

### ISSUE THREAD

**Issue by pgarnry** [Rblp/Rblpapi#184]
There seems to be an input type issue in the bds function on a field such as "COUNT_INDEX_MEMBERS" which has not happened before.

`Rblpapi::bds("SPX` Index", "COUNT_INDEX_MEMBERS")

> Error: Attempt to access value of element 'COUNT_INDEX_MEMBERS'(type: 'Int32') as 'Element' type.

**Comment by eddelbuettel** [comment]
Grrr:

```r
R> bds("SPX Index", "COUNT_INDEX_MEMBERS", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "SPX Index"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                COUNT_INDEX_MEMBERS = 505
            }
        }
    }
}
Error: Attempt to access value of element 'COUNT_INDEX_MEMBERS'(type: 'Int32') 
as 'Element' type.
R>
R> fieldInfo("COUNT_INDEX_MEMBERS")
                       id            mnemonic datatype  ftype
COUNT_INDEX_MEMBERS DS680 COUNT_INDEX_MEMBERS    Int32 String
R> 
```

This is more them than us with the Int32 <-> String confusion but I guess one of us can chase that down.  We had similar issues before.

**Comment by pgarnry** [comment]
Works with bdp, which makes sense. Went back and worth with Bloomberg support and it did work previously with bds. Anyway, Rblpapi works as intended!
