### ISSUE TITLE
Problem adding Options/overides in BDS

### ISSUE THREAD

**Issue by aludolf** [Rblp/Rblpapi#185]
Hi,
I am having trouble specifying a curve date for a BDS query.

This unconstrained query works
```r
df = bds("YCGT0372 Index", "CURVE_TENOR_RATES", options = NULL, overrides = NULL, 
              verbose = FALSE, identity = NULL, con = defaultConnection())
```

But when I try to set an Option 
```r
opt = "CURVE_DATE"="20150701"
df2 = bds("YCGT0372 Index", "CURVE_TENOR_RATES", options = opt, overrides = NULL, 
                verbose = FALSE, identity = NULL, con = defaultConnection())`
```

I crash the instance of R and get the following message:
"This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

Any hints? I’ve tried to set the CURVE_DATE at the overrides with the same results and I was mimicking the syntax of the example queries from the documentation.

```
## example of using overrides
  overrd <- c("START_DT"="20150101", "END_DT"="20160101")

  bds("CPI YOY Index","ECO_RELEASE_DT_LIST", overrides = overrd)
```

**Comment by eddelbuettel** [comment]
Your `opt` is not valid R.

**Comment by aludolf** [comment]
Tks Eddel for this quick reply,and sorry about this basic syntax problem.
could you clarify why the example with the 'overrd' works 'overrd <- c("START_DT"="20150101", "END_DT"="20160101")' and mine with the 'opt' don't? also tried with 'opt = c("CURVE_DATE"="20150701")'

**Comment by eddelbuettel** [comment]
Please look up the formatting help to provide proper questions. I edited one for you, I do not plan to edit all your work.  If you try to address me by name, try one I am actually using.

**Comment by aludolf** [comment]
Sorry about that, will not happen again.
closing this topic
