### ISSUE TITLE
XM1 PIT Comty - odd intraday time buckets

### ISSUE THREAD

**Issue by gity84571** [Rblp/Rblpapi#188]
Hello.

When I download intraday data for the above security using getBars( ) I get data which is spaced unusually - 00:27, 00:32, 00:37 etc.  - I think - because the security opens at 2:32am. Is there a way to force the data downloaded to conform to buckets 00:25, 00:30, 00:35 etc.? That is, every 5th minute as is the typical case for other securities? My code and output are below:

    xts1 <- getBars("XM1 PIT Comdty", 
                        eventType = "TRADE", 
                        barInterval = mins,
                        startTime = start1,
                        endTime = end1,
                        options = NULL,
                        verbose = FALSE,
                        returnAs = getOption("blpType", "xts"),
                        tz = Sys.getenv("TZ", unset = "UTC"),
                        con)
    
7/12/16 00:27	98.06
7/12/16 00:32	98.055
7/12/16 00:37	98.05
7/12/16 00:42	98.05

Thank you very much for your time and the lovely package.

**Comment by eddelbuettel** [comment]
I would tend to say _Nope there ain't_ because we simply call into the Bloomberg backend and then faithfully report what we get back.  So unless you find an option to specify such a time grid you may be out of luck.

But the again these things are pretty easy to do on the _client_ side, ie in R itself, by a few lines of time index manipulation with eg the `xts` package.

**Comment by wmorgan85** [comment]
This is easily done by controlling the start time in the Bloomberg request. 

The following returns data in the way you are expecting:
```
getBars("XM1 PIT Comdty", 
        eventType = "TRADE", 
        barInterval = 5, 
        startTime = as.POSIXct("2016-07-12 00:25", tz="GMT"), 
        endTime = as.POSIXct("2016-07-12 12:25", tz="GMT"))
```

**Comment by eddelbuettel** [comment]
Spot on. I overlooked the ill-specified start time in the original question.

**Comment by gity84571** [comment]
Thank you. But wmorgan85's solution only works if it is one day's of data which is being downloaded. The below call will produce the data with irregular spacing after market close on the 7th, even though "PIT" was included in the ticker. 

    xts2 <- getBars("XMU6 PIT COMDTY", 
                eventType = "TRADE", 
                barInterval = 5,
                startTime =  as.POSIXct("2016-07-07 00:25", tz="GMT"),
                endTime =  as.POSIXct("2016-07-11 12:25", tz="GMT"),
                options = NULL,
                verbose = FALSE,
                returnAs = getOption("blpType", "xts"),
                tz = Sys.getenv("TZ", unset = "UTC"),
                con)

**Comment by wmorgan85** [comment]
Ok - the way around this is effectively with what's called RecurDaily in the equivalent BDH formula in Excel. This was a special feature added to allow retrieval of bars between specific windows over multiple days, i.e. 9-10am every day. Unfortunately it was added as a separate request type called IntradayBarDateTimeChoiceRequest. This is not currently built into the Rblpapi library.
