### ISSUE TITLE
Can't invoke library(Rblpapi)

### ISSUE THREAD

**Issue by Cashangu** [Rblp/Rblpapi#189]
I am working on a OS X version or R/RStudio. I have been able to successfully install Rlpapi package, but but when invoking `library(Rblpapi)` I get the following message. 

I have updated to the latest version of R & RStudio. 

Suggestions on how to resolve this issue?

Thanks

---

``` r
library(Rblpapi)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rblpapi/libs/Rblpapi.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rblpapi/libs/Rblpapi.so, 6): Library not loaded: @rpath/libblpapi3_64.so
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rblpapi/libs/Rblpapi.so
  Reason: image not found
Error: package or namespace load failed for ‘Rblpapi’
```

**Comment by eddelbuettel** [comment]
We need more details on how you installed, how the install went, what tools you used etc pp.

Other people are happily using Rblpapi on OS X.

(Please also look into formatting help on GH and learn about ``` for code blocks and ` ` for words.)

**Comment by Cashangu** [comment]
This is the command I used to install the package. 

Does it help? What info would you need in detail so that I can provide?

I am not an expert on R, or a developer, but I want to start using R on finance related applications. Thanks 

---

> install.packages("Rblpapi")
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/Rblpapi_0.3.4.tgz'
Content type 'unknown' length 3694421 bytes (3.5 MB)
==================================================
downloaded 3.5 MB


The downloaded binary packages are in
	/var/folders/kn/tg7b6z3j2q7bd_46psls2fk00000gn/T//RtmpTA20lv/downloaded_packages
>

**Comment by spennihana** [comment]
Hi,
I experienced and fixed this issue and wanted to leave a note for future travelers:

It's related to macos SIP (intro'd in El Capitan) and relative rpath libblpapi3_64.so in Rblpapi.so.

The fix is to install the absolute path to libblpapi as follows:

```
$ cd /Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rblpapi/libs
$ otool -L Rblpapi.so
Rblpapi.so:
	Rblpapi.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libblpapi3_64.so (compatibility version 3.8.1, current version 3.8.1)
	/Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libR.dylib (compatibility version 3.4.0, current version 3.4.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1259.0.0)
	/Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

note the `@rpath`. Now let's install the absolute path:

```
install_name_tool -change @rpath/libblpapi3_64.so /Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rblpapi/blp/libblpapi3_64.so Rblpapi.so
```

That should do it:

```
> library(Rblpapi)
Rblpapi version 0.3.6 using Blpapi headers 3.8.1.1 and run-time 3.8.1.1.
Please respect the Bloomberg licensing agreement and terms of service.
```

**Comment by eddelbuettel** [comment]
Can you take a look at the corresponding code in the package and maybe suggest a PR?

**Comment by spennihana** [comment]
Sure thing. I'm not too familiar with how this package is built, but a change to src/Makevars.in is the likely place to put this. Any pointers to bootstrapping the build on my machine to test are appreciated.

**Comment by eddelbuettel** [comment]
That is exactly the place as we do call `install_name_tool` there.  But as we're not on Darwin it is hard(er) for us to test.  If you can think of an improvement ...
