### ISSUE TITLE
Shiny and Rblpapi::subscribe

### ISSUE THREAD

**Issue by juancentro** [Rblp/Rblpapi#190]
Hi, I'm trying to use Rblpapi in a Shiny app. As using bdp is quite slow (1 second per call aprox) I was trying to use subscribe to stream market data directly.
Let's assume I want to subscribe to a single security and field. I have this construct (it is inside a bigger app)

ui.R

```
  tabPanel(
    "Blg Tester",
    shiny::textInput(inputId = "blg_security", label = "Security", value = "EUR Curncy"),
    shiny::textInput(inputId = "blg_field", label = "Field", value = "ASK"),
    shiny::verbatimTextOutput(outputId = "blg_out")
```

server.R

```
  v <- reactiveValues(blg_data = NULL)
  
   observe(
     Rblpapi::subscribe(
      securities = input$blg_security, 
      fields = input$blg_field,
      fun = function(x) v$blg_data <- x))

  output$blg_out <- renderPrint({
    v$blg_data
  })

```

But the app never starts. When I remove this code it works. Have you got any example that uses both Shiny and Rblpapi? I was going to post this on SO, sorry if this the wrong place

**Comment by eddelbuettel** [comment]
I do, but at work so not easy to share.  But I do nothing special.  Oh, and I decoupled things by having R (using Rblpapi) write to Redis, and then shiny pulls data from Redis (on a counter) and displays it.  I think I gave a short talk about the basics a while back though.

**Comment by juancentro** [comment]
Thanks Dirk. I was thinking about decoupling too. Not familiar with Redis, and I am running on Windows, so maybe an in memory Sqlite db might do.

2 questions

1 - I checked your presentations at [](http://dirk.eddelbuettel.com/bio/presentations.html) but couldnt find anything relating Shiny and Rblpapi. Would you be so kind as to share a link?

2- In your experience, is the 1 second mark for a simple BDP request expected? Is there someway to optimize it? (maybe reuse subscriptions)

Thanks for the package, it is great

**Comment by eddelbuettel** [comment]
Regarding points

1. There is no magic.  Shiny can execute valid R statements.  Rblpapi provides R functionality to talk to Bloomberg.

2. That strikes me as aggressive.  Bloomberg is famously vague about how, when, where, ... you hit the data limit but it has happened when a colleague sent off something too broad (in hindsight).  But YMMV.

**Comment by eddelbuettel** [comment]
I am closing this as it hasn't demonstrated a reproducible and addressable issue in Rblpapi.
