### ISSUE TITLE
getBars( ) documentation

### ISSUE THREAD

**Issue by gity84571** [Rblp/Rblpapi#192]
Hello.

https://cran.r-project.org/web/packages/Rblpapi/Rblpapi.pdf

The documentation at the above URL reads:

"Note that the ‘time’ value is adjusted: Bloomberg returns the opening time of the bar interval, whereas financial studies typically refer to the most recent timestamp. For this reason we add the length of the bar interval to time value from Bloomberg to obtain the time at the end of the interval."

However, the data downloads by default with the timestamp referring to the opening time of the bar interval. Maybe the documentation should be changed to make it clear that you all did not override this behavior:

"Note that the ‘time’ value is adjusted: Bloomberg returns the opening time of the bar interval, whereas financial studies typically refer to the most recent timestamp. Therefore, if one wants the timestamp associated with the end of the bar interval one should add the  length of the bar interval to time value from Bloomberg to obtain the time at the end of the interval."

Just a suggestion.

Great package! Thank you.

**Comment by gity84571** [comment]
I will close this issue. Thank you.

**Comment by eddelbuettel** [comment]
I keep this open. I should make that change. 

(FWIW I recently had the same issue when compute OHLC bars from (our) tick data using `data.table()`.)

**Comment by eddelbuettel** [comment]
Change made.  Thanks for the heads-up.  

In the future, consider making a pull request which makes it easier for us to fold this in (and as a side effect records you as the contributor).
