### ISSUE TITLE
Question on Rblpapi overrides for BDP and BDH

### ISSUE THREAD

**Issue by pl260** [Rblp/Rblpapi#194]
Hi.
It seems like my two overrides of:
FILING_STATUS and EQY_FUND_YEAR in the following two formulae is causing the function to not to run and return an error. Am I using the wrong name for these overrides or it it possible they are not supported? 

(The code below is written for Excel, the equivalent R code cause an error.)

=BDP("IBM US Equity", "BS_CASH_NEAR_CASH_ITEM", "FUND_PER=q", "FILING_STATUS=or"). 

=BDP("IBM US Equity","FUNDAMENTAL_PUBLIC_DATE", "FUND_PER","Q1", "EQY_FUND_YEAR","2012","FILING_STATUS=OR")

Thank you in advance.

**Comment by eddelbuettel** [comment]
Please provide reproducible R code for us look at.

**Comment by pl260** [comment]
These are the pieces of code that produce an error because of the overrides:

bdp("IBM US Equity", "BS_CASH_NEAR_CASH_ITEM", overrides=c(FUND_PER="Q", FILING_STATUS= "OR"))

bdp("IBM US Equity","FUNDAMENTAL_PUBLIC_DATE", overrides=c(FUND_PER="Q1", EQY_FUND_YEAR="2012", FILING_STATUS="OR"))

Thank you for your help.

**Comment by eddelbuettel** [comment]
I am not sure I follow.  Both calls work for me here.   It is unclear what you expected, what you got and why that would be a problem.  I can't help you on information like this.

```r
R> bdp("IBM US Equity", "BS_CASH_NEAR_CASH_ITEM", overrides=c(FUND_PER="Q", FILING_STATUS= "OR"))
              BS_CASH_NEAR_CASH_ITEM
IBM US Equity                  10017
R> bdp("IBM US Equity", "BS_CASH_NEAR_CASH_ITEM")
              BS_CASH_NEAR_CASH_ITEM
IBM US Equity                   7686
R> bdp("IBM US Equity","FUNDAMENTAL_PUBLIC_DATE", overrides=c(FUND_PER="Q1", EQY_FUND_YEAR="2012", FILING_STATUS="OR"))
              FUNDAMENTAL_PUBLIC_DATE
IBM US Equity              2012-04-24
R> bdp("IBM US Equity","FUNDAMENTAL_PUBLIC_DATE")
              FUNDAMENTAL_PUBLIC_DATE
IBM US Equity              2016-02-23
R> 
```

**Comment by pl260** [comment]
Dirk,
My apologies for the error in my code. I was mixing up the "options" keyword with the "overrides" keyword and that was causing the errors. Your confirmation helped me trace the problem. 
Thank you again and sorry to trouble you.

**Comment by eddelbuettel** [comment]
No worries. It is a little confusing with `overrides=` versus `options=` but that is how it is.

Closing this now.
