### ISSUE TITLE
Rblpapi with Bloomberg Anywhere

### ISSUE THREAD

**Issue by henrywoo** [Rblp/Rblpapi#195]
I see somebody mentioned it works with Bloomberg anywhere. How to do that?

**Comment by eddelbuettel** [comment]
No bonus points, or sympathy, for spamming the issue tickets.  We got the other one, so why this?

Please do not abuse free resources,  and maintainer attention / sympathy.

**Comment by henrywoo** [comment]
Sorry I didn't mean to spam the ticket. I just saw somebody said it's Absolutely Possible to connect Bloomberg Anywhere with excel using Rblpapi. But he did not provide any details. Do you know how to do it?

**Comment by eddelbuettel** [comment]
I do not, and have personally never stated whether it works or does not.  I use a standard Bloomberg installation; I think that is referred to as Bloomberg Desktop but I could be wrong.
