### ISSUE TITLE
Installation problems - github, getPortfolio

### ISSUE THREAD

**Issue by akarpf** [Rblp/Rblpapi#196]
Hi,

I am currently trying to install the github version of your awesome library. I need to download a large number of tickers from a portfolio. I found out that the github version contains the getPortfolio function, which seems to to accomplish this task, while the Cran version doesn't. So the logical next step would be to install the whole thing via devtools/install_github but here I unfortunately get the following error message:

> Downloading GitHub repo Rblp/Rblpapi@master
from URL https://api.github.com/repos/Rblp/Rblpapi/zipball/master
Installing Rblpapi
"D:/Utilisateurs/BloomBerg/Documents/R/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "D:/Utilisateurs/BloomBerg/AppData/Local/Temp/RtmpgFZslW/devtools1b7459e85ba6/Rblp-Rblpapi-d5a9fc9"  \
  --library="D:/Utilisateurs/BloomBerg/Documents/R/R-3.3.1/library" --install-tests 

>* installing *source* package 'Rblpapi' ...

>   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

>** libs

>*** arch - i386
>curl: not found
mv: cannot stat 'blpHeaders.tar.gz': No such file or directory
tar (child): ../blp/win/i386/blpHeaders.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Exiting with failure status due to previous errors
make: *** [blpLibrary] Error 2
Warning: l'exécution de la commande 'make -f "Makevars.win" -f "D:/UTILIS~1/BLOOMB~1/DOCUME~1/R/R-33~1.1/etc/i386/Makeconf" -f "D:/UTILIS~1/BLOOMB~1/DOCUME~1/R/R-33~1.1/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="Rblpapi.dll" OBJECTS="RcppExports.o authenticate.o bdh.o bdp.o bds.o beqs.o blpConnect.o blpVersion.o blpapi_utils.o bsrch.o fieldsearch.o getBars.o getFieldInfo.o getTicks.o subscribe.o"' renvoie un statut 2
ERROR: compilation failed for package 'Rblpapi'
* removing 'D:/Utilisateurs/BloomBerg/Documents/R/R-3.3.1/library/Rblpapi'
* restoring previous 'D:/Utilisateurs/BloomBerg/Documents/R/R-3.3.1/library/Rblpapi'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problème lors de la copie de D:\Utilisateurs\BloomBerg\Documents\R\R-3.3.1\library\00LOCK-Rblp-Rblpapi-d5a9fc9\Rblpapi\libs\x64\blpapi3_64.dll vers D:\Utilisateurs\BloomBerg\Documents\R\R-3.3.1\library\Rblpapi\libs\x64\blpapi3_64.dll: Permission denied
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problème lors de la copie de D:\Utilisateurs\BloomBerg\Documents\R\R-3.3.1\library\00LOCK-Rblp-Rblpapi-d5a9fc9\Rblpapi\libs\x64\Rblpapi.dll vers D:\Utilisateurs\BloomBerg\Documents\R\R-3.3.1\library\Rblpapi\libs\x64\Rblpapi.dll: Permission denied
Erreur : Command failed (1)

Can anybody advise me on how I can circumvent this problem or how I can get the portfolio tickers by other means? I suppose it has something to do with the configuration file, but what do I have to do? I unfortunately didn't use Windows for a very long time.

Best,

Andreas 

> System:
> R version 3.3.1 (2016-06-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
[1] devtools_1.12.0 Rblpapi_0.3.4  

>loaded via a namespace (and not attached):
[1] httr_1.2.1    R6_2.1.3      tools_3.3.1   withr_1.0.2   curl_1.2      memoise_1.0.0 Rcpp_0.12.7   git2r_0.15.0  digest_0.6.10

**Comment by eddelbuettel** [comment]
`curl: not found`

Install `curl.exe` in the $PATH.

**Comment by akarpf** [comment]
Super, thank you for the ultra fast reply! I read the error message, but I thought it concerns the R library "curl", which is however installed on the system. I will try your solution and report back tomorrow!

**Comment by eddelbuettel** [comment]
You can also avoid the issue by _manually_ downloading the _required_ tarballs into the required directories.  Hard to get right, though, so you may as well install `curl.exe`.

**Comment by akarpf** [comment]
Thank you very much, that solved my problem!
