### ISSUE TITLE
BEST_EPS_YOY_GTH returns NA

### ISSUE THREAD

**Issue by meteorjs3000** [Rblp/Rblpapi#197]
Hi all, I am just starting out on using Rblpapi and Bloomberg and this may sound like a silly question!

I'm trying to get the historical data for 12 month forward values of `BEST_EPS_YOY_GTH` and `BEST_SALES_YOY_GTH`  for say `IBM US Equity`. However the following code is returning `NA` for both of these fields, but not for `BEST_PE_RATIO`.

Why is it giving `NA` and how can we get the actual values?

    monthlyOptions <- structure(c("ACTUAL", "MONTHLY"),
                                names = c("periodicityAdjustment",
                                          "periodicitySelection"))
    
    fields <- c('BEST_PE_RATIO', 'BEST_EPS_YOY_GTH', 'BEST_SALES_YOY_GTH')
    df <- bdh(securities = c('IBM US Equity'), 
               fields = c('BEST_PE_RATIO', 'BEST_EPS_YOY_GTH', 'BEST_SALES_YOY_GTH'),
               start.date = as.Date('2014-01-01'), 
               options = monthlyOptions)

Returns 

    date BEST_PE_RATIO BEST_EPS_YOY_GTH BEST_SALES_YOY_GTH
    1  2015-02-09         8.197               NA                 NA
    2  2015-03-09         8.477               NA                 NA
    3  2015-04-09         8.570               NA                 NA
    4  2015-05-09         9.602               NA                 NA
    5  2015-06-09         9.213               NA                 NA
    6  2015-07-09         9.111               NA                 NA
    7  2015-08-09         8.783               NA                 NA
    8  2015-09-09         8.222               NA                 NA
    9  2015-10-09         9.058               NA                 NA
    10 2015-11-09         8.681               NA                 NA
    11 2015-12-09         8.759               NA                 NA
    12 2016-01-09         8.408               NA                 NA
    13 2016-02-09         8.841               NA                 NA
    14 2016-03-09        10.000               NA                 NA
    15 2016-04-09        10.637               NA                 NA
    16 2016-05-09        10.433               NA                 NA
    17 2016-06-09        10.864               NA                 NA
    18 2016-07-09        10.968               NA                 NA
    19 2016-08-09        11.567               NA                 NA
    20 2016-09-09        11.383               NA                 NA

**Comment by pgarnry** [comment]
Three things...

1) "BEST_EPS_YOY_GTH" and "BEST_SALES_YOY_GTH" are only available as current value which you can check through the FLDS function in the terminal (see bottom of description).

2) If "BEST..." fields are indeed available historically you should consider setting overrides in the future.

3) You can calculate EPS y/y growth by pulling the raw BEST_EPS and then calculate y/y changes on that series.

Good luck

**Comment by eddelbuettel** [comment]
Very nice answer, thanks @pgarnry 

I presume we can close this?

**Comment by pgarnry** [comment]
Thanks @eddelbuettel . Yes, I vote for closing this issue.
