### ISSUE TITLE
Invalid dates not handle properly by bdh() when downloading date fields

### ISSUE THREAD

**Issue by CharlesCara** [Rblp/Rblpapi#198]
Rblapi is really useful.  Thank you for creating it. 

However there is a problem with data that are Dates.  bdh does not handle invalid dates in the Bloomberg data.  (These used to be returned as strings, but now in v0.3.4 they are now returned as Date objects).  
My minimal example is:

```
> require(Rblpapi)
> blpConnect()
> bdh("HKUERATE Index","Eco_Release_Dt",as.Date("1996-01-01"),as.Date("2016-09-01"))
Error in eval(substitute(expr), envir, enclos) : 
  Day of month value is out of range 1..31
> bdh("TWLFADJ Index","Eco_Release_Dt",as.Date("1996-01-01"),as.Date("2016-09-01"))
Error in eval(substitute(expr), envir, enclos) : 
  Year is out of valid range: 1400..10000
> 
```

In my view the correct behaviour would be to return the dataframe with NA for the invalid date.

**Comment by armstrtw** [comment]
Why don't you ask bbg to fix the data?

          fieldData = {
                date = 1998-02-03
                Eco_Release_Dt = 0.000000
            }
...
...
            fieldData = {
                date = 1998-05-02
                Eco_Release_Dt = 0.000000
            }

**Comment by eddelbuettel** [comment]
> In my view the correct behaviour would be to return the dataframe with NA for the invalid date.

You could always do that at your end. _Our_ data transformations according _our_ coding standards, preferences and style all happens at the R level.  You could access the compiled routines yourself.

**Comment by CharlesCara** [comment]
Sorry if I have upset you with my suggestion.  I very much appreciate the work you guys have done creating this package.

Whit, Yes Bloomberg should fix the data, but I can only tell them about a piece of iffy data after my program has been affected by this.

Dirk, Unfortunately, no dataframe for this instrument/field is returned by bph, so I cannot handle the error in my code.   I am afraid skills in C++ are lacking, and the error is thrown in the compiled routine.  But looking through the code maybe the change should be that shown below (ie zero dates throw an handled exception).  If I understand it correctly then this would lead to that value being NA in the final dataframe.

blpapi_utils.cpp : line 81
` if(yyyymmdd_date <= 0) {`

I am happy to test this before making a pull request.  Could you point me in the direction of any documentation on how to build this package on Windows?

Thanks

**Comment by eddelbuettel** [comment]
Nobody is upset, but we are all busy professionals so answers are sometimes short.  What I had in mind was `bdh()` - the R function -- but I had not realized / forgotten than its case very little work is done there.
So I was wrong. It happens.  A lot actually :)

So yes, `bdh()` the R function calls `bdh_impl()` a C++ function using utility helpers.  We may indeed get by   via new optional flags which could indicate not to transform, or skip, or ...   I have been meaning to look into returning [`data.table`](https://github.com/Rdatatable/data.table/wiki) objects too.

Now: Windows. I won't have time to tutor you here.  It requires arguably more setup and elbow grease than the other platforms, but _it is doable_.  It takes effort.  There are dozens of tutorials out here.  Please try one or more.  Once you are able to build _a_ package from source with R (including compiled code; try maybe on of the smaller Rcpp-using packages like, sat, [RcppCCTZ](https://github.com/eddelbuettel/rcppcctz) come back here and just do `R CMD INSTALL .` in the source directory.   (RStudio also helps, a lot.)  Make sure you have `curl.exe` (see eg #196).

So how far you get.  By all means come back here with questions.

**Comment by armstrtw** [comment]
@CharlesCara you can drop in a link to the code like this:
https://github.com/Rblp/Rblpapi/blob/master/src/blpapi_utils.cpp#L81

**Comment by eddelbuettel** [comment]
Yep, even `L81-L85` works for highlighting a region, and markdown does of course have _links_. See the _Styling with Markdown is supported_ link at the bottom of the edit box.  And going into edit mode (and then canceling) of existing posts is a good way to see formatting tricks at the source.

**Comment by armstrtw** [comment]
so, the options here are to throw, which is the current behaviour, or to set the bad data as an NA, and possibly print a warning...

I'm somewhat inclined to go w/ the NA's since bbg data is notoriously crappy.

**Comment by CharlesCara** [comment]
Thanks, very much appreciated.  Charles

**Comment by eddelbuettel** [comment]
We could just pass a `bool` down to control that.  

It is of course a rat's nest. `NA` just for _values_ or also for _dates_ ?

**Comment by eddelbuettel** [comment]
@CharlesCara : By the way, I need more coffee.   I have been working on release date stuff too, and _you simply picked the wrong function_.  Doh.

```r
R> ovrd <- c("START_DT"="19960101", "END_DT"="20160901") 
R> dt <- bds("HKUERATE Index", "ECO_RELEASE_DT_LIST", overrides=ovrd)
R> head(dt)
  Ecostats Release Date
1              19970716
2              19970813
3              19970913
4              19971018
5              19971117
6              19971215
R> tail(dt)
    Ecostats Release Date
224              20160317
225              20160419
226              20160517
227              20160616
228              20160719
229              20160818
R> 
```

I am almost certain I learned that trick (of using `bds()` for _histories_ of these things, as opposed to `bdh()` which, as I recall, is for _histories of things you would use `bdp()` for_.  I wish I had a better rule.

**Comment by armstrtw** [comment]
Well, I was thinking more along the lines of just for dates.

NA's for numeric's are more of a normal condition.  and in the case of bbg, we drop them in when the datapiont is missing from the 'row' of the bbg response.  So, I don't think we need to deal w/ that case, but for a date column.

Also, dates in the index column of a bdh response are 'special' as bbg has already encoded them as a bbg date, so they should already be validated.  Dates appearing as 'double' or perhaps 'int' we should inspect and possibly just return NA if the data is bad.
