### ISSUE TITLE
subscribe( ) - finding Errors

### ISSUE THREAD

**Issue by gity84571** [Rblp/Rblpapi#201]
Hello.

Is there a way to trace the location of where exactly in parseResponse( ) I am generating an error?

I've tried the below but it doesn't provide any detail.

debug(subscribe(secs, flds, fun = parseResponse))
"Error: replacement has length zero"

Thank you for your time.

**Comment by armstrtw** [comment]
could you post an actual executable example here?

**Comment by gity84571** [comment]
I am sorry I don't think I can because there are many global variables and procedures which parseResponse makes use of and my employer wouldn't allow me to share so much code. I have no doubt the error is on my side, and I'm just trying to find out what is the process for debugging an - asynchronous? - method like this.

Usually my code works fine so I am accustomed to using subscribe( ) method.

**Comment by armstrtw** [comment]
so, just open an interactive session, run the subscribe, and drop a 'browse()' statement into the parser function...

Other than that, we can't really help you debug your parser.

> subscribe("USDJPY Curncy","BID",function(x) browser())
Called from: (function (x)
browser())(list(event.type = "SUBSCRIPTION_STATUS", topic = "USDJPY Curncy",
    data = list(exceptions = NULL)))
Browse[1]> names(x)
[1] "event.type" "topic"      "data"
Browse[1]>

**Comment by armstrtw** [comment]
unless there is an actual bug in the package, then you should close the issue... you can IB me if you can't figure it out on your own.

**Comment by gity84571** [comment]
thank you very much for your assistance.
