### ISSUE TITLE
bdh function to download EC_RELEASE_DT Error: Day of month value is out of range 1..31

### ISSUE THREAD

**Issue by rongli1101** [Rblp/Rblpapi#203]
The error is specifically with the ticker HARVSOYB Index and with the date 2004-10-08

`con<-Rblpapi::blpConnect();
Rblpapi::bdh(securities="HARVSOYB Index", 
             fields="ECO_RELEASE_DT", 
             start.date = as.Date("2004-10-02"), 
             end.date = as.Date('2004-10-08'), 
             include.non.trading.days = FALSE, 
             con=con)`

**Comment by eddelbuettel** [comment]
Try `PX_LAST`:

```r
R> bdh(securities="HARVSOYB Index", fields="PX_LAST", start.date = as.Date("2004-10-02"), 
+           end.date = as.Date('2004-10-08'), include.non.trading.days = FALSE)
        date PX_LAST
1 2004-10-08      58
R> 
```

**Comment by rongli1101** [comment]
If I change to it other fields it works. Even changing the start and end date will work. But the error is particularly with this ticker and this date. I have checked the data with Bloomberg, the day of month is absolutely within 1 to 31. So I suppose there is something wrong with the function.

**Comment by eddelbuettel** [comment]
No!  As we showed in other case, try `verbose=TRUE` and  you see that the returned value is bad:

```r
R> bdh(securities="HARVSOYB Index", fields="ECO_RELEASE_DT", start.date = as.Date("2004-10-02"), end.date = as.Date('2004-10-08'), include.non.trading.days = FALSE, verbose=TRUE)                                
HistoricalDataResponse = {
    securityData = {
        security = "HARVSOYB Index"
        eidData[] = {
        }
        sequenceNumber = 0
        fieldExceptions[] = {
        }
        fieldData[] = {
            fieldData = {
                date = 2004-10-08
                ECO_RELEASE_DT = 404236800.000000
            }
        }
    }
}
Error in eval(substitute(expr), envir, enclos) : 
  Day of month value is out of range 1..31
R>
```

Nothing we can here.  

Maybe show them this?   You are correct that _e.g_ moving dates by a week helps.
