### ISSUE TITLE
Can someone provide a sample code on how to get technical indicators data? historical and current? 

### ISSUE THREAD

**Issue by yongkangzhao** [Rblp/Rblpapi#204]
I'm having trouble getting technical indicator data they are called studies in Bloomberg, For example, Aroon Oscillator?

**Comment by armstrtw** [comment]
I suggest you work w/ the help desk to determine whether you can download that data into excel, and if so, then request those fields in the api.

**Comment by yongkangzhao** [comment]
ah~ I have contacted them and I was told that it is something they are working on, but not available right now.

From:  Whit Armstrong
Reply-To:  Rblp/Rblpapi
Date:  Monday, October 10, 2016 at 4:37 PM
To:  Rblp/Rblpapi
Cc:  Yongkang Zhao, Author
Subject:  Re: [Rblp/Rblpapi] Can someone provide a sample code on how to get technical indicators data? historical and current? (#204)


I suggest you work w/ the help desk to determine whether you can download that data into excel, and if so, then request those fields in the api.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Rblp/Rblpapi","title":"Rblp/Rblpapi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Rblp/Rblpapi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@armstrtw in #204: I suggest you work w/ the help desk to determine whether you can download that data into excel, and if so, then request those fields in the api."}],"action":{"name":"View Issue","url":"https://github.com/Rblp/Rblpapi/issues/204#issuecomment-252774014"}}}

**Comment by eddelbuettel** [comment]
Ok, thanks for reporting back. I will close this.
