### ISSUE TITLE
Error: Attempt to access value of element 'PX_VOLUME'(type: 'Float64') as 'Int32' type

### ISSUE THREAD

**Issue by jrehor** [Rblp/Rblpapi#207]
I believe this is related to https://github.com/Rblp/Rblpapi/issues/172 which has been fixed for 'VOLUME' but continues to fail with 'PX_VOLUME'.

The problem can be reproduced the same way in Rblpapi 0.3.5 on Windows:

```
opt <- c("periodicitySelection"="MONTHLY")
Rblpapi::bdh("SPY US Equity", c("PX_LAST", "PX_VOLUME"), start.date=Sys.Date()-31*6, options=opt)
```

**Comment by armstrtw** [comment]
is this set? in your options?
https://github.com/Rblp/Rblpapi/blob/master/R/bdh.R#L78

**Comment by eddelbuettel** [comment]
Please just use `VOLUME`. As you say, that works:

```
R> opt <- c("periodicitySelection"="MONTHLY")
R> bdh("SPY US Equity", c("PX_LAST", "PX_VOLUME"), start.date=Sys.Date()-31*6, options=opt)
Error in eval(substitute(expr), envir, enclos) : 
  Attempt to access value of element 'PX_VOLUME'(type: 'Float64') as 'Int32' type.
R> bdh("SPY US Equity", c("PX_LAST", "VOLUME"), start.date=Sys.Date()-31*6, options=opt)
        date PX_LAST     VOLUME
1 2016-06-30 209.475 2630619702
2 2016-07-29 217.120 1648381477
3 2016-08-31 217.380 1519703229
4 2016-09-30 216.300 2303701186
5 2016-10-31 212.550 1725687191
6 2016-11-30 220.380 2073824327
R> 
```

If you build from the current sources, you also get a new option:

```
R> opt <- c("periodicitySelection"="MONTHLY")
R> bdh("SPY US Equity", c("PX_LAST", "PX_VOLUME"), start.date=Sys.Date()-31*6, options=opt, int.as.double=TRUE)
        date PX_LAST  PX_VOLUME
1 2016-06-30 209.475 2630619702
2 2016-07-29 217.120 1648381477
3 2016-08-31 217.380 1519703229
4 2016-09-30 216.300 2303701186
5 2016-10-31 212.550 1725687191
6 2016-11-30 220.380 2073824327
R> 
```

**Comment by eddelbuettel** [comment]
@armstrtw That option is not in the CRAN version 0.3.5. And I don't think we put a new binary into the drat repository.

**Comment by jrehor** [comment]
Right. I'm going with VOLUME for now.

The 'int.as.double' option looks like a good solution.

**Comment by eddelbuettel** [comment]
Would an interim (Windows) binary for the current GitHub code base help?

**Comment by jrehor** [comment]
Wow, that would be wonderful. Thank you for considering it.

**Comment by eddelbuettel** [comment]
I just pushed it to [the ghrr drat](http://ghrr.github.io/drat/).  You should be able to get via

```r
install.packages("drat")       # easier repo access + creation
drat:::add("ghrr")             # make it known
install.packages("Rblpapi")    # install it
```

and that should get you 0.3.5.1 which is ahead of CRAN by that very `int.as.double` option.

**Comment by jrehor** [comment]
Thank you! I just confirmed that this solution works.
