### ISSUE TITLE
subscribe( ) processing volume in real-time

### ISSUE THREAD

**Issue by gity84571** [Rblp/Rblpapi#208]
I am making a real-time connection for several securities, and adding their volumes as they arrive to global variable accumulators (xts.today). I find that when I print the contents of those global variables (xts.today) in real-time the values are much less than when I stop the program and check the contents of the variable (xts.today). I suspect I am not processing the data the way I should be. I would appreciate any guidance. Thank you for your time.

Below is an html-formatted copy of the code:
[subscribe-volume.docx](https://github.com/Rblp/Rblpapi/files/669151/subscribe-volume.docx)

**Comment by eddelbuettel** [comment]
Sorry but we cannot offer a code review service here.

**Comment by gity84571** [comment]
I understand. I apologize. Thank you for your time.

**Comment by eddelbuettel** [comment]
One possibility:   reduce the problem to a 'pure' C++ problem.  That is product Bloomberg stands behind, so you can maybe use the support you pay for.

**Comment by gity84571** [comment]
I understand that is an option, but presumably there is a way to do this in R.  I understand I am a novice in R, but the below is what we see:

 df.today[ minute, security.prx ] <<- prx    # this works
 print (df.today[ minute, security.prx ])    # this indeed prints the last value of  prx for that minute

 df.today[ minute, security.vol ] <<-   df.today[ minute, security ]  + 1   # this does not increment 
 df.today[ minute, security.vol ] <<-    # this prints a value, say 14

when you stop the program and inspect df.today[ minute, security.vol ] you see a value much greater than 14

so, there appears to be no way to us to increment a global variable (to read it, change it, write it, and allow it to be changed again as more data comes in from Bloomberg. one can only write the data once.

so, the function seems to be designed to output the data, not to process it. 
 
and that's fine. we're just trying to understand if we're missing a possibility here or whether perhaps the documentation should make it more clear that doing the above is not possible within R

**Comment by eddelbuettel** [comment]
This is not the place to ask for R coding advice nor do we have the time to walk you through.

Consider maybe the r-sig-finance list.

**Comment by johnlaing** [comment]
Without spending a great deal of time examining your code, let me suggest that perhaps your problem is the use of the `<<-` operator. I find global assignment to be tricky, especially when coupled with `[` in the LHS.

Maybe better to put your accumulator object into an environment and assign to it there, which is the R way of achieving true reference semantics.

**Comment by gity84571** [comment]
Thank you for your patience and for making it clear the problem is not Subscribe( ) but rather my knowledge of R.  I will research. Thank you again for the lovely package and your time.
