### ISSUE TITLE
Trying to running bdh() function from RStudio, with receive error message

### ISSUE THREAD

**Issue by clivelamkk** [Rblp/Rblpapi#209]
I am trying to download historical data (Last Price, Volume) of a stock (3988 HK Equity) from Bloomberg with bdh() function.  I run my script under RStudio environment, with Rblpapi package installed.

Here is my code:
#----------------------------------------------------------------
  library(Rblpapi)
  
  tickers = "3988 HK Equity"
  fields  = c( "PX_LAST", "PX_VOLUME")
  begDate = "2000-01-01"
  endDate = "2016-12-27"
  
  the.BegDate <- as.Date(begDate)
  the.EndDate <- as.Date(endDate)
  
  conn <- blpConnect()
  histSpot <- bdh( tickers, fields, the.BegDate, the.EndDate )
#---------------------------------------------------------------- 

And I got this error message:

#----------------------------------------------------------------
Error in bdh_Impl(con, securities, fields, start.date, end.date, options,  : 
  Attempt to access value of element 'PX_VOLUME'(type: 'Float64') as 'Int32' type.
#----------------------------------------------------------------

Seems like there is some overflow inside the volume field, if they try to use Int32 to handle the volume traded of this stock.

I use RStudio and pre-compiled binary version of R and Rblpapi.  May I know if I can get around this problem?

I am running under Windows 10
RStudio version 1.0.136
R version 3.3.2, 64-bit
Rblpapi version 0.3.5

Thank you
Clive

**Comment by johnlaing** [comment]
Yes, there is an overflow, stemming from inconsistent type-handling on Bloomberg's side. Please try setting int.as.double=TRUE` in your `bdh` call, that should fix it. More details in #163 where we hashed out the exact problem and its eventual solution.

**Comment by eddelbuettel** [comment]
@clivelamkk :  For better bug reports also consider

- formatting your questions, as this explained in the link title [Styling with Markdown is supported](https://guides.github.com/features/mastering-markdown/) which you see below _each_ edit box
- omit irrelevant information; this issue has nothing to do with RStudio
