### ISSUE TITLE
BDH/BDP Override Support

### ISSUE THREAD

**Issue by kylebalkissoon** [Rblp/Rblpapi#21]
In rbbg land, BDH/BDP support overrides AND options, I currently see only options supported in the code. How do I pass an override in to bdh/bdp?

Also when using nonTradingDayFillMethod "PREVIOUS_VALUE" should also be an option (as international portfolios may have securities with non synchronous dates).

**Comment by eddelbuettel** [comment]
Can you whip up a pull request?

**Comment by armstrtw** [comment]
I'm pretty sure JL was going to take care of this.

**Comment by johnlaing** [comment]
Yes, I had started some work on this last week. It's a straightforward add, I think I can finish it up tomorrow morning.

**Comment by johnlaing** [comment]
PR #23 adds overrides. For nonTradingDayFillMethod, you can set that option explicitly.

**Comment by forkandspoon** [comment]
Is it possible to add overrides to getTicks? Specifically looking at obtaining the condition codes (condcodes=s) to obtain the indicative bid/ask

**Comment by kylebalkissoon** [comment]
Fork and spoon plz make a diff issue.
I forgot to close this one.
