### ISSUE TITLE
GetMultipleTicks vs GetTicks with returnas = "xts" yield different classes of index (POSIXlt vs POSIXct)

### ISSUE THREAD

**Issue by FaGuoMa** [Rblp/Rblpapi#211]
Took us some time to figure what was happening, but essentially strftime ignores the "tz" parameter for getMultipleTicks (returned as xts) because the underlying index datetime class is POSIXlt. 
GetTicks with returnas = "xts" yields index in POSIXct which nicely play any tz from Olsonvalue()

Not a huge deal, of course, but RBLpapi is awesome and I'm not sure how I can contribute

**Comment by eddelbuettel** [comment]
Do you have a quick reproducible example?  I'd be surprised if we created `POSIXlt`, it should always be `POSIXct`.

**Comment by FaGuoMa** [comment]
Yeah, that's why it took us so long to figure it out. No idea how that would come about (but maybe I'll look at the codebase if I get the chance today). We're running version 0.3.2

`singletick <- getTicks("CLA Comdty", eventType = "TRADE", startTime = Sys.time()-60*5, returnAs = "xts")
class(zoo::index(singletick))`

>"POSIXct" "POSIXt"
and

`multick <- getMultipleTicks("CLA Comdty",startTime = Sys.time()-60*5, returnAs = "xts")
class(multick)`

> "POSIXlt" "POSIXt"

**Comment by eddelbuettel** [comment]
Well, 0.3.2 is comparatively ancient.  When I execute your code I get

```
R> singletick <- getTicks("CLA Comdty", eventType = "TRADE", startTime = Sys.time()-60*5, returnAs = "xts")
R> class(index(singletick))
[1] "POSIXct" "POSIXt" 
R> 
```

No surprise here. Request a `xts`, get `POSIXct` as the index.

Next:

```
R> multick <- getMultipleTicks("CLA Comdty",startTime = Sys.time()-60*5, returnAs = "xts")
Error in match.arg(returnAs, c("data.frame", "data.table")) : 
  'arg' should be one of “data.frame”, “data.table”
R> 
```

So it appears you are using an older and outdated version with what may be an already fixed bug.  Maybe do yourself a favour and get current.

I plan to close this as I see no bug here.

**Comment by FaGuoMa** [comment]
So, I've upgraded and you can probably close the issue but why is the xts version removed from the returnas = ???
Any particular reason? Do you want me to give a crack at adding the option on getMultipleTicks ?

**Comment by eddelbuettel** [comment]
There was a clear logic error / thinko making it not so useful.  `xts` only allows for _numerical_ return data, we dropped some textual columns meaning that you could have queries with returned data where some events where accounted for multiple times.  This function really wants something like `data.table` which can index via POSIXct _and_ other (non-numeric) data.
