### ISSUE TITLE
BDP - data frame columns not identical to fields in input

### ISSUE THREAD

**Issue by Carcajou01** [Rblp/Rblpapi#212]
Hello,

I'm using BDP to request information about several fields and several Isins.

I have noticed that if all my requested securities have no data for a specific field then the data frame in return will not have a column associated with this field.
However in the documentation it is mentionned : "A data frame with as a many rows as entries in
securities and columns as entries in fields".

In my opinion a Na column would be better than no column at all oterwise it makes you returned data frame size "random".

Many thanks for this package,
Regards

**Comment by armstrtw** [comment]
can you post your actual call to bdp?

**Comment by Carcajou01** [comment]
Hello,

thanks for your answer and sorry for the delay of mine.

Here is an example :
bdp(c("/isin/IT0004780802","/isin/IT0004780810","/isin/IT0004781503"),c("CRNCY","FLOATER_SPREAD_STEPPED","ID_ISIN","MTG_DEAL_CALL_DT"),overrides="2", con=bbgConn)

As an output and following the documentation, the output should be a 3x4 dataframe. However I only obtain a 3x2 dataframe. The 2nd and 4th fields are NULL.

**Comment by johnlaing** [comment]
Your call does not work as written. The `overrides` argument must be a named vector, where you provide only a character.

Dropping out the `overrides`, this behaves as expected for me:
```
> x <- bdp(c("/isin/IT0004780802","/isin/IT0004780810","/isin/IT0004781503"),c("CRNCY","FLOATER_SPREAD_STEPPED","ID_ISIN","MTG_DEAL_CALL_DT"))
> dim(x)
[1] 3 4
> colnames(x)
[1] "CRNCY"                  "FLOATER_SPREAD_STEPPED" "ID_ISIN"                "MTG_DEAL_CALL_DT"      
```

**Comment by eddelbuettel** [comment]
Suggest to close this.

**Comment by johnlaing** [comment]
Agree, I'll close.

@Carcajou01 - please check the exact call you're making to `bdp`. Also please check which version of `Rblpapi` you're using. If you can demonstrate bad behavior on a current version, please re-open.

**Comment by Carcajou01** [comment]
Hello,

Sorry if it reopen the issue but one way to correct it is to download the 3.5 blpapi version. I was using 3.2.

Many thanks for your time
