### ISSUE TITLE
I want to know what the numEvents mean in the gerBars function

### ISSUE THREAD

**Issue by tapsan80** [Rblp/Rblpapi#213]

**Comment by eddelbuettel** [comment]
That is a question for Bloomberg help.  You pay for the service.

**Comment by eddelbuettel** [comment]
But in a minimal nutshell, it's just what you think would be: for a _bar_ constructed of _trade events_ it counts the number of events _summarized by the bar_.  Or so it seems.  Buyer beware.  And you should still make use of the (generally excellent) help support you get for paying those top dollars to Bloomberg.
