### ISSUE TITLE
Updating to 0.3.6 issue

### ISSUE THREAD

**Issue by mcastagnaa** [Rblp/Rblpapi#224]
I am stuck here while trying to update from 0.3.5.

```
* installing *source* package 'Rblpapi' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************
** libs
*** arch - i386
curl: not found
mv: cannot stat 'blpHeaders.tar.gz': No such file or directory
tar (child): ../blp/win/i386/blpHeaders.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Exiting with failure status due to previous errors
```

Is there anything I could do to get past this? I understand my trouble is with the headers file. I can download this independently but then I would need to modify the configure script, which I am not sure how to do.
Thanks.

**Comment by eddelbuettel** [comment]
It worked for all our tests, including in both win-builder and the R Hub windows builder.   So I suspect something local at your end.

Worst case you can either do the few steps of the helper script by hand, or wait til CRAN builds it for you.

Also, for the next day or so, [this link](https://win-builder.r-project.org/1C8HY68FOi0v/) will have the win-builder result. You can just fetch that zip file and install it locally.

**Comment by eddelbuettel** [comment]
And the binary for Windows is now there, with just a little delay to wait for R 3.4.0.

Your issue could just have some networking voodoo between you and GitHub. It happens.

**Comment by mcastagnaa** [comment]
Believe me when I say that being behind a corporate firewall is really painful!
