### ISSUE TITLE
getTicker Function and older data

### ISSUE THREAD

**Issue by FilipeCoutinhoPereira1** [Rblp/Rblpapi#225]
Hello, 

Firstly I would like to thank you for this amazing API! I imagine the time you'd put to accomplish it and for that I'm really grateful. 

Now, I would just like to ask you a question. I am getting a void response (just the headers, but not data) for this getTicks function call down below. StartTime and EndTime should be an arbitrary date by Dec 2005 (by today's calendar May 8th 2017). Is getTicks function capable to retrieve older tick data like this or I am getting something strong in the middle of the way?

Thank you

----------CODE-------------
getTicks(as.character("USDEUR Curncy", 
                       eventType = "ASK", 
                       startTime = Sys.time() - 60 * 6000000,
                       endTime = Sys.time() - 60 * 5994000, 
                       verbose = FALSE, 
                       returnAs = getOption("blpType","data.frame"), 
                       tz = Sys.getenv("TZ", unset = "America/Sao_Paulo"),
                       con = defaultConnection())

**Comment by eddelbuettel** [comment]
It's documented _somewhere_ or I think someone answered on r-sig-finance recently.  You get something like 60 or 80 _days_ worth of history.

**Comment by armstrtw** [comment]
I don't think they will let you pull that far back in time.  try current dates.  not a bug in the api.

**Comment by wmorgan85** [comment]
There is a limit of 140 days of intraday data through the API, regardless
of the interface used.

**Comment by eddelbuettel** [comment]
I am adding this to the documentation now,.

**Comment by joel23888** [comment]
A couple of other things I have noticed which may be helpful:
* "140 days" seems to mean calendar days including weekends/holidays (as opposed to 140 trading days' worth of information). Correct me if I am wrong on this @wmorgan85 .
* I have found there is often a bit more than 140 days' worth available, so it is worth experimenting with date ranges. Obviously this is to be done at one's own risk.
