### ISSUE TITLE
bfx bfxcurve bfxswap and bfxforward functions

### ISSUE THREAD

**Issue by FGaier** [Rblp/Rblpapi#227]
Hi there, 

do you plan on developing functions that can run these newer bloomberg functions via R ?

bfx bfxcurve bfxswap and bfxforward functions

kind regards

**Comment by armstrtw** [comment]
pls drop a link to the documentation of these for the c++ api.

**Comment by FGaier** [comment]
Right, so this is the reply i got from bloomberg. Sorry for wasting your time.

Unfortunately this is not currently available, but there is a request in with our programmers to enable this in the future. I have linked your interest to that programming request, such that if/when it becomes possible we can reach out via MSG <GO> to let you know.
I do not have a timeline on development, but our engineering team is actively monitoring client demand, and as soon as we have any additional information we will reach out to you.

**Comment by armstrtw** [comment]
haha, good luck with that.  I even suggested to the AIM devs that they use jira, and allow clients to comment on issues, but obviously that's totally crazy when they can build a bbg screen to do that... HDSK, totally the same thing, right?

**Comment by armstrtw** [comment]
feel free to re-open when you get that msg from them. I'm not gonna hold my breath.

**Comment by FGaier** [comment]
Yeah – understood. Thx for coming back so quick
