### ISSUE TITLE
Rblapi crashing when running from command line

### ISSUE THREAD

**Issue by aleave** [Rblp/Rblpapi#228]
I have a bloomberg terminal and can use Rblapi with no problem from within Rstudio. However when I try to run it from the command line through Rscript or R.exe loading the library with
`library(Rblapi)`
causes the script to crash with no specific error message.

The R version I am using is the same for Rstudio and command line R (3.3.2)

**Comment by armstrtw** [comment]
you haven't really given us any information, other than to indicate you're running R on windows (only by referencing R.exe).

Do you know how to start R w/ a debugger?  then at least you can see the coredump.

**Comment by eddelbuettel** [comment]
Almost surely your local problem as we (and a bazillion other people) have a gazillion scheduled jobs doing just that day in and day out.

Your report is also not exactly reproducible.  Trim the script.  Show it.

**Comment by aleave** [comment]
here's the script, trimmed:
`library(Rblapi)`

this single line causes the script to crash

**Comment by eddelbuettel** [comment]
Just rebuild. Almost surely a mismatch between your version of R, your version of Rcpp and your version of Rblpapi.  It can happen.

It does not happen to any of us, mind you.

**Comment by armstrtw** [comment]
why don't you try on another machine.

or the debugger, as I suggested.

**Comment by aleave** [comment]
I'll try, good to know it is only a local issue. thanks

**Comment by aleave** [comment]
OK, the oldest trick in the IT world of restarting the machine made this work. Thanks for your help and apologies for the procured alarm.

**Comment by eddelbuettel** [comment]
Trust us, we've all been there.  

And on Windoze, you do need to sacrifice the occasional goat or first born.  It's what we all do.
