### ISSUE TITLE
BDH Days and Fill Options

### ISSUE THREAD

**Issue by Research100** [Rblp/Rblpapi#229]
Hi,
Does anyone know how to use the Days and Fill Options in R Rblpapi? I can write it in Excel like below, but cannot translate that to R:

=BDH("IBM US Equity","PX_LAST","1/1/2016",TODAY(),"days=a","fill=p")

**Comment by armstrtw** [comment]
?bdh

**Comment by Research100** [comment]
BDH is Bloomberg API's Historical Data request command.

**Comment by joel23888** [comment]
I think the point is, if you have a question about any function in R then try R's help as your starting point. If you just run `?bdh` from R then you will see your exact question is answered in the Examples.

**Comment by eddelbuettel** [comment]
And if and when something is missing in the docs, or examples, we will add it. 

But this question is likely answered here, and OP appears to have given zero effort to finding out how the R package works. Just coming over and declaring "this worked in Excel" does not cut it.  If Excel works for you, by all means keep using Excel.   If on the other hand you are interested in using (and, deity forbid, even improving) the R side, then by all means invest some time and learn about it.

**Comment by Research100** [comment]
Thank you! I found out how it is done.
