### ISSUE TITLE
Request Failed

### ISSUE THREAD

**Issue by OuHui** [Rblp/Rblpapi#231]
I just want to get When issued data for June 2017 by using following code,

wit <- getBars(security = "9999T03Y", 
                 eventType = "TRADE", barInterval = 1, 
                 startTime = as.POSIXct(as.character(dat$ANNC_DATE[j]), format = "%m/%d/%Y %H:%M"),
                 endTime = as.POSIXct(as.character(dat$SETT_DATE[j]), format = "%m/%d/%Y %H:%M"),
                 options = NULL, verbose = FALSE,
                 returnAs = getOption("blpType", "matrix"),
                 tz = Sys.getenv("TZ", unset = "EST"),
                 #eastern standard time
                 con = defaultConnection())

It works fine June 24th and 25th, but happened to have request failure. I am sure there are enough data on Bloomberg. Anyone have some idea?

**Comment by armstrtw** [comment]
Check if your date range crosses the settlement date of the wi3, then run the same request with the actual cusip, and see if it fails.

**Comment by OuHui** [comment]
Still have same error. It works for 2yr, 5yr and 7yr.

**Comment by joel23888** [comment]
Can you provide a reproducible example and set `verbose=TRUE`?

**Comment by OuHui** [comment]
library(Rblpapi)
blpConnect(host = getOption("blpHost", "127.0.0.1"),
           port = getOption("blpPort", 8194L),
           default = TRUE)

wit <- getBars(security = "9999T03Y",
               eventType = "TRADE", barInterval = 10,
               startTime = as.POSIXct("06/08/2017 12:00 AM", format = "%m/%d/%Y %H:%M"),
               endTime = as.POSIXct("06/12/2017 4:00 PM", format = "%m/%d/%Y %H:%M"),
               option = NULL, verbose = TRUE,
               returnAs = getOption("blpType", "matrix"),
               tz = Sys.getenv("tz", unset = "EST"),
               con = defaultConnection())
-------------------------------------------------------------------------------------------------------------------
Hi, joel23888. This is the code. It is not working since this Monday, but it works fine last weekend.
Thank you for your help. And the errors are as below.
-------------------------------------------------------------------------------------------------------------------
REQUEST FAILED: responseError = { source = "bbdbl7" code = 15 category = "BAD_SEC" message = "Unknown/Invalid security [nid:3882] " subcategory = "INVALID_SECURITY" }

**Comment by johnlaing** [comment]
This is a Bloomberg issue/quirk. Any calls to that instrument fail similarly:
```
> bdp("9999T03Y", "PX_LAST", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "9999T03Y"
            eidData[] = {
            }
            securityError = {
                source = "3698::bbdbd23"
                code = 15
                category = "BAD_SEC"
                message = "Unknown/Invalid security [nid:3698] "
                subcategory = "INVALID_SECURITY"
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
            }
        }
    }
}
         PX_LAST
9999T03Y      NA
> bdp("9999T03Y", "PX_LAST", verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "9999T03Y"
            eidData[] = {
            }
            securityError = {
                source = "3698::bbdbd23"
                code = 15
                category = "BAD_SEC"
                message = "Unknown/Invalid security [nid:3698] "
                subcategory = "INVALID_SECURITY"
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
            }
        }
    }
}
         PX_LAST
9999T03Y      NA
```

It seems like they've deactivated the WIT3 instrument and presumably will reinstate it before the next auction.

The historical data does seem to be preserved, since you can see it with `GIP<GO>` in the terminal. Maybe it's possible to access via API with some alternative ticker or options, but I don't know. That would be a question for Bloomberg.

I'll close this for now, but feel free to report back if you have any success talking to Bloomberg about how to make this work.
