### ISSUE TITLE
getRunTimeVersion and getHeaderVersion Broken

### ISSUE THREAD

**Issue by eunosm3** [Rblp/Rblpapi#233]
I tried the two functions referenced above today, but received 

> Error in get----() : could not find function "get----"

System: Win7; R 3.4.0; RblpApi 0.3.6;

**Comment by eddelbuettel** [comment]
I am not sure I follow.

We have hundreds of users of Windows.  It works for them.  It works for us too.  Sure your error is not due to some change at your end?

**Comment by eunosm3** [comment]
I tried again, several times, including restarting R, starting R w/ Rgui instead from within SublimeText3, uninstalling and then reinstalling the package and after completely re-booting.  Still, those two functions throw an error even though the other functions seem to work fine.  

In this case, the package is installed on a corporate computer w/ security restrictions, etc.  Before last week I had not tried either function because I did not have any reason to use them.  

```
> blpConnect()
> bdp("MSFT Equity", "px_last")
            px_last 
MSFT Equity   69.46
> getRuntimeVersion()
Error in getRuntimeVersion() : 
  could not find function "getRuntimeVersion"
> getHeaderVersion()
Error in getHeaderVersion() : could not find function "getHeaderVersion"
```

**Comment by eddelbuettel** [comment]
I think this may be your local problem --- maybe an old version is shadowing a new newer version.

```r
R> packageVersion("Rblpapi")
[1] ‘0.3.6’
R> Rblpapi:::getRuntimeVersion()
[1] "3.8.18.1"
R> Rblpapi:::getHeaderVersion()
[1] "3.8.18.1"
R> 
```

All works here as it should.  I think I lean towards closing this.

**Comment by eunosm3** [comment]
Sounds like a fine idea to me.  If it crops up again somewhere, at least a reference point exists.
