### ISSUE TITLE
bds() is limited to roughly 20 columns

### ISSUE THREAD

**Issue by joeltrinnacle** [Rblp/Rblpapi#234]
using the following function
bds(as.character("AAPL US EQUITY"),c("PG_REVENUE"),overrides=c("FUND_PER"="Q","NUMBER_OF_PERIODS"="-5"))
yields as expected 5 historic quarters. However
bds(as.character("AAPL US EQUITY"),c("PG_REVENUE"),overrides=c("FUND_PER"="Q","NUMBER_OF_PERIODS"="-40"))
does not yield 40 results

It seems the function is limited to 20 columns
Does anyone have an idea how to best solve this? Many thanks

**Comment by eddelbuettel** [comment]
When I use `verbose=TRUE` I clearly see only 16 periods being returned by Bloomberg.

So methinks you have to take that up with _them_ rather than with us.

**Comment by joel23888** [comment]
Indeed the `FLDS` description in the BBG terminal states that number of periods can be in [-16,16].

**Comment by eddelbuettel** [comment]
Thanks for the follow-up and confirmation.  Ok to close this then, I presume.
