### ISSUE TITLE
package ‘blpConnect’ is not available (for R version 3.4.1)

### ISSUE THREAD

**Issue by augustohassel** [Rblp/Rblpapi#236]
When trying to install this package I get the following message: 

package ‘blpConnect’ is not available (for R version 3.4.1)

**Comment by eddelbuettel** [comment]
That is correct as the package is called [Rblapi](https://cran.r-project.org/package=Rblpapi)  which does exist and install.   Have yourself another cup of coffee and try that, it has a _function_ call `blpConnect`.

**Comment by augustohassel** [comment]
I fell like a.. my bad! Tks

**Comment by eddelbuettel** [comment]
No worries.  We have all been there.
