### ISSUE TITLE
BDS fails on server api

### ISSUE THREAD

**Issue by boofhead** [Rblp/Rblpapi#237]
I am having issues using the server api with BDS calls which work fine using the desktop api.

For example the following works fine using a local connection to the desktop api but fails when hitting the server. I have no problems with bdh / bdp calls to the server so I know it's working.

`bds("KFW Corp", "BOND_CHAIN", overrides = c(CHAIN_COUPON_TYPE = "Fixed", 
                                                                            CHAIN_MATURITY_TYPE = "Bullet", 
                                                                                     CHAIN_CURRENCY = "EUR"))`

error message is 

`Error in bds_Impl(con, security, field, options, overrides, verbose, identity) : 
  Choice sub-element not found for name 'securityData'.`

As I said server works fine with other calls so I don't believe it is an over data limit issue.

**Comment by eddelbuettel** [comment]
I am not sure if any one of us have access to the server backend.  My experience is only via the desktop.

**Comment by joel23888** [comment]
@boofhead I still think you should check with your IT staff to make sure it is not related to  authentication/authorization/permissioning. You never know, there might be a setting they can change to open up this specific request for you. Quoting from the BLPAPI developer guide:

> All API products share the same programming interface and behave almost identically. The main difference is that customer applications using the enterprise API products (which exclude the Desktop API) have some additional responsibilities, such as performing authentication, authorization and permissioning before distributing/receiving data.  

Ref: https://data.bloomberglp.com/professional/sites/10/2017/03/BLPAPI-Core-Developer-Guide.pdf (section 1.1)

**Comment by boofhead** [comment]
Probably you are correct. I am investigating but for what it's worth here is the server response. In any case not an Rblpapi issue so will close here.

 `ReferenceDataResponse = {
    responseError = {
        source = "bbdbd48"
        code = 9
        category = "BAD_ARGS"
        message = "override is not allowed for field: CHAIN_COUPON_TYPE [nid:931] "
    }
}`

**Comment by joel23888** [comment]
I am guessing here but in case it might help you, have you tried upper-case override values? I noticed in the BBG terminal they are displayed this way.
```
bds("KFW Corp", "BOND_CHAIN", overrides = c(CHAIN_COUPON_TYPE = "FIXED", CHAIN_MATURITY_TYPE = "BULLET", CHAIN_CURRENCY = "EUR"))
```

Also note that according to `FLDS` that `BOND_CHAIN` and its associated fields will be "deprecated soon". There is only a reference there to an Excel function, so if you depend on this then it might be worthwhile to see how to get this data using the C++ API. Then you could possibly implement this in `Rblpapi`. Just looking at the developers guide, it seems the Market List Service (section 5.9) is a good place to start investigating.
