### ISSUE TITLE
Pre-Open IntraDay BID ASK Data

### ISSUE THREAD

**Issue by Research100** [Rblp/Rblpapi#239]
Hi,
I am trying to get some pre-open data using getBar or getTicks and the data starts and ends with trading hours. I am not able to get data prior to or after market hours. Is there an option that I can use to allow for those values to come in?

  bar_data = getBars(t, eventType = "BID", barInterval = 1,
        startTime = start_date , endTime = Sys.time(),
        options = c(UseDPDF="N",CshAdjAbnormal="N",CshAdjNormal="N",CapChg="N"), verbose = FALSE, returnAs = getOption("blpType", "matrix"), tz = Sys.getenv("TZ", unset = "America/New_York"))

**Comment by eddelbuettel** [comment]
Please ask Bloomberg Help about data _content_ questions.

**Comment by Research100** [comment]
Understood. Thank you!
