### ISSUE TITLE
Accessing Custom Data via Rblpapi

### ISSUE THREAD

**Issue by brandoncfarr** [Rblp/Rblpapi#241]
I'm trying to extract Bloomberg data from Custom Data fields that I have set up in Bloomberg (see CDE \<GO\>). I have created a custom data field with the name "UD_BBTEST01" in Bloomberg. I can access the data in Excel via a formula "=BDP("AAPL US Equity","UD_BBTEST01"). However the request in R returns the following:

```
R > bdp("AAPL US Equity", "UD_BBTEST01", verbose=TRUE)
Error in bdp_Impl(con, securities, fields, options, overrides, verbose,  : 
  Bad field: UD_BBTEST01
```

Requests on standard Bloomberg fields work as expected:

```
R > bdp("AAPL US Equity","Name")
                    Name
AAPL US Equity APPLE INC
```

Speaking with my Bloomberg Rep and the help desk indicates that the data should be accessible via API. I am posting here see if anyone knows whether it is currently possible to extract custom data via Rblpapi. I am using Rblpapi version 0.3.5 in R 3.3.3.

Thank you.

**Comment by armstrtw** [comment]
does your custom field work in excel?

**Comment by eddelbuettel** [comment]
That's pretty much between you (for the query) and Bloomberg (for answering it).   We don't filter or modulate, we just happen to provide some R access points using the C++ API provided by Bloomberg.

In other words, we're just the messenger here, and we don't anything about `UB_BBTEST01` either.

**Comment by eddelbuettel** [comment]
You may also be logged into Excel with different credentials than via Rblpapi, have other default settings etc pp.  Hard for us to tell.

**Comment by brandoncfarr** [comment]
The custom field does work in Excel. I received the following advice from Bloomberg

> Currently Bloomberg doesnt support the R binding to our desktop API but there are open source versions available. The one thats the most popular is RBLPAPI. He can find the User Guide for it here - https://cran.r-project.org/web/packages/Rblpapi/Rblpapi.pdf and the github link here - https://github.com/Rblp/Rblpapi. He might already be familiar with this piece.

> I've also attached a pdf that shows how to get cde data through excel formulas. Each of those excel formulas should map to a R API and the inputs should be similar. Between the that library and this document technically he should be able to get CDE data into R.
Hope this helps.

The "Bad field" field error message appears to only show up when misspelling a field name or entering a valid CDE field name. I was under the impression that Rblpapi was just a wrapper to the C++ API, and didn't think the problem lay with Rblpapi.

Thanks for the clarification. I'm hoping someone out there has worked through this, as I've not made much progress with Bloomberg help desk.

**Comment by joel23888** [comment]
`bdp` returns because BBG is not returning custom field information to `getFieldTypes` in `bdp_Impl`. Running `bdp` with `verbose=T` shows it does not even send the data request. The same error is returned when using `fieldInfo` which already relies on `getFieldTypes`:
```
> bdp("7203 JT Equity", "UD_TEST2", verbose=T)
Error in bdp_Impl(con, securities, fields, options, overrides, verbose,  : 
  Bad field: UD_TEST2
> fieldInfo("UD_TEST2")
Error in fieldInfo_Impl(con, fields) : Bad field: UD_TEST2
```


Note: `UD_TEST2` is a custom field I made in `CDE` and it works in Excel with `BDP`.



`bds` on the other hand does not use `getFieldTypes`, so it sends the data request but has trouble processing the response. This seems similar to https://github.com/Rblp/Rblpapi/issues/184?

```
> bds("7203 JT Equity", "UD_TEST2", verbose=T)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "7203 JT Equity"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                UD_TEST2 = 4.000000
            }
        }
    }
}
Error in bds_Impl(con, security, field, options, overrides, verbose, identity) : 
  Attempt to access value of element 'UD_TEST2'(type: 'Float64') as 'Element' type.
```

The suggestion would be for OP to speak with BBG about getting custom field information to be provided via the C++ API and use `bdp`.

**Comment by brandoncfarr** [comment]
joel23888,

Thanks for shedding further light on this. I will speak with Bloomberg today and post any response here.

**Comment by brandoncfarr** [comment]
joel23888,

Your research helped direct my inquiry with Bloomberg. `bds` is indeed the way to go, though is admittedly a bit of a workaround.

```
bdc <- function(sec, ud_field, start_dt = NULL, end_dt = NULL) {
  
  if(is.null(start_dt)) start_dt = "20161231"
  if(is.null(end_dt)) end_dt = format(Sys.Date(), format = "%Y%m%d")
  
  ovrd <- c(
    "CUSTOM_USER_DATA_FLD_ID_OVERRIDE" = ud_field,
    "CUSTOM_USER_DATA_START_DT_OVRD" = start_dt,
    "CUSTOM_USER_DATA_END_DT_OVERRIDE" = end_dt
  )
  
  bds(sec, "CUSTOM_USER_DATA_BULK_FIELD", overrides = ovrd)
  
}

R > bdc("MSFT US Equity", "UD_BBTEST01")
        Date      Notes
1 2017-09-27 350.000000
```

The above simplified example works.

I pointed my Bloomberg contact to this github issue and got the following response.

> Just read the thread. cde fields are not included as part of the field information service since they are different for every user where as the field info is generic. Hence that explanation makes sense. I'm not sure if they can drop the requirement to verify the field before pushing the request through.

As to why it was working in Excel:

> In Excel we have logic to double check the field against the field list and seperately with the users cde list before firing off the request.

Thanks again for helping get this resolved.
