### ISSUE TITLE
Change from character to date

### ISSUE THREAD

**Issue by Claire-Kimbugwe** [Rblp/Rblpapi#242]
Hi 
Guys I've been trying to change dates given in character form to a date , but i keep getting the wrong answers or an error.
this is the structure of my data
Classes ‘data.table’ and 'data.frame':	2880 obs. of  9 variables:
 $ Date                 : chr  "1/2/2007" "1/2/2007" "1/2/2007" "1/2/2007" ...
 $ Time                 : chr  "00:00:00" "00:01:00" "00:02:00" "00:03:00" ...
 $ Global_active_power  : num  0.326 0.326 0.324 0.324 0.322 0.32 0.32 0.32 0.32 0.236 ...
 
Below is what ive tried so far
Trial$Date <- as.Date(Trial$Date, "%d/%m/Y") #this gives me NAs
Trial$Date <- as.Date.character(Trial$Date, "%d/%m/Y") #this gives me an error(Error in format.default(x, ...) : invalid 'trim' argument)
please advice. Thanks

**Comment by eddelbuettel** [comment]
This is
- the wrong place for basic R questions, try maybe StackOverflow
- has nothing to do with with Rblpapi

You may want to look at my [anytime](http://dirk.eddelbuettel.com/code/anytime.html) package. You can convert to POSIXct (via `anytime()`) by, say, paste-ing your `Date` and `Time` columns, or to Date (via `anydate()`).  It is very tolerant of input type and format.  I use it a lot with `data.table` too.
