### ISSUE TITLE
Windows location for external DLLs

### ISSUE THREAD

**Issue by spennihana** [Rblp/Rblpapi#243]
Related to #40,  R CMD check warns with:

```
* checking package subdirectories ... WARNING
Found the following non-empty subdirectories of 'inst' also used by R:
inst/libs
It is recommended not to interfere with package subdirectories used by
R.
```

Is there a canonical place to put external DLLs? I may need to reread the relevant sections of Writing R Extensions, but I figured I'd ask here, too.

**Comment by eddelbuettel** [comment]
I think you may be overlooking the fact that this gets cleaned away.  The source repo has no `inst/libs`.

What is you real question?  And what about it do the zip files on CRAN not answer?

```sh
/tmp$ unzip -l Rblpapi_0.3.6.zip | grep dll         ## for a dll just wget'ed from CRAN
  3338200  2017-10-01 19:24   Rblpapi/libs/i386/blpapi3_32.dll
  1168398  2017-10-01 19:24   Rblpapi/libs/i386/Rblpapi.dll
  4676568  2017-10-01 19:26   Rblpapi/libs/x64/blpapi3_64.dll
  1081856  2017-10-01 19:26   Rblpapi/libs/x64/Rblpapi.dll
/tmp$
```

**Comment by spennihana** [comment]
Thanks, Dirk. My mistake for not realizing Rblpapi is a binary package. Using Rblpapi as a reference, I am puzzling my way through understanding how to link everything properly in my own package and get a pass from R CMD check.

Apologies for abusing the Rblpapi issues for the more general question--but resources on more complicated windows builds are scarce!

**Comment by eddelbuettel** [comment]
It's a complicated package as it (on Windows) pulls in a prebuilt set of dlls, and similar on other platforms.

Your best bets are the _Writing R Extensions_ manual, the r-package-devel list and packages like this.  But please ask follow-ups on the list.  I read it too.
