### ISSUE TITLE
Using Sedol as identifiers

### ISSUE THREAD

**Issue by 108toy** [Rblp/Rblpapi#247]
It is not really an error. But would like to do, for example, the following: 

=BDP("BMMV2K8 SEDOL1","px_last")

**Comment by eddelbuettel** [comment]
Briefly:
- Please do use the courtesy and format your question
- If you want to use our R package, show the R usage you tried. We are not an Excel translation service
- This is an API question so ask Bloomberg, our package does not modify what you submit. If it failed, your query wasn't right

**Comment by 108toy** [comment]
thanks.

**Comment by johnlaing** [comment]
SEDOL identifiers _do_ work, but the API requires you to provide proper yellow key:
```R
bdp("BMMV2K8 Equity", "PX_LAST")
#                PX_LAST
# BMMV2K8 Equity   391.8
```

It is a mystery why the yellow-key is required in the API but a generic SEDOL works in Excel. This is one of many examples of "magic" performed in Excel that is not exposed and/or documented in the underlying API. I wish it were not so, and we have complained to Bloomberg about this many times over many years, but no real progress API/Excel convergence.
