### ISSUE TITLE
Multiple overrides for bond yield calc

### ISSUE THREAD

**Issue by auenbauer** [Rblp/Rblpapi#248]
Hi, I am using this code and it works to cal yields: 

Code:
ID <- c("EI463143 Corp", "EK600823 Corp", "EI724801 Corp")
overrd <- c("PX_DISC_BID"="100")
yld_flds <- c("YLD_YTM_BID", "YLD_CNV_BID")
bdp(securities =  ID, fields = as.vector(yld_flds), overrides = overrd, verbose = FALSE)

Outcome: 
              YLD_YTM_BID YLD_CNV_BID
EI463143 Corp    7.991256    7.991256
EK600823 Corp    3.749850    3.749850
EI724801 Corp    6.070826    6.070826

however, I am trying to use three different prices for overrides instead of 100  and cant get it wo work -
 f.i. 

Code:
ID <- c("EI463143 Corp", "EK600823 Corp", "EI724801 Corp")
px <- c(100, 101, 102) 
overrd <- c("PX_DISC_BID"=px)
yld_flds <- c("YLD_YTM_BID", "YLD_CNV_BID")
bdp(securities =  ID, fields = as.vector(yld_flds), overrides = overrd, verbose = FALSE)

Outcome:
Error in bdp_Impl(con, securities, fields, options, overrides, verbose,  : 
  Request overrides must be named.

What am I missing? Can it be that it is only allowed to have one static override for multiple securities?

thx a lot!

**Comment by eddelbuettel** [comment]
I was suspecting something similar -- some calls simply are 'single security'.

**Comment by johnlaing** [comment]
The call will take multiple securities; more accurately it's 'single override':
```
> id <- c("EI463143 Corp", "EK600823 Corp", "EI724801 Corp")
> px <- 100:102
> yld.flds <- c("YLD_YTM_BID", "YLD_CNV_BID")
> bdp(id, yld.flds, overrides=c(PX_DISC_BID=as.character(px[1])))
              YLD_YTM_BID YLD_CNV_BID
EI463143 Corp    7.991323    7.991323
EK600823 Corp    3.749900    3.749900
EI724801 Corp    6.071850    6.071850
```

But it's straightforward to extend to multiple overrides:
```
> lapply(px, function(p) bdp(id, yld.flds, overrides=c(PX_DISC_BID=as.character(p))))
[[1]]
              YLD_YTM_BID YLD_CNV_BID
EI463143 Corp    7.991323    7.991323
EK600823 Corp    3.749900    3.749900
EI724801 Corp    6.071850    6.071850

[[2]]
              YLD_YTM_BID YLD_CNV_BID
EI463143 Corp    7.514054    7.514054
EK600823 Corp    3.228173    3.228173
EI724801 Corp  -25.475076  -25.475076

[[3]]
              YLD_YTM_BID YLD_CNV_BID
EI463143 Corp    7.042749    7.042749
EK600823 Corp    2.712984    2.712984
EI724801 Corp  -56.420731  -56.420731
```

As an aside, I was surprised to discover that I have to cast my prices to character before passing as override. Guessing here, since `bdp_Impl` takes a `vector<string>` is it possible that the names attribute gets dropped if I pass a `vector<double>`?

**Comment by auenbauer** [comment]
Many thanks for helping me with this!



2017-11-17 3:01 GMT+01:00 John Laing <notifications@github.com>:

**Comment by auenbauer** [comment]
Sorry to bother you again with this (my fear is that I miss use this forum
because of the lack of my R knowledge) but my goal would be to apply only
one price to each bond instead of applying each price to each bond and I
don't know how to do it.

id <- c("EI463143 Corp", "EK600823 Corp", "EI724801 Corp")
px <- 100:102 # use 100 for first bond, 101 for second bond and 102
for third bond


sry - don't know how to do that by changing this lapply line

lapply(px, function(p) bdp(id, yld.flds,
overrides=c(PX_DISC_BID=as.character(p))))





2017-11-17 3:01 GMT+01:00 John Laing <notifications@github.com>:

**Comment by eddelbuettel** [comment]
We are not really the right place for general R tutorials, sorry.
