### ISSUE TITLE
blpAuthenticate/blpConnect - what information to use to connect as a server api

### ISSUE THREAD

**Issue by trade-notification2016** [Rblp/Rblpapi#249]
Hi all, first of all, allow me to say this is a question, rather than an issue. but just struggling to find an answer. thank you so much for your time and help!

I do have a proper IP and UUID. I even have the Bloomberg Bpipe demo tool working and connected as a server API user. 

I'm just struggling to figure out what to use in the blpAuthenticate/blpConnect function calls. 

for example: 
is this correct?
blpConnect("69.184.###.##",8194L)
blpAuthenticate("UUID", host = "69.184.###.##", ip.address= "69.184.###.##",  con = defaultConnection())

I really dont think I should put IP as both host and ip.address, but not sure exactly what to use there. 

kindly appreciate your answers. thank you!

**Comment by johnlaing** [comment]
You only need to provide `host` or `ip.address`, not both. By default, `host="localhost"` and we use a system command to convert it to an IP. If you provide an IP address explicitly we will use that instead. The documentation should be more clear about this.

As an additional note, not directly related to your question, generally the IP address used for `blpConnect` is not the same as you want for `blpAuthenticate`. For SAPI (and presumably also for B-PIPE), the IP to connect is the machine where the SAPI (or B-PIPE) process is running, while the IP to authenticate is the machine where you are logged into the terminal.

**Comment by trade-notification2016** [comment]
Thank you for your feedback, John. i will give a try.
