### ISSUE TITLE
connect to remote bloomberg terminal on your lan

### ISSUE THREAD

**Issue by dangulod** [Rblp/Rblpapi#250]
Is it possible to connect to remote bloomberg terminal on your lan, using 

> blpConnect(host ="XXX.XXX.XXX.XXX", port = xxxxx)

**Comment by eddelbuettel** [comment]
The Bloomberg terms of service is pretty specific about this and says nope.

**Comment by akkce** [comment]
> 
> 
> The Bloomberg terms of service is pretty specific about this and says nope.

Do you know if there's an available API from Bloomberg that would support this use-case? I'm helping one of our Investment Mgmt. teams develop a small data warehouse and it would be awesome if we could pull data from their Bloomberg account using R.

**Comment by eddelbuettel** [comment]
You can ... with a Bloomberg data license.

Get your checkbook ready.  Maybe take another checkbook too.
