### ISSUE TITLE
blpAuthenticate issue

### ISSUE THREAD

**Issue by randomee** [Rblp/Rblpapi#251]
I can't seem to authenticate the the Rblpapi package.  The old Rbbg java package works fine.  Not sure what could be wrong.  Nor where to look really.  Any help/hints would be great.

Rbbg (java) working fine:
```
$ R
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)
...
> library(Rbbg)
Loading required package: rJava
> conn <- blpConnect(host=blpHost, port=blpPort)
R version 3.4.1 (2017-06-30)
rJava Version 0.9-7
Rbbg Version 0.5.3
Java environment initialized successfully.
Looking for most recent blpapi3.jar file...
Adding /opt/bloomberg/APIv3/blpapi3.jar to Java classpath
Bloomberg API Version 3.7.4.1
> blpAuthenticate(conn=conn, uuid=blpUUID, ip=blpIP_address)
> bdp(conn, "IBM US Equity", "NAME")
                                     NAME
IBM US Equity INTL BUSINESS MACHINES CORP
>
Save workspace image? [y/n/c]: n
```

Rblpapi version not working
```$ R

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)
...
> library(Rblpapi)
Rblpapi version 0.3.6 using Blpapi headers 3.8.18.1 and run-time 3.8.18.1.
Please respect the Bloomberg licensing agreement and terms of service.
> blpConnect(host=blpHost, port=blpPort)
> blpAuthenticate(uuid=blpUUID, ip=blpIP_address)
<pointer: 0x1e59870>
> bdp("IBM US Equity", "NAME", verbose=T)
ReferenceDataResponse = {
    responseError = {
        source = "bbdbd47"
        code = 1217
        category = "NO_AUTH"
        message = "parmcmofflinethinpipe_managed_ex: asid 16761 server mode (no identity) not allow [nid:929] "
        subcategory = "INVALID_USER"
    }
}
Error: Choice sub-element not found for name 'securityData'.
>
```

**Comment by johnlaing** [comment]
In the old Rbbg, authenticating saves your identity along with the connection and passes it with every subsequent request. In this package the identity object is returned and you are expected to pass it as part of your request. So your code becomes:
```
blpid <- blpAuthenticate(uuid=blpUUID, ip=blpIP_address)
bdp("IBM US Equity", "NAME", identity=blpid)
```

I like the flexibility of our approach in this package, but I think the old behavior is by far the dominant use case. Maybe we can do something analogous to `blpConnect` which stores a single connection by default but also allows a user to choose to have it returned instead. If I get some time this week I'll look into a change

**Comment by randomee** [comment]
Ah.  Ok.  That works.  It'd be great if it could be stored as a default object for calls.

For both Rblpapi and Rbbg it seems like there's not enough documentation on authenticated connections.  Adding an example to blpAuthenticate and a pointer in blpConnect would help quite a lot.

blpConnect...
```
Note: 
    Many SAPI and bPipe connections require authentication via blpAuthenticate() after blpConnect().
```
blpAuthenticate
```
Value: 
    The returned object should be passed to subsequent data calls via bdp(), bds(), etc.  

Examples: 
    ## Not run:
    blpid <- blpAuthenticate(uuid=blpUUID, ip=blpIP_address)
    bdp("IBM US Equity", "NAME", identity=blpid)
    ## End(Not run)
```

I can try to put together a pull request if needed.

Thanks again

**Comment by johnlaing** [comment]
Agreed, documentation is lacking here.

**Comment by randomee** [comment]
Not perfect, but some pointers added in (now merged) pull request. #252
