### ISSUE TITLE
Can't install forked Rblpapi from Github

### ISSUE THREAD

**Issue by auenbauer** [Rblp/Rblpapi#254]
I forked Rblpapi to https://github.com/auenbauer/Rblpapi and tried to install it by:

library(devtools)
install_github("auenbauer/Rblpapi")

I get the error message:

 --library="C:/Users/gleitold/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'Rblpapi' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
curl: not found
mv: cannot stat 'blpHeaders.tar.gz': No such file or directory
tar (child): ../blp/win/x64/blpHeaders.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Exiting with failure status due to previous errors
make: *** [blpLibrary] Error 2
Warnung: Ausführung von Kommando 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="Rblpapi.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o authenticate.o bdh.o bdp.o bds.o beqs.o blpConnect.o blpVersion.o blpapi_utils.o bsrch.o fieldsearch.o getBars.o getFieldInfo.o getTicks.o init.o lookup.o subscribe.o"' ergab Status 2
ERROR: compilation failed for package 'Rblpapi'
* removing 'C:/Users/gleitold/Documents/R/win-library/3.3/Rblpapi'
* restoring previous 'C:/Users/gleitold/Documents/R/win-library/3.3/Rblpapi'
Installation failed: Command failed (1)

An earlier issue had similar problems and there was guidance to install curl.exe to $PATH but unfortunately I don' know how to do this. 

My aim is to try to change the C++ code of GetTics function to "includeRpsCodes" 

thx a lot for your effort and help

**Comment by eddelbuettel** [comment]
That's your problem. Nobody forces you to use `devtools`; if you have an issue with file an issue there.  This is still a source repo you can clone and install from source, or request a zipfile, or ... 

Not an issue with Rblpapi so I will close this in due course.

**Comment by eddelbuettel** [comment]
Also, read the error message:

> `curl: not found`

That's hint.  Your system is simply not setup for a build from source, forked or not.
