### ISSUE TITLE
Subscribe Price is Rounded with no decimal points 

### ISSUE THREAD

**Issue by Research100** [Rblp/Rblpapi#256]
Hi,
When I write a sample query to get the last price through the Subscribe function, I get the data back rounded with no cents. Am I doing something wrong?

subscribe(securities=c("AAPL US Equity","MSFT US Equity"),
          fields=c("LAST_PRICE","BID","ASK"),
          fun=function(x) print(str((x$data$LAST_PRICE))))

Thank you,

 num 177
NULL
 num 177
NULL
 num 177
NULL
 num 177
NULL
 num 177
NULL
 num 177
NULL
 NULL
NULL
 NULL
NULL
 NULL
NULL
 NULL
NULL
 NULL
NULL
 NULL
NULL
 num 89
NULL
 num 89
NULL
 num 89
NULL
 num 89

**Comment by johnlaing** [comment]
Yes, you are doing something wrong: confusing the underlying data with what is printed to console. Calling `str` is printing truncated numbers. Here is a simple example of that behavior:
```
> str(123.45)
 num 123
```

Try performing operations on the data as it comes back, or appending it to a vector which you can then inspect. I think you'll find that everything is fine.

**Comment by Research100** [comment]
Thank you! That helps a lot. One more question. When I make multiple subscriptions on different tickers, which field will tell me the repose belongs to which ticker? I reviewed the response fields, but couldn't figure it out. 

Thank you.
