### ISSUE TITLE
User define SRCH screen (bsrch)?

### ISSUE THREAD

**Issue by Tom9824** [Rblp/Rblpapi#262]
I have a user defined SRCH screen call "green_bonds" with certain criteria.  Per the documentation I would think the following would work:  gb <- bsrch("green_bonds"), but it returns a dataframe with with zero rows and columns.  (Running the screen in BBG gives nearly 3k securities).

The examples work fine.  Am I using the wrong syntax?   I haven't defined a domain, and to be honest I'm not sure what to use.  I'm an equity guy trying to help a friend put together a database of green bonds...

Any help would be appreciated.
Thanks.

**Comment by eddelbuettel** [comment]
You probably want to talk to Bloomberg's help desk to learn how to this programmatically.

**Comment by eddelbuettel** [comment]
And by that I mean:  have a basic C++ example.  If we have that we can extend the package.  Until then we just the service by the API and if no response comes well ... then we don't know either.

**Comment by Tom9824** [comment]
Okay, now I get it.  That I can do.  It seems like this would be a useful function.  

I get a lot of use out of beqs btw. Thanks a ton for that.

**Comment by mtkerbeR** [comment]
Probably a bit late: 
Using the domain `FI` as a prefix worked for me for a bond search saved in Bloomberg's SRCH screen, i.e. `bsrch("FI:rblpapi_test_srch")` - with the search name being case-sensitive.

**Comment by eddelbuettel** [comment]
Thanks for that but we can probably close this  -- but use your working example in a quick unit test?
