### ISSUE TITLE
$topic lost in user function of subscribe_impl

### ISSUE THREAD

**Issue by meisterluk** [Rblp/Rblpapi#265]
Hi,

**Testcase**

we have a script similar to the following:

```
library(Rblpapi)
blpConnect()
id <- "PLACEHOLDER@TRAC Corp"

subscribe(securities=as.vector(id),
          fields=c("BID"),
          fun=function(x) {
            fd <- file("test.txt", "a")
            cat(str(x$topic), file = fd, sep = "\n", append = T)
            cat(str(x$data), file = fd, sep = "\n\n", append = T)
            close(fd)
          })
```

This is not idiomatic code (too many syscalls), but our only goal is to write the string representation of `x` (specifically `$topic` and `$data`) to a file in append mode. We fail to do that, because `x$topic` has a strange behavior:

```
   print(str(x$topic))
```

gives the topic (in the RStudio Console), but if we access it to write it to a file with `cat`, it becomes `NULL` (according to `class()` and `typeof()`) (the first time it had datatype `character`). The resulting file only contains newlines. At this very moment, I do not have access to the system to provide better testcases, so I would like to phrase a specific question indicating a potential problem.

**Analysis**

[subscribe.cpp line 222](https://github.com/Rblp/Rblpapi/blob/master/src/subscribe.cpp#L222) initializes `topic` with `securities[cid]`.
* `securities` is the parameter provided to the user function basically containing a vector with 1 element which is `"PLACEHOLDER@TRAC Corp"`. It outlives the function and is not expected to change.
* `cid` is initialized with `size_t cid(msg.correlationId().asInteger())`. Assuming the correlationId in between calling `subscribe` and `msg.correlationId()` changes, a potential data race is given. To the best of my understanding, [the C++ documentation](https://bloomberg.github.io/blpapi-docs/cpp/3.8/classblpapi_1_1CorrelationId.html#aa58341493f586247dee08e1ed2cfa286) does not indicate that the correlationId is supposed to change. If am on the right track, this question would me more appropriate to ask upstream, I guess.

**Question**

Is it possible there is a race condition somewhere here? For example with `cid`? I am glad about any input and will run testcases the next time (in less than 2 weeks).

[By the way, we run version 0.3.8 and the patch for issue #257 is therefore applied)

**Comment by armstrtw** [comment]
interesting.  Please let me know if you find a race condition.

**Comment by meisterluk** [comment]
@armstrtw Is my assumption correct, that `$topic` and `str(x$topic)` should always return a non-empty string?

**Comment by johnlaing** [comment]
I think this is not an issue with this package but rather with your use of `str` and `cat`:
```
> x <- str(3)
 num 3
> x
NULL
> cat(x)
> cat(str(3))
 num 3
```

`str` prints what you give it but returns `NULL`. You are seeing output in the console (due to `str`) but then `cat`ing `NULL` to the file.

**Comment by meisterluk** [comment]
Oh thanks, @johnlaing. This might be the actual reason. What an awkward type system / function behavior. I am going to test it within the next 2 weeks.

**Comment by meisterluk** [comment]
@johnlaing That's it. That was the reason.

I am sorry for drawing wrong conclusions and sorry about the noise. Thank you all for your support!
