### ISSUE TITLE
A request for `Date` objects to be built using NumericVectors, not IntegerVectors

### ISSUE THREAD

**Issue by DavisVaughan** [Rblp/Rblpapi#271]
See r-dbi/odbc#203 for the description of the issue and Jim Hester's reasoning.

I believe the required line to change is below.

https://github.com/Rblp/Rblpapi/blob/428e60e2a0d5f0672d96d32783fb8ea9b83c9626/src/blpapi_utils.cpp#L338

Should be:

```r
ans = Rcpp::NumericVector(n, NA_REAL); 
```

**Comment by eddelbuettel** [comment]
It's a hornet's nest.  We've been meaning to clean up the data.frame generator for some time.  Those vectors may be old; we by now have better ones in Rcpp.  These also use NumericVector as days can of course be fractional -- just like @jimhester argues in https://github.com/r-dbi/odbc/issues/203.

I don't currently have Bbg access so I can't test your PR.

**Comment by DavisVaughan** [comment]
There is a reference in `addDateClass()` to that `newDateVector.h` file over in Rcpp (not adding value, just saying that those new vectors potentially existed when this was implemented). 

https://github.com/Rblp/Rblpapi/blob/428e60e2a0d5f0672d96d32783fb8ea9b83c9626/src/blpapi_utils.cpp#L140

I'm not sure my rusty Windows skills are going to be enough to be able to build `Rblpapi` from source. I naively tried a few days ago and it failed almost immediately. Didn't have enough time to look through the error messages though. I'll give it another look tomorrow.

**Comment by johnlaing** [comment]
Maybe we should be using `Rcpp::DateVector` here? That's easy enough to fix, I'll give it a try this morning. @eddelbuettel if I'm misguided here please let me know.

**Comment by armstrtw** [comment]
Not exactly clear in R either.  I actually prefer integer for pure 'days'.  People wanting higher res should use POSIXct (IMHO).

> storage.mode(Sys.Date())
[1] "double"
> storage.mode(seq.Date(Sys.Date(),length.out=10,by="days"))
[1] "integer"
>

**Comment by eddelbuettel** [comment]
I think that is a bad example.  `seq()` always gets us `integer` by a convention _for sequences_.

```r
R> storage.mode(Sys.Date() + 0:9)
[1] "double"
R> 
```

**Comment by armstrtw** [comment]
did you mean to close the issue?

not a 'bad' example, just an example of the fact that R doesn't care what the storage mode is, as long as it provides the necessary precision to represent a date, and integer is sufficient for that.  I'm keen to see an example in which using integer causes a breakage or bug in R.  That would be a motivating case for the change.

other examples:
> print(Sys.Date()+.1,format="%Y%m%d %H%M%S")
[1] "2018-07-24"
> print(as.POSIXct(Sys.Date()+.1),format="%Y%m%d %H%M%S")
[1] "2018-07-23 22:23:59 EDT"
>

I don't really care one way or the other.  Conceptually, I favor integer as it does provide the necessary precision with less memory usage, but for daily data, that's never really going to be an issue.

If you all want to change it to be consistent w/ R, then go for it.

**Comment by eddelbuettel** [comment]
Yes, as I merged the PR, and yes it is important to do the same as R because Dates can frequently contain fractional information.  If it is important to you to save the 32 bits on each entry by all means revert.

**Comment by armstrtw** [comment]
I said conceptually, but you gave me no chance for objection anyway. it doesn't really matter.

**Comment by armstrtw** [comment]
are you aware you are being a dick, or are you just being German.

**Comment by armstrtw** [comment]
pls disregard previous.  my misinterpretation of what you meant.

**Comment by eddelbuettel** [comment]
No mas.  

I wasn't very clear but you grokked: the old date(time)vectors (call them iteration 1) where awful which is the reason you had the local {Numeric|Integer}Vector ones here (call them iteration 2).   These days we can rely on the newer ones in Rcpp (iteration 3) which improve on both prior ones.

**Comment by DavisVaughan** [comment]
If you wanted some testing and could put the new version in the `ghrr/drat` I could probably install from there and test it out. No problem if that's too much trouble.

**Comment by eddelbuettel** [comment]
What is preventing you from cloning?

**Comment by eddelbuettel** [comment]
BTW @armstrtw in case you work with `data.table` then:

     ‘ITime’ is a time-of-day class stored as the integer number of
     seconds in the day. ‘as.ITime’ does not allow days longer than 24
     hours. Because ‘ITime’ is stored in seconds, you can add it to a
     ‘POSIXct’ object, but you should not add it to a ‘Date’ object.

I often keep columns of POSIXct as well as IDate and ITime around.  Makes for good grouping.
