### ISSUE TITLE
BDP - value without decimals

### ISSUE THREAD

**Issue by auenbauer** [Rblp/Rblpapi#277]
bdp("ibm us equity", "px_last")
              px_last
ibm us equity     146
> 
The code above provides a data.frame with 146 as  value for px_last. However, px_last is 146.48. How can I avoid that the decimals are removed?

**Comment by armstrtw** [comment]
check your defaults. You can always set verbose=TRUE to see exactly what bbg is returning.

> options(digits=1)
> bdp("IBM Equity","PX_LAST")
           PX_LAST
IBM Equity     146
> options(digits=7)
> bdp("IBM Equity","PX_LAST")
           PX_LAST
IBM Equity  146.48
>


> bdp("IBM Equity","PX_LAST",verbose=TRUE)
ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "IBM Equity"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                PX_LAST = 146.480000
            }
        }
    }
}
           PX_LAST
IBM Equity  146.48
>
