### ISSUE TITLE
Save connection

### ISSUE THREAD

**Issue by johnlaing** [Rblp/Rblpapi#28]
[moving off email, per Dirk's request]

TL;DR: we should save a connection in the package environment and use it by default so that people don't have to deal with passing the same connection to every single function call.

I've made a few more changes and pushed a branch to my repo. Let me know what you think.

**Comment by armstrtw** [comment]
are you going to preserve the traditional interface in blpwrapper?

**Comment by armstrtw** [comment]
so, something like this:

bb.con <- new.env()

.onAttach <- function(libname, pkgname) {
    bb.con$con <- blpConnect(blah blah from options)
}

**Comment by johnlaing** [comment]
I plan to preserve the traditional interface in a transitional Rbbg -> Rblpapi package (probably to be called Rbbg2). But I'm not quite sure what you mean by the example.

I don't intend to connect automatically on attachment -- I don't think that's desirable. You'll still have to call blpConnect(), but the connection will then be saved and available for future use.

**Comment by johnlaing** [comment]
Working:
```
> require(Rblpapi)
Loading required package: Rblpapi
> blpConnect(host="app", port=8194)
> bdp("GOOG Equity", "PX_LAST")
            PX_LAST
GOOG Equity  547.77
```

**Comment by eddelbuettel** [comment]
I missed this as I am not (by default) subscribed to an issue in Whit's project.  Please ping @eddelbuettel if you want me.

In e.g. RPushbullet I do [this very thing](https://github.com/eddelbuettel/rpushbullet/blob/master/R/init.R#L21-L38); I think I concluded you nee `assign(...)` rather than just `<-`.

**Comment by eddelbuettel** [comment]
I believe we ended up implementing something that pleases everyone: autoconnect for those who want it, manual connect as before otherwise.
