### ISSUE TITLE
getPortfolio, Attempt to access value of element 'PORTFOLIO_NAME'(type: 'String') as 'Element' type.

### ISSUE THREAD

**Issue by akkce** [Rblp/Rblpapi#280]
Hello.

I'm having some issues with the getPortfolio where it looks like Bloomberg's API is returning a String and R is trying to access it as an Element. I'm very new to both R and Bloomberg so I'm not sure if this issue is on my end (i.e., I'm not casting the data type correctly) or with Bloomberg:

`> getPortfolio("PORTID-FUNDID Client", "PORTFOLIO_NAME", verbose=TRUE)
PortfolioDataResponse = {
    securityData[] = {
        securityData = {
            security = "PORTID-FUNDID Client"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                PORTFOLIO_NAME = "myPortfolioName"
            }
        }
    }
}
Error in getPortfolio_Impl(con, security, field, options, overrides, verbose,  :
  Attempt to access value of element 'PORTFOLIO_NAME'(type: 'String') as 'Element' type.`

The value of the PORTFOLIO_NAME field is correct but I cannot seem to figure out how to force the call to treat it as a string. 

I get the same error when trying to pull the following fields:

- PORTFOLIO_NAME
- PORTFOLIO_POSITION_TYPE
- PORTFOLIO_BENCHMARK
- PORTFOLIO_BASE_CURRENCY
- PORTFOLIO_ASSET_CLASS

For what it's worth I do get the expected results when using the PORTFOLIO_MEMBERS, PORTFOLIO_MPOSITION and PORTFOLIO_MWEIGHT fields.

I'm using R 3.5.1 and Rblpapi 0.3.8.

Thanks.

**Comment by johnlaing** [comment]
As these are descriptive fields (rather than bulk data) I think you can get them using just `bdp`. Give that a try and let us know.

**Comment by johnlaing** [comment]
Unfortunately I don't have much to offer here. Documentation is exceptionally sparse for the portfolio functions.  If it's helpful, `getPortfolio` is similar to `bds` on the backend so it deals with bulk fields.
