### ISSUE TITLE
Rblpapi affected by Bloomberg V2 API retirement

### ISSUE THREAD

**Issue by GeorgiePete** [Rblp/Rblpapi#287]
Hi, 
I received a message from Bloomberg saying that I recently used an API that will be retired soon (ActiveX VBA Data Control (blpdatax.dll) and the V2 C-API (bbapi.dll)).  I think Rblpapi is the only application on my computer that uses the Bloomberg API.  Now I'm afraid that the Rblpapi is affected by this change in Bloomberg's API policy.  Hence I wanted to ask you whether or not the Rblpapi package will be affected by the upcoming changes in the Bloomberg API policy?
Where can I see which version of the Bloomberg API is used by Rblpapi?

**Comment by eddelbuettel** [comment]
As for the final question, on startup you should see this message:

```r
    packageStartupMessage(paste0("Rblpapi version ", packageVersion("Rblpapi"),
                                 " using Blpapi headers ", getHeaderVersion(),
                                 " and run-time ", getRuntimeVersion(), "."))
```

At any point in time you call the two helper functions for the version info.

**Comment by GeorgiePete** [comment]
Bloomberg API retirement did not affect Rblpapi
