### ISSUE TITLE
Possible update to docs, clarifying that the package (probably) will only work on Windows?

### ISSUE THREAD

**Issue by glennlawyer** [Rblp/Rblpapi#289]
The docs state that the status is `Fully functional on Linux, OS X and Windows.`

However, they also state that a requirement is `A valid and working Bloomberg installation.`

As far as I know, including after several talks with Bloomberg support, Bloomberg only runs under windows. Thus it is "impossible" to have a valid and working Bloomberg installation on other systems.

Ref: issue #152 

```
I was not able to find testimonials on whether Rblpapi works on Mac (OS X 10.10.5) with Bloomberg Anywhere. Installing the package and loading it works fine (R Studio with R 3.2.4) but when trying to connect (blpConnect) I get the following:

...
    ... connection failed ...
...
```
noting that my system setup and connection error message is similar to the above. 

@wmorgan85's answer to the issue is:
```
Rblpapi will not work with Bloomberg Anywhere because it requires a locally
installed instance of Bloomberg (and more specifically bbcomm) to access
the API.
```
(Bloomberg Anywhere is Bloomberg's option for running on non-Windows machines. It uses a Citrix client to open a connection to Bloomberg)

If you could either share your notes on how you got a valid and working Bloomberg installation on a non-Windows machine, that would be great (set up a virtual machine??). Otherwise, it might save people some needless frustration if the docs were more explicit that the requirements cannot be met on these OSs, rendering the status of the package something less than "fully functional."

Hate to carp, your work has always been excellent. And clearly the issue here is with Bloomberg, not with your package.

Noting #219, one solution could be Docker with a  Bloomberg installation. Anyone aware of such an image? Also noting @eddelbuettel's comment that this may or may not be within scope of the license.

Noting https://aws.amazon.com/solutionspace/financial-services/solutions/bloomberg-b-pipe/
there appears to be an AWS solution, but this also looks expensive, as it replaces on-premises Bloomberg deployment 

> which requires customers to install two Bloomberg circuits, servers, and switches in their hosting site, consuming rack space and network ports, incurring extra costs, and spending weeks and months to ship, install. and configure

Also in reference to #152 , noting @hbailer clarifies his original comment
```
Sorry I like to point out that it **absolutely works** with Bloomberg Anywhere.
```
with
```
if you run Bloomberg Anywhere directly from the Browser it does not work. You need to install the actual terminal software. Since Bloomberg only provides it for Windows OS you need to install parallels & windows on your PC - what a drag...
```
which seems to agree with @wmorgan85  's more authoritative comment that `Rblpapi will not work with Bloomberg Anywhere`

**Comment by randomee** [comment]
I think BBG support was confusing a few things.  

Yes, one cannot use Rblpapi with the browser only version of BBG.  You need the same setup as you do for using BBG from Excel (namely bbcomm running).  

I use Rblpapi from Linux in production every day.  Works fine.  We're connecting to a SAPI server, not DAPI (desktop).  Some SAPI installs require blpAuthenticate, some do not.  I believe Rblpapi also works fine with bPipe.  Though I've not tried it.  

Fwiw, I've tried running a linux VM on windows, then port forwarding the bbcomm port to linux, and it works fine.  I believe that complies w/ the license terms.  We did not work more on that since BBG was willing to give us SAPI access at a reasonable rate.  Caveat emptor.

**Comment by glennlawyer** [comment]
Ok, then perhaps the docs could clarify that this is what is meant by `a valid and working Bloomberg installation`? 

Coming at this as a new Bloomberg user with decades of R experience, I had interpreted the docs as meaning it would *just work* on linux/mac machine. This is clearly not the case-- i.e. setting up a SAPI Bloomberg server. 

Your VM example presupposes a working Windows machine for the connection. So, while technically correct, is not so helpful for someone without that underlying OS.

Again, this is Bloomberg's fault, not yours, but I still find the line: 
```
Fully functional on Linux, OS X and Windows.
```
a bit of an overstatement.

One or two sentences added to the  `Requirements` section at the top of the Readme would make it immediately clear that non-windows users are in for special treats. Something like:

```
# Requirements
A valid and working Bloomberg installation.

Note that Bloomberg Anywhere (the Bloomberg solution for Linux/OSX) is not a valid Bloomberg installation. Users not on a Windows machine will need to have a SAPI Bloomberg Server or some other Bloomberg product which creates a (local) bbcomm process for access to the Bloomberg API.

You need the same setup as you do for using BBG from Excel (namely bbcomm running).
```

**Comment by armstrtw** [comment]
I think anyone who really uses Bloomberg understands what is required.

If you strongly feel the documentation requires clarification, submit a patch.

**Comment by lee170** [comment]
Bloomberg API [docs](https://www.bloomberg.com/professional/support/api-library/) say:

> API macOS
> These Bloomberg API libraries cannot be used by Bloomberg Professional terminal users (which use the Desktop API). They are only compatible with the Bloomberg Server API and B-Pipe data feed products.
