### ISSUE TITLE
Staged installs

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#290]
I received mail from BDR about an upcoming R 3.6.0 change which will be activated by March 1:

> This concerns packages

> EmiStatR ProjectTemplate RVowpalWabbit Rblpapi bayesdfa bigMap bmlm
distrEllipse franc gWidgets2 ganalytics glmmfields nimble polidata prcbench
race rfishbase spdynmod trialr uavRst walker zonator

> Staged installation is to be a new feature of R 3.6.0: it is not yet the
default in R-devel but it is scheduled to become so on Mar 1.  To turn it on
before then, set environment variable R_INSTALL_STAGED=true : this has been
done for the fedora-clang results on CRAN.

> Tomas Kalibera has written a blog about this which can be seen at
https://developer.r-project.org/Blog/public/2019/02/14/staged-install/index.html
.  For most of these packages he has some analysis of the issues at
https://github.com/kalibera/rstagedinst/tree/master/hardcoded
and is happy to help with interpretation (he is Cc:ed here).

> Please adjust your package to work with staged installation, if possible
before Mar 1.  A stopgap measure is to opt out by adding

> StagedInstall: no

> in the DESCRIPTION file, and the CRAN team will do that for any remaining
packages on which others depend (currently EmiStatR ProjectTemplate Rblpapi
gWidgets2 nimble rfishbase) when the default is switched.

I am inclined to do a minimal maintenance releases taking the existing package and just adding that one suggested line as I cannot currently test Rblpapi.

Thoughts?

**Comment by johnlaing** [comment]
I agree, for now: the best short-term solution is `StagedInstall: no`

I can test Rblpapi and will look into how to fix our installation process to work with staged install. Based on a quick read of Tomas's blog this looks non-trivial. In particular we jump through some hoops around retrieving the Bloomberg libs that may be tricky to clean up.

**Comment by eddelbuettel** [comment]
Awesome -- thanks for the quick reply.  I do keep r-devel built on my machine at home so I can test, but it of course has no blp connection nearby.

**Comment by eddelbuettel** [comment]
OTOH we had a few PRs in since the last release and more pending so a case could be made for a new release candidate which with a bit of testing may suit.  I guess I can argue myself into a knot either way.

**Comment by johnlaing** [comment]
I vote minimal maintenance for now.

I'll try to get motivated to tackle the pending authentication items. Then we can take those and the other PRs and maybe even a better staged install solution and roll a full release. But no promise on timing, hence: minimal maintenance release.

**Comment by eddelbuettel** [comment]
Works for me.  A problem tackled and taken care of is one less on the agenda.
