### ISSUE TITLE
Bloomberg Anywhere functionality request

### ISSUE THREAD

**Issue by VaughanHenkel** [Rblp/Rblpapi#292]
HI

I know the ticket was closed in Aug 2016 but I use Bloomberg anywhere and was wondering if the ability to draw data from the terminal version will be extended in future releases.

**Comment by eddelbuettel** [comment]
Generally it is "he/she who needs it gets to drive the process" -- so if you need some code to be added, it is best for you to propose and (once consensus established) implement that change.

**Comment by johnlaing** [comment]
Also see discussion in #152 , to the best of my understanding Bloomberg does not support this functionality. In that case there would be nothing we can do.

**Comment by VaughanHenkel** [comment]
thanks
