### ISSUE TITLE
install Rblpapi 3.6.2 from source

### ISSUE THREAD

**Issue by Courvoisier13** [Rblp/Rblpapi#295]
Hi I need to install Rblpapi 3.6.2 from source because I am using R3.6 and I can't install from binary. I need this because of the #281 issue.
I tried:

   packageurl <- "https://cran.r-project.org/src/contrib/Archive/Rblpapi/Rblpapi_0.3.6.tar.gz"
   install.packages(packageurl, repos=NULL, type="source")

but it gave the following error:

   sh: curl: command not found
   mv: cannot stat 'blpHeaders.tar.gz': No such file or directory
   tar (child): ../blp/win/i386/blpHeaders.tar.gz: Cannot open: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
   make: *** [Makevars.win:46: blpLibrary] Error 2
   ERROR: compilation failed for package 'Rblpapi'
   * removing 'D:/libraries/R/libraries-3.6.1/Rblpapi'

I downloaded the https://github.com/Rblp/Rblpapi/archive/0.3.6.tar.gz file and tried to build and found that the folder ../blp/win/ only has an x64 folder that one is empty. 

What should I complete in this folder in order to be able to build the package?

thanks

**Comment by eddelbuettel** [comment]
Install `curl` as the error message says. 

Also consider learning markdown formatting to make  your answers more easily readable.  There is a link in _every_ edit box.

**Comment by eddelbuettel** [comment]
> What should I complete in this folder in order to be able to build the package?

It is all open source.  You can read every command, step by step. Start with [`configure`](https://github.com/Rblp/Rblpapi/blob/master/configure) as R does.

**Comment by Courvoisier13** [comment]
I am using an older version of chrome :( and can't update it. I can't edit and I can't or insert "code" unfortunately. it's very annoying apologies. 

so I need cURL from https://curl.haxx.se/download.html? 

Also I am under windows. are the path in the configure the same ?

**Comment by eddelbuettel** [comment]
> I am using an older version of chrome :( and can't update it. I can't edit and I can't or insert "code" unfortunately. it's very annoying apologies.

Entirely wrong but I don't have the time to teach you all of this.

Also consider googling "how to install curl on Windows".  Used by hundreds of millions of people. There are binaries.

Please do your homework, we are all busy.  _The package obviously builds at CRAN for a variety of systems_ including yours as shown here:   https://cloud.r-project.org/web/checks/check_results_Rblpapi.html

**Comment by entropy43** [comment]
It actually would have taken you **_less_** time to just tell him "You haven't got curl installed. You can install it from here (insert link)". You just **wanted** to unhelpfully flame him. As ever.

And while you're on your high horse, it's highly unlikely that there are "hundreds of millions" of windows users explicitly installing curl for themselves.

I'd insert some link about not being rude but (1) I haven't got time to teach you all of this and (2) it's pretty standard form from you.
