### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by kevinho1996** [Rblp/Rblpapi#296]
Is there a way I can blpConnect using my username and password rather than opening the bloomberg?

**Comment by johnlaing** [comment]
Not really. The desktop API requires an active terminal login. Bloomberg offers other products (SAPI, B-PIPE) that bypass the terminal but those are a different can of worms.

**Comment by eddelbuettel** [comment]
In fact, it is almost the inverse:  Rblpapi can only work _if and only if_ you are logged into your terminal the standard way.

Their software, their API, their rules.  We only get to pay the fees....
