### ISSUE TITLE
Does bdh() function retrieve intra-daily history at this moment? 

### ISSUE THREAD

**Issue by ChloeTian** [Rblp/Rblpapi#299]
By digging into 'Pull historical intraday data from Bloomberg with R' https://stackoverflow.com/questions/46429930/pull-historical-intraday-data-from-bloomberg-with-r, I already know that 'barsz' or 'bartp' couldn't be specified in bdh() function. This related question in this attached link was answered two years ago, and when I tried `=BDH("ABLX BB EQUITY","OPEN","06/01/17 09:00","06/30/17 09:05","recurdaily=true","barsz=5","bartp=B")` I still got the same issue. Does it mean bdh() function still doesn't retrieve intra-daily history at this moment? 

Thanks.

**Comment by johnlaing** [comment]
No, `bdh` is for daily (or lower frequency) historical data. As Dirk says in the SO link, if you want intraday bars use `getBars`.

**Comment by ChloeTian** [comment]
> No, `bdh` is for daily (or lower frequency) historical data. As Dirk says in the SO link, if you want intraday bars use `getBars`.

Thank you!

**Comment by eddelbuettel** [comment]
So ok to close this?
