### ISSUE TITLE
API cleanup

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#30]
If we are redoing the function interface by having a default `con` in the environment, can we also standardize other arguments?   `start.time` vs `startTime` is just one example.

**Comment by armstrtw** [comment]
I think my original code had used 'start.date'
https://github.com/armstrtw/Rblpapi/blob/master/R/bdh.R#L33

but I see startTime in getBars and getTicks.

You prefer the camelCase ?

I don't really care, I have tried to use dot.separated names as I thought that was the historical convention in R.  but if you want to disabuse me of this belief, then I'll happily switch.

-Whit

**Comment by eddelbuettel** [comment]
All statements are true.

We both have been using R long enough to remember `dot.separated.variables` in R code. I am under the very firm impression that that is an old and somewhat (albeit informally) deprecated habit.  I think the best evidence is this [(really funny too) useR presentation from 2013 about convention](http://sumsar.net/files/academia/UseR_2013_R_naming_conventions_final.pdf) by Rasmus Baath.

I like `camelCase` a lot better.  No confusion with S3 dispatch.

Your project, your call.   But modern times call for `modernNamingConventions`.

Anything else to clean up?  I'll try to get my OS X using colleagues to peek at the build script.  This should also build there...

**Comment by armstrtw** [comment]
as long as you don't want to use underscores I'll be ok.

JL does not believe me, but I can remember the days of _ as assignment operator in R...  yes, I guess I am truly ancient now.

lowerCamel is fine w/ me.

I can take care of this one.

**Comment by eddelbuettel** [comment]
`apt-get install ess`, then open `/tmp/foo.R` and press `_` .... which becomes a `<-` by convention.  But was _ an actual operator?  I don;t recall that.

And yes, underscores and `snake_case` are the devil.  We know full well who propagates that :)

**Comment by johnlaing** [comment]
I do believe the presentation you linked argues for period-separated parameters (slide 64).

**Comment by eddelbuettel** [comment]
In which case I withdraw the evidence suggested and rule by fiat. Or by begging.  Whatever works :)

**Comment by armstrtw** [comment]
R : Copyright 2001, The R Development Core Team
Version 1.3.1  (2001-08-31)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type `license()' or `licence()' for distribution details.

R is a collaborative project with many contributors.
Type `contributors()' for more information.

Type `demo()' for some demos, `help()' for on-line help, or
`help.start()' for a HTML browser interface to help.
Type `q()' to quit R.

> x _ 10
> x
[1] 10
>

**Comment by johnlaing** [comment]
I suppose I can be OK with lowerCamel for functions and args. Go nuts.

**Comment by eddelbuettel** [comment]
Sccchwwwweeeeeet. Where did you get a version THAT ancient so fast?

**Comment by armstrtw** [comment]
http://cran.r-project.org/bin/windows/base/old/

**Comment by eddelbuettel** [comment]
I guess that is what virtual machines were made for ...

**Comment by eddelbuettel** [comment]
By the way, [this SO post](http://stackoverflow.com/a/13413278/143305) may have been what I had in mind.

**Comment by eddelbuettel** [comment]
I think we can close this one too.
