### ISSUE TITLE
Error: package or namespace load failed for ‘Rblpapi’

### ISSUE THREAD

**Issue by aveshenpillay** [Rblp/Rblpapi#300]
Good day, I have an error when trying to install the Rblpapi package. I have only run two lines:

install.packages("Rblpapi")
library(Rblpapi)

My OSX installation is Catalina (10.15.3)

<img width="963" alt="Screenshot 2020-02-04 at 23 08 07" src="https://user-images.githubusercontent.com/27091888/73787290-a8798900-47a3-11ea-9842-48b2f73982ed.png">

**Comment by eddelbuettel** [comment]
Any macOS users who could chime in?

**Comment by steveputman** [comment]
Looks like a similar issue to #189. Seems like the reference to `libblpapi3_64.so` is pointing to a path on a dev's local computer?

I got it to load by issuing the following command in terminal:

`/Library/Fr/R/V/3.6/R/libr/Rb/libs ❯ install_name_tool -change /Volumes/SSD-Data/Builds/R-dev-web/QA/Simon/packages/el-capitan-x86_64/Rlib/3.6/Rblpapi/blp/libblpapi3_64.so /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rblpapi/blp/libblpapi3_64.so Rblpapi.so`

**Comment by eddelbuettel** [comment]
Thanks for the follow-up!  If you can think of a means to automate that or make it part of the macOS build let us know.

**Comment by steveputman** [comment]
@eddelbuettel It appears to be a CRAN issue. I forked this repo to see if I could come up with any tweaks to `Makevars.in` to address it, and when I installed from master before making any changes, I got a clean install and load.

**Comment by eddelbuettel** [comment]
Thanks for the follow-up, much appreciated.  

So let's keep it open as a reminder for people to build locally if need be.  The macOS maintainer tends to be super-busy and doesn't always reply in time so I won't escalate this.

**Comment by danilosarti** [comment]
library(devtools)
install_github("Rblp/Rblpapi")
require("Rblpapi")

this solved the problem for me!!

**Comment by eddelbuettel** [comment]
This seems addressed.
