### ISSUE TITLE
getTicks_Impl error while running getTicks 

### ISSUE THREAD

**Issue by ChloeTian** [Rblp/Rblpapi#301]
While running getTicks, sometimes it throws error : `getTicks_Impl(con, security, eventType, startUTC, endUTC, setCondCodes = returnAs %in% : std::bad_alloc)`, but sometimes it generates results without any errors.

Please find codes attached:
`
library(Rblpapi)
`
`con <- blpConnect() 	
`
`start <- '2020-01-3008:00:00'
`
`end <- '2020-01-3020:55:55'`
`tickData <- getTicks('ESH0 Index', eventType = c("BID","ASK"), startTime = as.POSIXct(start,tz='GMT') - 60 ,endTime = as.POSIXct(end,tz='GMT') - 60, verbose = FALSE, returnAs = getOption("blpType","data.frame"), tz = Sys.getenv("TZ", unset = "GMT"),con = defaultConnection())`

Does anyone experience the same issue? 

Thanks

**Comment by eddelbuettel** [comment]
Please take a look at _e.g._ this write-up at StackOverflow on [how to create a minimally complete verifiable example](https://stackoverflow.com/help/minimal-reproducible-example).  At present, we cannot help you with your issue.

As a simple sanity check at your end, try what it in the example part of `help(getTicks)`:

```r
  res <- getTicks("ES1 Index")
  str(res)
  head(res, 20)
```

**Comment by ChloeTian** [comment]
> Please take a look at _e.g._ this write-up at StackOverflow on [how to create a minimally complete verifiable example](https://stackoverflow.com/help/minimal-reproducible-example). At present, we cannot help you with your issue.
> 
> As a simple sanity check at your end, try what it in the example part of `help(getTicks)`:
> 
> ```r
>   res <- getTicks("ES1 Index")
>   str(res)
>   head(res, 20)
> ```

**Comment by ChloeTian** [comment]
> Please take a look at _e.g._ this write-up at StackOverflow on [how to create a minimally complete verifiable example](https://stackoverflow.com/help/minimal-reproducible-example). At present, we cannot help you with your issue.
> 
> As a simple sanity check at your end, try what it in the example part of `help(getTicks)`:
> 
> ```r
>   res <- getTicks("ES1 Index")
>   str(res)
>   head(res, 20)
> ```

Sorry about the mistake I made when I raised this topic of issue. I have updated my descriptions of the questions. Thank you for your suggestions.

**Comment by eddelbuettel** [comment]
`start <- '2020-01-3008:00:00'` looks bad.  What happens when you try an ISO 8601 date such as `2020-01-30 08:00:00`.  The space may matter.

**Comment by eddelbuettel** [comment]
Could you please confirm that things work fine when you correctly enter start and end time?

**Comment by ChloeTian** [comment]
> Could you please confirm that things work fine when you correctly enter start and end time?

Unfortunately, I guess it still throws the error sometimes.

**Comment by eddelbuettel** [comment]
"Sometimes" is not something we can help with very easily.  

If you can, please provide a _simple_ and _reproducible_ example -- and then feel free to reopen the issue with it, but I will now close it for lack of specifics.
