### ISSUE TITLE
bdh

### ISSUE THREAD

**Issue by cdspqi** [Rblp/Rblpapi#302]
https://github.com/cdspqi/quickfix/issues/1#issue-561876802

(Edited by @eddelbuettel to repair this)

In the example below, overrides don't seem to be working:

```r
start_date <- as.Date("2020-02-05")
end_date <- start_date
field_name <- "EQY_WEIGHTED_AVG_PX"
ticker <- "FXI US Equity"
bbg_overrides<-c(VWAP_START_TIME="14:00", VWAP_END_TIME="15:00")

bdh(ticker,fields=field_name,start.date=start_date,
        end.date=end_date,overrides=bbg_overrides)
```

yields

```
date EQY_WEIGHTED_AVG_PX
1 2020-02-05 41.4351
```

The value returned above is for the whole day. The actual value for the time period I specified should be 41.3959 (note that the default time zone on my host machine is CST)

**Comment by johnlaing** [comment]
Perhaps you meant to open the linked issue here rather than in your own copy of the project?

Anyway, unfortunately I have no insight into how to specify vwap overrides. We pass the overrides as text into the API - perhaps the problem is date/time formatting. This is more a question for the helpdesk. They won't know anything about Rblpapi but in theory someone should be able to help with the C++ API, which we are just a wrapper around.

**Comment by cdspqi** [comment]
Thanks John.  Yes, I did intend to open this issue here...rookie mistake.  I will check on the VWAP_START_TIME / END_TIME formatting with the helpdesk - although it does work as a character string through Excel.

**Comment by eddelbuettel** [comment]
@cdspqi You can still _edit_ entry above.  Go to the issue you linked, click on '...', select edit, copy the content and then do the same above.

But as @johnlaing said: likely not our issue here as we just 'transmit' the value via the API as a transport means to have the _request_ resolved at their end.  At it is that last bit that coughs here.

**Comment by eddelbuettel** [comment]
I suggest you press F1 on your Bloomberg terminal and discuss that with the help desk.  _We do not process the answer which is what you get._  Your time window may be off (timezones?), or the field may be wrong, or ...

**Comment by cdspqi** [comment]
[636738954_APP_API_Services_USRG_170831.pdf](https://github.com/Rblp/Rblpapi/files/4192972/636738954_APP_API_Services_USRG_170831.pdf)
Page 51 (VWAP SCHEMA) of the attached reference guide outlines the VWAP schema subscription options.  It appears that my call above is consistent with these options.  Also, it is not a timezone problem as my terminal time zone (TZDF) is set to Central Daylight Time.

**Comment by johnlaing** [comment]
The schema you reference is for the streaming vwap service, but what you seem to be looking for is a historical price average. Apples to oranges.

You say that it works correctly in Excel. It would be helpful to see what you're doing there, because I get the same results in Excel as in R.

**Comment by cdspqi** [comment]
Looks like I made a mistake.  Excel implementation for bdh() doesn't expose VWAP_START_TIME / VWAP_END_TIME as per full override list when you look at FLDS function in bbg terminal.

**Comment by eddelbuettel** [comment]
Ok to close then?

**Comment by cdspqi** [comment]
Yes. Thanks!

On Feb 12, 2020, at 11:28 AM, Dirk Eddelbuettel <notifications@github.com> wrote:

﻿

Ok to close then?

**Comment by travis-leith** [comment]
Just popping in here to say that the field you used is for a BDP request, not a BDH request. Probably why you don't get the results you expect.
