### ISSUE TITLE
bdh overrides

### ISSUE THREAD

**Issue by cdspqi** [Rblp/Rblpapi#303]
In the example below, overrides don't seem to be working:
start_date <- as.Date("2020-02-05")
end_date <- start_date
field_name <- "EQY_WEIGHTED_AVG_PX"
ticker <- "FXI US Equity"
bbg_overrides<-c(VWAP_START_TIME="14:00", VWAP_END_TIME="15:00")

bdh(ticker,fields=field_name,start.date=start_date,end.date=end_date,overrides=bbg_overrides)

date EQY_WEIGHTED_AVG_PX
1 2020-02-05             41.4351

The value returned above is for the whole day. The actual value for the time period I specified should be 41.3959 (note that the default time zone on my host machine is CST)

**Comment by eddelbuettel** [comment]
You created a *new issue* which is not what I suggested / asked in #32 

Closing, and editing myself.

**Comment by cdspqi** [comment]
Misunderstood.  Thanks Dirk!
