### ISSUE TITLE
Q: Why is there duplicate validation in bdp?

### ISSUE THREAD

**Issue by Ljupch0** [Rblp/Rblpapi#305]
Hi Dirk and John, thanks for the great package.

Can you shed some light as to why bdp doesn't accept duplicates?

My use case: take an entire column of bloomberg identifiers out of dataset, plug in to bdp, and merge the resulting dataframe by bloomberg id. There will definitely be duplicates in the initial column.

Many thanks.

**Comment by johnlaing** [comment]
It makes sense to prohibit duplicates for (at least) 2 reasons:
* It would be unnecessary to ask Bloomberg for the same information multiple times, so we pass each identifier into the API only once.
* The returned object contains identifiers as its rownames, which again only appear once.

You can easily call `unique` on your input to make it work. This is preferable to having the package do the same behind the scenes, which would break the alignment between input and output.

**Comment by Ljupch0** [comment]
Hi John, thank you for the quick response. I completely agree.

**Comment by johnlaing** [comment]
I'm not sure what has changed from the scenario you initially reported. As I see it, we can't duplicate output because we use rownames to link output to input - and rownames can't be duplicated. Do you have a way around this?

**Comment by Ljupch0** [comment]
Aha I see the issue. I use Rblpapi in a dplyr centric workflow and convert things to tibbles where there are no rownames. I think the best solution is a separate package that wraps Rblpapi so it plays well with the tidyverse. What do you think?
