### ISSUE TITLE
Formula BQL?

### ISSUE THREAD

**Issue by cnordenlow** [Rblp/Rblpapi#316]
Hi, im trying to recreate a formula using this package that can generate all outstanding bonds from an issuer. In excel, I´,m using the BQL-formula below but I would like to being able to get it in R. If this is possible, I would greatly appreciate your assistance.

Thanks, Chris

=BQL("BONDS('DIS US Equity')","ID_ISIN","NAME")

**Comment by armstrtw** [comment]
is bql supported in the c++ api?

**Comment by klin333** [comment]
The BQNT python module somehow gets around it and supports bql execution. It's beyond me how it does it.

C:\blp\BQuant\environments\bqnt-xxxx\Lib\site-packages\bql\
  -> service.py has execute() which you can call with a bql query string
  -> it then calls complicated functionality in the request folder

No idea if such functionality can be replicated in rblpapi or even allowed to.

**Comment by Ljupch0** [comment]
I think BQNT is a walled garden and you cannot take out the data from the terminal. The only place currently you can get BQL data freely is Excel.
