### ISSUE TITLE
Maturity date of a bond

### ISSUE THREAD

**Issue by calik97** [Rblp/Rblpapi#327]
Is there a way to extract the maturity from a Bond by using some formula in the Rblpapi library?

**Comment by wmorgan85** [comment]
There are examples in the README that show how to use `bdp` to get single data points. The field in Bloomberg for this information is literally `MATURITY`. For more specific details and questions on the behaviour of individual fields, I would recommend pressing HELP on your keyboard twice and asking in IB. They are generally good at solving Bloomberg API questions!
