### ISSUE TITLE
Switch vignette to minidown

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#329]
One minor change I suggest we wrap into the update is to switch the vignette from the current (quasi-default) of `rmarkdown::html_vignette` to the newer contributed style of package [minidown](https://cloud.r-project.org/package=minidown).  

The reverse suggests on that package lists a few packages using minidown, most or all are mine.  The fonts are much crisper and the file size can be drastically larger.  

And importantly it looks crisper.  On Chrome, when I look at our CRAN vignette I see 

![image](https://user-images.githubusercontent.com/673121/115026670-63adaf80-9e88-11eb-9645-75a650316446.png)

(which almost looks better in the screenshot than rendered in the browser, weird) where if I switch to minidown and turn a floating table of content on I get 

![image](https://user-images.githubusercontent.com/673121/115026864-9c4d8900-9e88-11eb-8c32-055c6d5dbbc2.png)

If you are ok with it I will make that change too.

**Comment by johnlaing** [comment]
No objections here

**Comment by johnlaing** [comment]
Do we need to add `minidown` to Suggests?
