### ISSUE TITLE
Update headers

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#33]
With the helper script to fetch the (Linux) tar.gz I'll update the headers as well.  

Wonder if we could/should/... automate that.  I presume nobody got bitten yet?

**Comment by armstrtw** [comment]
That would be nice.

Along the same lines, I've wondered for a while whether it is possible to ship the shared libs w/ the package.  Something we've touched on a while back on the mail list.

**Comment by eddelbuettel** [comment]
I did one test just trying to keep the lib in `src/`; that builds with `-L.` but fails to load.

But I just realized a possible alternative.  We can use `rpath` to encode the path.  At least on Linux.  Not sure about OS X.

**Comment by eddelbuettel** [comment]
Seems possible: http://stackoverflow.com/questions/4513799/how-to-set-the-runtime-path-rpath-of-an-executable-with-gcc-under-mac-osx

**Comment by eddelbuettel** [comment]
> Along the same lines, I've wondered for a while whether it is possible to ship the shared libs w/ the package. Something we've touched on a while back on the mail list.

I looked into this, and do not think this is an option.

I'll still look into updating the headers.

**Comment by eddelbuettel** [comment]
Correction. I can make it work.

`R CMD check` still complains about shipping with binaries / libraries.

**Comment by armstrtw** [comment]
I can't imagine CRAN being too thrilled about that, so perhaps best to leave it for the user to install for now.  Thoughts?

**Comment by eddelbuettel** [comment]
I have a working setup.  We include a tar.gz and extract the library we need from configure.

That at least makes it self-contained. and makes it match library and headers.

**Comment by eddelbuettel** [comment]
I just sent you a PR.  I suggest you do NOT immediately merge it but maybe check out the branch, build and test the package and we then take it from there.

It would easy to extend this ... and just shipt the _unmodified_ tarball from Bloomberg.  I cannot see them objecting to that.   Whether the official R repos would ever take this is an entirely different story...

**Comment by eddelbuettel** [comment]
This can be closed too as we now embed the headers.
