### ISSUE TITLE
Switch unit tests to tinytest

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#330]
One last change I am suggesting we should do (but which like #329 isn't "required") is to switch from [RUnit](http://cloud.r-project.org/package=RUnit) to [tinytest](http://cloud.r-project.org/package=tinytest). I have done so for all my packages, and the change is very beneficial.  Test scripts really are scripts, you can test (easily) while developing, test the installed package (more easily, RUnit allows it too).   The momentum is clearly with [tinytest](http://cloud.r-project.org/package=tinytest) and the conversion tends to be quick.  Let me know what you think.

**Comment by johnlaing** [comment]
No objections here, either
