### ISSUE TITLE
Installation does not complete

### ISSUE THREAD

**Issue by rjindal9** [Rblp/Rblpapi#341]
The installation stops/ freezes after a point mentioned below: 

Installing package into �\\adl-fp01/My Docs/rahul.jindal/R/win-library/4.0�
(as �lib� is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/drat_0.2.0.zip'
Content type 'application/zip' length 211289 bytes (206 KB)
downloaded 206 KB

package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\rahul.jindal.SFMC\AppData\Local\Temp\RtmpgD6U2o\downloaded_packages
Installing package into �\\adl-fp01/My Docs/rahul.jindal/R/win-library/4.0�
(as �lib� is unspecified)
also installing the dependency �BH�

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/BH_1.75.0-0.zip'
Content type 'application/zip' length 19674958 bytes (18.8 MB)
downloaded 18.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/Rblpapi_0.3.11.zip'
Content type 'application/zip' length 4293457 bytes (4.1 MB)
downloaded 4.1 MB

**Comment by johnlaing** [comment]
I don't see an error here, nor do I see your invocation of the install command. Have you pasted the entire console? Also, are you able to install other packages?

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up.
