### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#355]
Any objections to rolling the recent fix and merge up to CRAN now that CRAN is open for business?

Maybe one more round of testing by those who can?  Remember to set `RunRblpapiUnitTests` to `yes` as well as `options(blpUnitTests=TRUE)`.

**Comment by johnlaing** [comment]
Yes, certainly another round of testing - will try to do that myself. Anything else that needs cleaning up before we release?

**Comment by eddelbuettel** [comment]
Don't think so as the delta was small and essentially just a partial cleanup hitting that one aspect.  But no rush -- if you can test today or tomorrow it would probably make us all feel even better :)

**Comment by mtkerbeR** [comment]
Running unit tests and examples, I noticed that the examples for function `bsrch`, e.g. `bsrch("COMDTY:NGFLOW")`, result in a `data frame with 0 columns and 0 rows` on my machine.

Using `verbose = TRUE`, I get:

```
library(Rblpapi)
blpConnect()
bsrch("COMDTY:NGFLOW", verbose=TRUE)
#> Sending Request: ExcelGetGridRequest = { Domain = "COMDTY:NGFLOW" }
#> Processing Response
#> GridResponse = {
#>     NumOfFields = 0
#>     NumOfRecords = 0
#>     ColumnTitles[] = {
#>     }
#>     DataRecords[] = {
#>     }
#>     ReachMax = false
#>     Error = "The domain entered: COMDTY:NGFLOW is not valid."
#>     SequenceNumber = 0
#> }
#> 0 records returned
#> Returned columns:
#> ColumnTitles[] = {
#> }
#> Columns converted to C++ vector
#> 0 Rows expected
#> Dataframe mit 0 Spalten und 0 Zeilen
```

Digging a bit deeper, I got the a similar error (#N/A Domain not Authorized) in Excel (although this exact example is still contained within the documentation of BBGs Excel-Addin). The person I spoke to at the Bloomberg helpdesk did also got an error message.

However, the function itself seems to be working properly, e.g. for a user-defined bond search. If helpful, I convert this to a unit test, in case others experience the same behaviour.

**Comment by eddelbuettel** [comment]
Looks like working symbol now went missing?   

If so a (working ;-) ) update in a PR would be great!

**Comment by mtkerbeR** [comment]
After some research on this, it seems that there are two main domains used for function `bsrch`:

1. COMDTY: 
All examples I found in this category (i.e. `bsrch("COMDTY:Weather")` and `bsrch("COMDTY:SHIP")`) need additional parameters. According to Bloomberg Excel Example Sheet: "BSRCH allows you to download vessel data dynamically. Searches can be constructed by selecting parameters for the INPUT and OUTPUT preceded by `COMDTY:SHIP`".
But additional parameters are currently not implemented for function `Rblpapi::bsrch`.

2. FI:
According to Bloomberg Excel Help: "You can use BSRCH to import the results of a **saved search** from the Fixed Income Search (SRCH) function, so you can analyze the list of bonds or loans in Excel." 

Hence a solution could be to have:

- a unit-test using an option, e.g. `rblpapi_test_srch` defined by the user running the unit tests
- no examples for function `bsrch` as the name is user-specific (analogous to function `getPortfolio`)
- maybe add a sentence how to construct fixed income searches (as this seems to be the main use-case now)?

**Comment by eddelbuettel** [comment]
Nice digging!  

I think two and three are appealing as tests (fundamentally) need a 'robot and no input' mode.   We can deal with this now, or relay it to the next release -- I am fine either way.  

@johnlaing @armstrtw : Any takes?

**Comment by eddelbuettel** [comment]
So with #356 by @johnlaing in here now, green light for rolling up a release?  Anything else missing that I am forgetting?

**Comment by johnlaing** [comment]
All clear from me.

**Comment by eddelbuettel** [comment]
I sent it on its way.   Because [CRAN shows NOTEs / WARNINGs / one ERROR](https://cloud.r-project.org/web/checks/check_results_Rblpapi.html) it got auto-rejected to which I replied so the submission now waits for someone at CRAN to look at it.    I am sure we will hear in a day or two.

**Comment by eddelbuettel** [comment]
And now at CRAN as there is often a late Sunday evening (European time) sweep over packages.
