### ISSUE TITLE
bdh issue with dates

### ISSUE THREAD

**Issue by andrewbenito** [Rblp/Rblpapi#359]
Issue: Using the bdh function to download monthly Economic data with Rblpapi generates a dataframe with end of month dates, not the actual dates the data were published. 
Question(s): How do I get the actual date when the Econ data release was published? Is it addressed in an Option or Override? Thank you.

Example below.

![image](https://user-images.githubusercontent.com/9501301/152160996-3ea13efa-36e9-43a9-a83e-044671858784.png)

**Comment by eddelbuettel** [comment]
Nit:  Let's please not post images here.  GitHun has _excellent_ markdown rendering for code. Use ` ` ` r (minus the spaces) to open an R block.

Nit:  Your example is not minimal. Drop tidyverse, drop lubridate as `as.Date()` is of course a base R function.

Nit:  We do not see the bottom of your example.

I have the vague feeling I once had this issue.  We often want vintages with data and ideally both "when published _at_" and "what period publish _for_".  But I don't recall.  Did you try Bloomberg Help?

**Comment by mtkerbeR** [comment]
Is this the result you are looking for:

```
library(Rblpapi)
blpConnect()
bdh("UKCCI Index", c("ECO_RELEASE_DT", "ACTUAL_RELEASE"), Sys.Date()-100)
#>         date ECO_RELEASE_DT ACTUAL_RELEASE
#> 1 2021-10-31     2021-10-21            -17
#> 2 2021-11-30     2021-11-18            -14
#> 3 2021-12-31     2021-12-16            -15
#> 4 2022-01-31     2022-01-20            -19
```

**Comment by andrewbenito** [comment]
That's it. Thank you.
