### ISSUE TITLE
Cannot install with Newer version of R, 4.2.1

### ISSUE THREAD

**Issue by JGLEEJG2** [Rblp/Rblpapi#370]
It was working up to 4.1.3 version of R.
No longer working with 4.2.1 version of R>

**Comment by JGLEEJG2** [comment]
![image](https://user-images.githubusercontent.com/96557576/186921061-718db84a-a044-4aa8-8eb1-f62d9e0ef0ab.png)

**Comment by JGLEEJG2** [comment]
Cannot install package with new version of R e.g. 4.2.1

**Comment by eddelbuettel** [comment]
You are using the wrong command.  Just do `install.packages("Rblpapi")` and install from CRAN.  It is clearly there as you can see at the [standard package page](https://cran.r-project.org/package=Rblpapi) including in three windows builds.

**Comment by JGLEEJG2** [comment]
Thx.  It is now installed
