### ISSUE TITLE
Could I get a Pay Index through Rblpapi?

### ISSUE THREAD

**Issue by Raymond-KT** [Rblp/Rblpapi#380]
Hi, I'm using  Rblpapi well. Thank you very much!!
It's beneficial for me!!

I wonder if I can get Pay Index information from CEOs of many companies through Rblpapi.

thanks.

**Comment by johnlaing** [comment]
We are just a wrapper around the API that Bloomberg provides. Do you know if this information is available in Bloomberg generally? Are you able to pull it from another API client, e.g. Excel? Start there and if there are tweaks necessary for Rblpapi we can try to help.

**Comment by Raymond-KT** [comment]
Thank you for your kind reply. 
Unfortunately, Bloomberg only provides captured image files like the one below. 

Could I have other solutions to get excel data through Rblpapi? 

![image](https://user-images.githubusercontent.com/51352487/212003639-3494e0c3-8718-4289-b610-d02e520a19d6.png)

thanks.

**Comment by klin333** [comment]
Have you used Helpdesk before in Bloomberg (click F1 Help twice)? Questions such as what you are asking ("how to get this Bloomberg screen into Excel API"), you should Bloomberg Helpdesk - it's their full-time job: your firm pays big money so you can have this service. 

Once you get a response from Bloomberg on how to do that in Excel, eg a bdp formula, then perhaps you would have worked it out yourself on how to use this package to achieve it, or perhaps someone on this project can help you then.

**Comment by eddelbuettel** [comment]
I think we should close this now.
