### ISSUE TITLE
documenting valid periodicitySelection options, semiannual not supported

### ISSUE THREAD

**Issue by groditi** [Rblp/Rblpapi#383]
the BDH documentation states that valid base periods are:

> The base periods are:
> - D: Daily
> - W: Weekly
> - M: Monthly
> - Q: Quarterly
> - S: Semi-annually
> - Y: Yearly

I can get DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY to work, but there seems to be no option for semi-annually. Additionally, it would be nice if the periodicity selections were documented.

**Comment by eddelbuettel** [comment]
We basically provide accessor to the C++ API offered by Bloomberg.  If we wrote those down they like are / were supported by the API.

Also, sometimes different access 'options' and values vary by symbol or ticker.  So maybe best to first check with the help desk at Bloomberg to see what constitutes a valid query?

**Comment by johnlaing** [comment]
Do you have a specific example? I can try to help troubleshoot.

**Comment by johnlaing** [comment]
In the Bloomberg API dev guide (most recent I see is https://data.bloomberglp.com/professional/sites/10/2017/03/BLPAPI-Core-Developer-Guide.pdf) the BDH documentation indicates a value of `SEMI_ANNUALLY`, which does work for me.

I'm unsure where you're quoting from in the initial issue - I don't see that we've documented these values. But if I'm missing something and we've written it down wrong I'd be happy to fix.
