### ISSUE TITLE
Page Data Service

### ISSUE THREAD

**Issue by lllnnnlll** [Rblp/Rblpapi#384]
Hi I am trying to find out if we are able to retrieve bbg page data using this package.  This would be the blp/pagedata service in the api or BPGE() function in excel.  I don't currently see any direct reference to page data within the docs but perhaps its a subset of one of the other functions.  Thanks!

**Comment by eddelbuettel** [comment]
You need to examine the documentation of the [API we use](https://www.bloomberg.com/professional/support/api-library/), namely the C++ API.  Not everything available via Excel is mapped.

See numerous [closed issues here](https://github.com/Rblp/Rblpapi/issues?q=is%3Aissue+is%3Aclosed) discussing that.

**Comment by lllnnnlll** [comment]
Thanks so much for your reply.  This functionality is on page 49-50 of the core developer guide per your link.  would you be able to tell me if its currently mapped or wrapped under another function

**Comment by eddelbuettel** [comment]
I am a wee bit removed from the code these days but you should be to able to tell this quickly by searching the code here at GitHub (!!) where search defaults first to wthin the repom and / or via `grep` if you have the sources unpacked.

We welcome contributions. If you are handy with the C(++) language(s) please consider crafting a pull request.

**Comment by lllnnnlll** [comment]
ty for the tip, i searched and the exact service is not mapped
