### ISSUE TITLE
Testing Release "feature/release_3.24.6.1"

### ISSUE THREAD

**Issue by mtkerbeR** [Rblp/Rblpapi#393]
As ask for by Dirk and John in [R-SIG-Finance](https://stat.ethz.ch/pipermail/r-sig-finance/2024q3/015197.html), I tested the new version.

Using suggested command `remotes::install_github("Rblp/Rblpapi", ref="feature/release_3.24.6.1")`, I get:

```
> library(Rblpapi)
Rblpapi version 0.3.14.1 using Blpapi headers 3.8.18.1 and run-time 3.8.18.1.
Please respect the Bloomberg licensing agreement and terms of service.
```

Digging a bit deeper, it seems that file `src/Makevars.win` has to be adjusted in lines 46/47 to curl files from the adjusted location (i.e. temporarily replacing `master` by `feature/release_3.24.6.1`).

This results for me in:

```
Rblpapi version 0.3.14.1 using Blpapi headers 3.24.6.0 and run-time 3.24.6.1.
Please respect the Bloomberg licensing agreement and terms of service.
```

It remains unclear why the version number of headers does not end in `.1` (as suggested in R-SIG-Finance), but the number in the output agrees with `inst/include/blpapi_versionmacros.h`:

```
#define BLPAPI_VERSION_MAJOR 3
#define BLPAPI_VERSION_MINOR 24
#define BLPAPI_VERSION_PATCH 6
#define BLPAPI_VERSION_BUILD 0
```

**Comment by mtkerbeR** [comment]
Unit tests are passing, apart from the one error below. 
Will probably have a look at it later on or in the next days - but would be nice if someone could confirm it is also not working for them, hence unrelated to my installation/computer:

```
> bds("DAX Index", "INDX_MEMBERS")
Error: Cannot convert to String type.
3. stop(structure(list(message = "Cannot convert to String type.", call = NULL, cppstack = NULL), class = c("BloombergLP::blpapi::InvalidConversionException","C++Error", "error", "condition")))
2. bds_Impl(con, security, field, options, overrides, verbose, identity) at bds.R#63
1. bds("DAX Index", "INDX_MEMBERS")
```

**Comment by eddelbuettel** [comment]
> It remains unclear why the version number of headers does not end in .1 (as suggested in R-SIG-Finance), 

That comes from the files included.  For the different architectures we created different 'library' and 'header' archives off different input files

```sh
edd@rob:~/git/blp(feature/release_3.24.6.1)$ ls -l 2024-08/
total 51292
-rw-rw-r-- 1 edd edd 21258132 Jul 24 08:15 blpapi_cpp_3.24.6.1-linux.tar.gz
-rw-rw-r-- 1 edd edd  9672382 Jul 24 08:15 blpapi_cpp_3.24.6.1-macos-arm64.tar.gz
-rw-rw-r-- 1 edd edd 21576622 Jul 24 08:15 blpapi_cpp_3.24.6.1-windows.zip
edd@rob:~/git/blp(feature/release_3.24.6.1)$ 
```

so I suspect that is the actual upstream number.  They sometimes differ, and that is why we print both.

> seems that file src/Makevars.win has to be adjusted

I will take care of that too.

> `> bds("DAX Index", "INDX_MEMBERS")`

I had found that sometimes the 'yellow key' fields needed adjustment. Does that query work with the current (old) version?  Does running in `verbose=TRUE` reveal more?  Does `bds("GOOG US Equity", "TOP_20_HOLDERS_PUBLIC_FILINGS")` work?

Thanks for running the tests!

**Comment by eddelbuettel** [comment]
I did adjust `Makevars.win` already (in order to build a test binary via win-builder) but never pushed it :-/  My bad.  Try now.  I also had [win-builder do another round](https://win-builder.r-project.org/T7Vy9Kn42TwF/) (link should be good for 48 to 72 hours).

**Comment by mtkerbeR** [comment]
Thanks for updating `Makevars.win`. I tried again - succesful:

```
> remotes::install_github("Rblp/Rblpapi", ref="feature/release_3.24.6.1")
> library(Rblpapi)
Rblpapi version 0.3.14.1 using Blpapi headers 3.24.6.0 and run-time 3.24.6.1.
Please respect the Bloomberg licensing agreement and terms of service.

```

**Comment by eddelbuettel** [comment]
No, thank you for catching that and not running the tests with old build!

If you can poke around `bds()` a little if we need to update that one test where DAX components are retrieved I'd appreciate.  There are a few other `bds()` example invocations in the help page and unit test files.

**Comment by mtkerbeR** [comment]
Regarding your first questions:

Yes - the query `bds("DAX Index", "INDX_MEMBERS")` is working in the old version.
No - using `verbose=TRUE` does not reveal more.
No - `bds("GOOG US Equity", "TOP_20_HOLDERS_PUBLIC_FILINGS")` does not work (no any of the other queries I tried)

However, I think the problem can be localized around line 264 of `bds.cpp`. 
Adding a couple of `Rcpp::Rcout`-statements ...

```
Rcpp::Rcout<<"point 1"<<std::endl;
    Service refDataService = session->getService(rdsrv.c_str());
    Request request = refDataService.createRequest("ReferenceDataRequest");
Rcpp::Rcout<<"point 2"<<std::endl;
Rcpp::Rcout<<securities.size()<<std::endl;
Rcpp::Rcout<<request.getElement(Name{"securities"})<<std::endl;
Rcpp::Rcout<<securities[0].c_str()<<std::endl;        
Rcpp::Rcout<<Name{securities[0].c_str()}<<std::endl;

    for (size_t i = 0; i < securities.size(); i++) {
        request.getElement(Name{"securities"}).appendValue(Name{securities[i].c_str()});
    }
Rcpp::Rcout<<"point 3"<<std::endl;
```
... results in:

```
> bds("DAX Index", "INDX_MWEIGHT")
point 1
point 2
1
securities[] = { }
DAX Index
DAX Index

Error: Cannot convert to String type.
3. stop(structure(list(message = "Cannot convert to String type.", call = NULL, cppstack = NULL), class = c("BloombergLP::blpapi::InvalidConversionException","C++Error", "error", "condition")))
2. bds_Impl(con, security, field, options, overrides, verbose, identity) at bds.R#63
1. bds("DAX Index", "INDX_MEMBERS")
```
Does it give you a hint what the problem could be?

**Comment by eddelbuettel** [comment]
Not that is a little sparse still.  What I have done in the past is poked around the examples in the tarball provided by Bloomberg -- you would need the Windows version from [here](https://www.bloomberg.com/professional/support/api-library/) ie this [file](https://blpapi.bloomberg.com/download/releases/raw/files/blpapi_cpp_3.24.6.1-windows.zip) and then poke around the  `demoapps/` directory.

Very worst case `bds()` is now defunct, better case we find a tweak...

**Comment by mtkerbeR** [comment]
One way could be to revert the changes recently done at this location in #391 and stick with the former code:

```
   for (size_t i = 0; i < securities.size(); i++) {
        request.getElement("securities").appendValue(securities[i].c_str());
        // request.getElement(Name{"securities"}).appendValue(Name{securities[i].c_str()});
    }

    request.getElement("fields").appendValue(field.c_str());
    // request.getElement(Name{"fields"}).appendValue(Name{field.c_str()});
```

Which seems to give the expected results:
```
> blpConnect()
> head(bds("DAX Index", "INDX_MWEIGHT"))
point 1
  Member Ticker and Exchange Code Percentage Weight
1                         1COV GY          0.766000
2                          ADS GY          2.822253
3                          AIR GY          5.975904
4                          ALV GY          8.049776
5                          BAS GY          2.993752
6                         BAYN GY          2.002698

```

What do you think?

**Comment by eddelbuettel** [comment]
Oh nice.  I think we probably want at least the first `Name{}` in `getElement()` or else it will likely yell at us for 'deprecation'.  But it looks like you spotted an bug I (overzealously !) introduced.  If I change to (and let's report as `diff` where we can

```diff
modified   src/bds.cpp
@@ -266,7 +266,7 @@ Rcpp::List bds_Impl(SEXP con_, std::vector<std::string> securities,
     Service refDataService = session->getService(rdsrv.c_str());
     Request request = refDataService.createRequest("ReferenceDataRequest");
     for (size_t i = 0; i < securities.size(); i++) {
-        request.getElement(Name{"securities"}).appendValue(Name{securities[i].c_str()});
+        request.getElement(Name{"securities"}).appendValue(securities[i].c_str());
     }
     request.getElement(Name{"fields"}).appendValue(Name{field.c_str()});
     appendOptionsToRequest(request,options_);
```

then it still compiles without warning (yet it would issue a warning if omitted the `Name{}` around `"securities"`).

**Comment by mtkerbeR** [comment]
You are right.
Omitting `Name{}` within `appendValue()` and keeping it in `getElement()` in lines 269 and 271 gives the correct results for `bds()` and does not lead to a warning.

**Comment by eddelbuettel** [comment]
And all tests pass?  Yay!!

**Comment by mtkerbeR** [comment]
```
> Sys.setenv("RunRblpapiUnitTests" = "yes")
> tinytest::run_test_dir()
test_bdh.R....................   25 tests OK 8.7s
test_bdp.R....................    7 tests OK 2.5s
test_bds.R....................    6 tests OK 0.8s
test_examples.R...............    1 tests OK 45ms
test_getBars.R................    8 tests OK 0.7s
test_getTicks.R...............   12 tests OK 43.5s
All ok, 59 results (56.2s)
```

**Comment by eddelbuettel** [comment]
I made one further generalisation:
- the `blp` repo now distinguishes 64-bit macOS between x86_64 (using the eight year old library that still works) and arm64 (using the new one)
- the `configure` script in `Rblpapi` here has been adjusted, this passes in GitHub Actions for macOS on arm64
- I also configure 'my' r-universe setup to build `Rblpapi` off this feature/release_3.24.6.1 branch and it [looks good](https://eddelbuettel.r-universe.dev/Rblpapi) on all platforms:

![image](https://github.com/user-attachments/assets/b5b8630a-6d41-4522-850f-e0ed0a73909e)

**Comment by bobjansen** [comment]
On 
```

> R.version
               _                                
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          3.2                              
year           2023                             
month          10                               
day            31                               
svn rev        85441                            
language       R                                
version.string R version 4.3.2 (2023-10-31 ucrt)
nickname       Eye Holes   
```
I have the all OK from `tinytest::run_test_dir()`.

```
> library(Rblpapi)
Rblpapi version 0.3.14.1 using Blpapi headers 3.24.6.0 and run-time 3.24.6.1.
Please respect the Bloomberg licensing agreement and terms of service.
> system("git rev-parse HEAD")
890fb5f663c3b14e36134bfd8c6ef0cbf0bf3e47
```

**Comment by eddelbuettel** [comment]
Thank you @bobjansen that is _really_ appreciated!  We will probably cut a release in a few days.

**Comment by eddelbuettel** [comment]
The testing is really appreciated but as it has moved to a 'release candidate' in the main branch I am going to close this.  With a big thank you to everybody who helped us get this via the dual feature branches in repo blp and here.  The next release should be coming next week.
