### ISSUE TITLE
Expected speed difference from Rbbg to Rblpapi?

### ISSUE THREAD

**Issue by n-e-w** [Rblp/Rblpapi#44]
@eddelbuettel @johnlaing @armstrtw  - first of all, excellent work on this package; think this is absolutely the way forward. I'm looking forward to making some pull requests in the future.

Quick question. Did you expect an increase in speed from `Rbbg` to `Rblpapi`?

This may well not be what you're aiming for, so please ignore the following if that's the case. I just wanted to give it a test before switching over and changing a fair bit of embedded code. 

Using:

* Desktop API
* Win 8.1 VM
* Latest RStudio prod release

***Tl;dr***: Appears (at least on this setup) that `Rbbg` is quicker.

Ran the following "head to head" tests in two separate R instances in a Win VM

```r

# Java Session Info

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Rbbg_0.5.3                    rJava_0.9-6                   quantstrat_0.9.1657           foreach_1.4.2                
 [5] blotter_0.9.1666              PerformanceAnalytics_1.4.3541 FinancialInstrument_1.2.0     quantmod_0.4-4               
 [9] TTR_0.22-0                    xts_0.9-7                     zoo_1.7-11                   

loaded via a namespace (and not attached):
[1] codetools_0.2-11 grid_3.1.2       iterators_1.0.7  lattice_0.20-30  tools_3.1.2   

```

and

```r

# C++ Session Info

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Rblpapi_0.2.2.5               quantstrat_0.9.1657           foreach_1.4.2                 blotter_0.9.1666             
 [5] PerformanceAnalytics_1.4.3541 FinancialInstrument_1.2.0     quantmod_0.4-4                TTR_0.22-0                   
 [9] xts_0.9-7                     zoo_1.7-11                    RQuantLib_0.4.0              

loaded via a namespace (and not attached):
[1] codetools_0.2-11 grid_3.1.2       iterators_1.0.7  lattice_0.20-30  Rcpp_0.11.5      tools_3.1.2   


```

##### Test 1(a): Single Symbol BDH call using Rbbg. SPY US from 2001 and YTD

```r

# 2001 to Present

> system.time(
    bdh(conn,
           "SPY US Equity",
           c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"),
           as.POSIXct("2001-01-01)"),
           Sys.Date()))

   user  system elapsed 
   0.15    0.00    4.18 

# 2015 YTD

> system.time(
    bdh(conn,
           "SPY US Equity",
           c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"),
           as.POSIXct("2015-01-01)"),
           Sys.Date()))

   user  system elapsed 
   0.05    0.00    0.30     
```

##### Test 1(b): Single Symbol BDH Call using Rblpapi. SPY US from 2001 and YTD

```r

# 2001 to Present

> system.time(bdh(securities = "SPY US Equity", fields = c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"), start.date =as.Date("2001-01-01"),end.date = Sys.Date()))

   user  system elapsed 
   0.02    0.01    5.22 

# 2015 YTD

> system.time(bdh(securities = "SPY US Equity", fields = c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"), start.date =as.Date("2015-01-01"),end.date = Sys.Date()))
   
user  system elapsed 
   0.00    0.00    2.23 
```

Surprisingly `Rbbg` was much quicker on the YTD symbol pull.

So the next test was to pull 8 equity symbols and see if the difference was as pronounced

##### Test 2(a):Eight Symbol BDH Call using Rbbg. 2001 and YTD

```r

# 2001 to present

> system.time(
    bdh(conn,
    x,
    c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"),
    as.POSIXct("2001-01-01)"),
    Sys.Date()))
   

user  system elapsed 
   1.34    0.08   11.05

# 2015 YTD
 
> system.time(
    bdh(conn,
    x,
    c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"),
    as.POSIXct("2015-01-01)"),
    Sys.Date()))

 user  system elapsed 
   0.27    0.00    2.61 
```

##### Test 2(b):Eight Symbol BDH Call using Rblpapi. 2001 and YTD

```r

# 2001 to present

> system.time(
    bdh(securities = x,
    fields = c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"),
    start.date =as.Date("2001-01-01"),
    end.date = Sys.Date()))
   
user  system elapsed 
   0.16    0.01   20.31

# 2015 YTD

> system.time(
    bdh(securities = x,
    fields = c("OPEN", "HIGH", "LOW", "PX_LAST", "VOLUME"),
    start.date =as.Date("2015-01-01"),
    end.date = Sys.Date()))

   user  system elapsed 
   0.00    0.00    1.15  

```

In this case `Rbbg` ***was nearly twice as fast pulling 14.5 years of 8 equity symbols from the API*** -- but `Rblpapi` was quicker on the YTD.

This could all be my VM setup or the way I ran these casual tests....but, otherwise, is this surprising?

**Comment by n-e-w** [comment]
Done some further digging... I can see that output from `Rblpapi` is much more highly processed and in a more readily usable format than from `Rbbg`. 

Will see if once wrappers are applied to convert both outputs to `xts` whether there's a difference net of the raw data post-processing.

Watch this space.

**Comment by n-e-w** [comment]
**Update:** I cracked out Hadley's `lineprof` package. I ran it against a script  I rolled for both `Rbbg` and `Rblpapi` that takes their respective raw outputs for a single symbol OHLCV request, converts them to `xts` and assigns them to the `.GlobalEnv`.

In short, `Rbbg` pulls the same single symbol, 14.5 year OHLCV data about a half second quicker than `Rblpapi`. 

But `Rbbg` (appears) to be much more of a memory hog than `Rblpapi`. `Rbbgapi` also seems to make thousands of duplicate vectors while `Rblpapi` makes none (as Hadley explains: *** A vector duplication occurs when R copies a vector as a result of its copy on modify semantics.***). 

This could be due to more going on under the hood with the C++ implementation that's invisible to `lineprof()` ...but I wouldn't know.

What I will say is that ***not having to post-process the `bdh` output as much makes for a much cleaner,faster experience when you have multiple symbols to download***. In this case, I was able to  get 5 symbols of 15 years of daily OHLCV converted to xts and into the environment for interactive use twice as quick with `Rblpapi`....and it seems to always be about twice as quick for any arbitrary number of symbols.

Hope this helps. Keen to hear how others mileage varies.

**Comment by eddelbuettel** [comment]
I do not think we say anywhere that _speed_ is a design goal.

Collecting an unknown number of rows and an unknown number of columns is ... difficult.  So there is some code at the heart of `bdh` which we may, or may not, revise, time permitting.   We intend to, but as it currently works it is not of the highest priority.

**Comment by n-e-w** [comment]
Totally understood. Thanks for responding.

I think the new implementation works much better net of 'typical' xts based workflows using multiple symbols. 

Again, great work all around, team.

**Comment by johnlaing** [comment]
I'll echo Dirk's comment that speed is not a design goal. But I'll add that speed should be a natural byproduct of good design. I think benchmarking of this sort is very useful. If there are places where Rblpapi is falling noticeably behind, those might be places where we could look for improvements.

On another point you raise: the cost of "switching over and changing a fair bit of embedded code". We've tossed around the idea of a transition package which implements the interface of Rbbg with the guts of Rblpapi. The idea is that we could enable people to transition to the C++ version without the high upfront cost of cleaning up years of working code. I'd be interested to get your thoughts on this.

JL

**Comment by n-e-w** [comment]
I'm happy to help here.

I suppose a good model for the syntax 'UI' is mirroring what our dear 
friends at The LP have built for the Excel API. I think it would drive a 
non-trivial uptake in use of the package - especially for those quants 
looking to make the jump from VBA. I know this because I wrote a ton of 
wrappers around Rbbg with precisely this syntactic sugar in mind. But, 
on the other hand, making things 'easy' for people may not be desired 
either.

I have no view on these things -- but if I can contribute in some small 
way, I'd be glad to.

n

**Comment by armstrtw** [comment]
Again, to echo the what others have said.  The objective is not speed.  The objective is to drop the Java dependency.

-Whit

https://gist.github.com/armstrtw/b1ff06f02642eda66c3d

also note that Rbbg returns all securities in a single dataframe, whereas Rblpapi returns a list.  So, Rbbg is actually doing more work, to rbind all that data into a single frame.

on a linux machine.  (not a vm)
output:
warmstrong@krypton:~$ Rscript dvl/scripts/test/bbg.test.R 
Loading required package: rJava
Loading required package: methods
R version 3.2.0 (2015-04-16) 
rJava Version 0.9-6 
Rbbg Version 0.6.1 
Java environment initialized successfully.
Adding /opt/vendor/blpapi_java_3.8.7.2/bin/blpapi-3.8.7-2.jar to Java classpath
Bloomberg API Version 3.8.7.2 
             user.self sys.self elapsed user.child sys.child
Rblpapi.time     0.060    0.004   1.718          0         0
Rbbg.time        2.584    0.040   2.550          0         0

**Comment by eddelbuettel** [comment]
Closing this now.  

If there is an issue, a _small_ and _self-contained_ and _reproducible_ example would be helpful.
