### ISSUE TITLE
Overrides for getTicks

### ISSUE THREAD

**Issue by forkandspoon** [Rblp/Rblpapi#45]
Firstly thanks for the initiative in supporting R and Bloomberg.

`getTicks` - is it possible to add the quote type (similar to verbose mode e.g. `TRADE`, `BEST_BID`) and the option to enable condition codes, similar to the Excel `condcodes = S` and `QRM = S`

I believe the following needs to be set:
`request.Set("includeConditionCodes", true); // Excel eqv. CondCodes = S`
`request.Set("includeNonPlottableEvents", true); // Excel eqv. QRM = S`

My C++ experience is quite limited, but in the meantime I have forked this project and will have a good go at this myself.

Thank you,
JD

**Comment by eddelbuettel** [comment]
:+1: for forking and trying.   The [Bloomberg API documentation](http://www.bloomberglabs.com/api/documentation/) is pretty good --- but lacks use cases or best practices.  So we need to iterate, add examples, expand use cases, ...

**Comment by forkandspoon** [comment]
I've forked and expanded getTicks w/condition codes and multiple event types (i.e. `c("TRADE", "BEST_BID"`). Spot checked with a few securities and appears to be working.

**Comment by eddelbuettel** [comment]
Yes, 28 commits is a lot.  Mayne you can 'squash' these before creating a pull request?
