### ISSUE TITLE
Error: External pointer is NULL.

### ISSUE THREAD

**Issue by RockScience** [Rblp/Rblpapi#50]
I have installed the Rblpapi package on Windows using 

    install.packages("drat", repos="http://cran.rstudio.com")
    drat:::add("ghrr")
    install.packages("Rblpapi")
    bdh("SPY US Equity", c("PX_LAST", "VOLUME"), start.date=Sys.Date()-31)

Installation was successful, however I get the following error: Error: External pointer is NULL.

is it because I need to set the path to the blpapi dll?

**Comment by RockScience** [comment]
ok just need to connect first using 

   con <- blpConnect()

**Comment by eddelbuettel** [comment]
Point taken.  I'll add code that will check `con` for `NULL` and tell you to connect first.
