### ISSUE TITLE
Portfolio Data Request

### ISSUE THREAD

**Issue by gold5201** [Rblp/Rblpapi#62]
The Portfolio Data Request enables retrieval of change information and portfolio positions with respect to a specific date in order to see how current market movements have affected user's portfolio's constituent weights.

**Comment by quantrisktrading** [comment]
If either of these requests is not currently in the development pipeline, I would be happy to help.

**Comment by eddelbuettel** [comment]
Yes, you would have to take the lead on this.  That is what I trying to get at with the [mailing list reply](http://article.gmane.org/gmane.comp.lang.r.r-metrics/13369).

**Comment by wmorgan85** [comment]
This issue can be closed as support was added in [#176](https://github.com/Rblp/Rblpapi/pull/176)
