### ISSUE TITLE
BEQS (Bloomberg Equity Screening) Request

### ISSUE THREAD

**Issue by quantrisktrading** [Rblp/Rblpapi#63]
BEQS (Bloomberg Equity Screening) request returns security data for a selected
screen created using the Bloomberg EQS <GO> function.

**Comment by quantrisktrading** [comment]
If either of these requests is not currently in the development pipeline, I would be happy to help.

**Comment by eddelbuettel** [comment]
Yes, you would have to take the lead on this.  That is what I trying to get at with the [mailing list reply](http://article.gmane.org/gmane.comp.lang.r.r-metrics/13369).

**Comment by eddelbuettel** [comment]
There is some code [in this post to r-sig-finance](http://article.gmane.org/gmane.comp.lang.r.r-metrics/13370) so maybe someone can build on this.

**Comment by eddelbuettel** [comment]
This should be taken care now thanks to #79.
