### ISSUE TITLE
Alter build scripts to download-if-needed-only

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#65]
Currently the header and library tarballs are download on each build and invocation of configure. This could be smarter -- and only download when not present.  That would help for repeated builds from the source directory, ie `R CMD build .`.

**Comment by armstrtw** [comment]
that would be nice. I supposed we are impacted most by repeated builds as we develop.

**Comment by eddelbuettel** [comment]
And it shouldn't be much more `test -f some/file && exit`.  It hit when I was noodling through this ['false alert' thingie](http://quant.stackexchange.com/questions/19357/change-periodicity-on-rblpapi) I found more or less by chance...

**Comment by armstrtw** [comment]
So, should we work out a rough roadmap for our next release.

I'd really like to add support for live data subscriptions. which shouldn't bee too hard.

**Comment by eddelbuettel** [comment]
That discussion should probably be under another ticket number then ...

I also saw, belatedly, that r-sig-finance had a post with code snippets for the issue raised in two issue tickets about beds (or whatever it is called).

In short, we probably need a punch list...

**Comment by eddelbuettel** [comment]
Crap. Looking into this now but we have 'round hole / square peg' issue:
- I can cache the Blp tarballs in the source tree
- But by agreement with Vienna the .Rbuildignore will ignore them
- So the 'build and check' cycle via `R CMD build ...` and `R CMD check ...` will NOT see them.

**Comment by eddelbuettel** [comment]
So `R CMD INSTALL .` from the working directory works.  Good enough.
