### ISSUE TITLE
R: Rblpapi: use overrides to fetch ML data from Bloomberg

### ISSUE THREAD

**Issue by BastienLuc** [Rblp/Rblpapi#67]
Dear All!

I have recently started to work with the great and helpful Rblpapi package to fetch data directly from Bloomberg. However, I have one question that could not be answered by searching the internet. So now I am asking you kindly if you might help me out in this matter.

Wherease
data1 <- bdh("EN00 INDEX", c("PX_LAST"), start.date=Sys.Date()-365)
works perfectly fine, I have troubles when it comes to other data that is provided by Merryll Lynch and available via Bloomberg. Concretely, I need the MLI_OAS mli date=20150901(or other date) of the index "EN00 INDEX", or, even better, the whole time series for" MLI_OAS" instead of "PX_LAST". 

I have tried several attempts, but none of them did work. Such as
data1 <- bdh("EN00 INDEX", c("MLI_OAS"), start.date=Sys.Date()-365)
data2 <- bdp("EN00 INDEX", c("MLI_OAS"), MLI_Date=20150901)
data3 <- bdp("EN00 INDEX", c("MLI_OAS"),,"mli_date=20150901")
data4 <- bdp("EN00 INDEX", c("MLI_OAS"),,"mli date=20150901")
However, the only data point I can get is the most recent value (yesterday 09/14/2015: 123). I think I have to somehow name the override correctly. The error I get is "Request overrides must be named".
  

My question is how to address the override correctly. Is this even implemented in the package? Is it not possible, because it is Merryll Lynch data?

Thank you very much for your help.

**Comment by armstrtw** [comment]
We have not worked on overrides yet.

Have you been able to successfully run that override in excel?  If so, please post the formula here.

I'm looking at the series, and I don't see MLI_OAS as a valid field, but I don't know a way to list the overrides for a series...

Sometimes index providers publish the index stats under a separate ticker as is the case for JPM ELMI+.

**Comment by eddelbuettel** [comment]
I think we now have [one worked example](https://github.com/Rblp/Rblpapi/blob/master/man/bdh.Rd#L54-L59)  of using `options()` but not `overrides()` in `bdh()`.  That whole area needs work -- but we need community involvement.

Cheers from [EARL 2015](http://www.earl-conference.com/london/index.html) in London.

**Comment by johnlaing** [comment]
This is actually a `bdp` call, not a `bdh`:
```
> bdp("EN00 Index", "MLI_OAS", overrides=c(MLI_DATE="20150831"))
           MLI_OAS
EN00 Index     116

> bdp("EN00 Index", "MLI_OAS", overrides=c(MLI_DATE="20150731"))
           MLI_OAS
EN00 Index     109
```

**Comment by eddelbuettel** [comment]
Super -- so now we have an overrides example for `bdp()`.  Shall we add it to the manual page?

**Comment by BastienLuc** [comment]
Thanks everybody! 

@armstrtw the excel code works too, it's =blp(EN00 Index,mli date=yyyymmdd:MLI_OAS)

**Comment by morobro** [comment]
I have a somewhat similar question to the one above.  I'm trying to pull in historical consensus estimate data on revenues for 40 quarters. Bloomberg gave me the override codes (for Python since they don't support R), but I still have not managed to successfully implement it.  My code would be:  
opt<- c("periodicitySelection" = "QUARTERLY")
CONSENSUS<- (bdh(STOCK,"BEST_SALES", start.date = Sys.Date()-375*10, options=opt))
but that only pulls in 6 quarters and it does not match what you'd get on the Bberg terminal.
The overrides Bberg gave me are:
"best
fperiod
override=1GQ"

    overrides = request.getElement("overrides")
    override1 = overrides.appendElement()
    override1.setElement("fieldId", "BEST_FPERIOD_OVERRIDE")
    override1.setElement("value", "9:30")

In Excel, I code it as:  =BDH(STOCK,"BEST_SALES","-13FY","","best fperiod override=1GQ","per=Q","sort=TRUE","fill=p","days=a","cols=2;rows=55")  

I can't seem to get the overrides to work and am hoping someone much more experienced at this can help me out.  Thank you very much!

**Comment by morobro** [comment]
I figured it out:  CONSENSUS<- (bdh(STOCK,"BEST_SALES", start.date = Sys.Date()-375*10, options=opt, overrides=c("BEST_FPERIOD_OVERRIDE"="1GQ")))
Thanks.

**Comment by eddelbuettel** [comment]
Nice!

```r
R> opt <- c("periodicitySelection" = "QUARTERLY")
R> ovrd <- c("BEST_FPERIOD_OVERRIDE"="1GQ")
R> res <- bdh("IBM US Equity", "BEST_SALES", start.date=Sys.Date()-365*3, options=opt, overrides=ovrd)
R> res
         date BEST_SALES
1  2013-03-29    24704.7
2  2013-06-28    25395.2
3  2013-09-30    24762.3
4  2013-12-31    28209.6
5  2014-03-31    22923.2
6  2014-06-30    24125.4
7  2014-09-30    23410.9
8  2014-12-31    25014.7
9  2015-03-31    19884.6
10 2015-06-30    20916.2
11 2015-09-30    19668.8
12 2015-12-31    22147.4
R> 
```

I think I'll add that to the `bdh()` examples.

**Comment by morobro** [comment]
Hello Dirk,

This might be ancient news to you, but I just saw Bloomberg is advertising to hire an R programmer in SF to open up their API to R.

Sorry if that's old news.

Regards,

Monika

**Comment by eddelbuettel** [comment]
I sort of knew of team in SF related to 'all things API', I did not know they wanted to hire.  Good for R.  Too bad team Rblpapi is based in New York and Chicago ;-)

**Comment by PierreLequeux** [comment]
Hi I am trying to use BDP to retrieve FX forward points and the number of days  between the value date and the settlement date of the foirward maturity  (i.e tenor) as in tyeh following:

```
 bdp("AUD1M Curncy",c("PX_MID","DAYS_TO_MTY"))

             PX_MID DAYS_TO_MTY
AUD1M Curncy -4.535          32


```
 I would like is to use the  overrides feature (or any other way) to retrieve  a series of queries such that I get  an xts or time series object as per the below:
```

Date	PX_MID	DAYS_TO_MTY
17/04/2017	-4.48	30
18/04/2017	-4.75	32
19/04/2017	-4.22	31
20/04/2017	-4.155	30
21/04/2017	-4.27	30
24/04/2017	-4.605	33
25/04/2017	-4.555	33
26/04/2017	-4.51	33
27/04/2017	-4.177	31
28/04/2017	-4.193	31
01/05/2017	-4.505	33
02/05/2017	-4.35	32
03/05/2017	-4.15	31
04/05/2017	-4.21	31
05/05/2017	-4.257	31
08/05/2017	-4.71	34
09/05/2017	-4.93	33
10/05/2017	-4.8	        32
11/05/2017	-4.505	31
12/05/2017	-4.5	        31
15/05/2017	-4.855	33
16/05/2017	-4.548	32


```

this works in excel when i use the BDP formulas as per the below:

AUD1M Curncy		
Date	PX_MID	DAYS_TO_MTY
17/04/2017	-4.48	30
18/04/2017	-4.75	32

=BDP($A$1,$C$2,"Reference Date",TEXT(A3,"YYYYMMDD"))


but I can t seem to get it to work  in R....


Any help would be appreciated

Kidn regards

Pierre

**Comment by armstrtw** [comment]
you want to fetch days_to_mty with bdh, or you want to supply the override to bdp?

if you want the override, then just look at the help for bdp:
overrides: An optional named character vector with override values.
          Each field must have both a name (designating the override
          being set) as well as a value.

**Comment by armstrtw** [comment]
> bdh("JPY1M Curncy",c("PX_LAST","DAYS_TO_MTY"),start.date=Sys.Date()-10)
        date  PX_LAST DAYS_TO_MTY
1 2017-05-08 113.1378          NA
2 2017-05-09 113.8591          NA
3 2017-05-10 114.1623          NA
4 2017-05-11 113.7385          NA
5 2017-05-12 113.2540          NA
6 2017-05-15 113.6572          NA
7 2017-05-16 113.0740          NA
> bdp("JPY1M Curncy",c("PX_LAST","DAYS_TO_MTY"),overrides=c("Reference Date"="20170515"))
             PX_LAST DAYS_TO_MTY
JPY1M Curncy 113.084          33
>

**Comment by PierreLequeux** [comment]
Hi Whit, 

Thank you for the above  comments they are helpful.  I have been told by the chaps at  Bloomberg that apparently to get the tenors you need to use  BDP as you can't get the day runs directely  via BDH...i.e you need first to run a BDH and use the date index in your the BDP override...I was wondering if there was a convenient way to pass the whole index date in the overrides  in one go other coding it as a loop...something like a multiple  query  via BDS maybe?  


Kind regards

Pierre

**Comment by eranravivv** [comment]
Hi Dirk, is there any way to get transcript calls using the bdh function?

**Comment by eddelbuettel** [comment]
I don't know.
