### ISSUE TITLE
Is this the right way to call BDS with options?

### ISSUE THREAD

**Issue by nattynatty** [Rblp/Rblpapi#70]
For historical index data in excel for a given date, I use this 
`=BDS("Indu Index","INDX_MWEIGHT_HIST","END_DATE_OVERRIDE=20150914")`

When I use bds from this package:
`bds("INDU INDEX", "INDX_MWEIGHT_HIST",c("END_DATE_OVERRIDE"="20150914") )`, I see this message:

`Error: Sub-element '(null)' does not exist.`

Any ideas?

**Comment by eddelbuettel** [comment]
Briefly:

- for issue to be meaningful, show _input_ and _output_.  What does Excel get you for that `bds()` call?
- do some reading, see the `help(bds)` page: what you supplied is an _override_ but you shipped it as an _option_ as the third  argument.  

So please try

 bds("INDU INDEX",   "INDX_MWEIGHT_HIST", overrides=c("END_DATE_OVERRIDE"="20150914") )

**Comment by eddelbuettel** [comment]
@nattynatty :  From you having closed that (thanks), are we lead to believe that this works with an override argument as we suspected?

**Comment by nattynatty** [comment]
Yes, it was the overrides argument.

Thanks

**Comment by eddelbuettel** [comment]
:+1:
