### ISSUE TITLE
bds appears to only return data for last security

### ISSUE THREAD

**Issue by tseaward** [Rblp/Rblpapi#72]
In the following example, each security returns data from a call to `bds`. However, when the securities are combined in to a character vector, only data for the last security is returned.

```
> cn <- blpConnect()
> bds("AGL SJ Equity", "EQY_DVD_ADJUST_FACT")
  Adjustment Date Adjustment Factor Adjustment Factor Flag Adjustment Factor Operator Type
1      2007-07-02          0.910000                      3                               1
2      2007-07-02          0.937085                      1                               2
3      2007-07-02          1.000000                      1                               2
4      2001-05-08          4.000000                      3                               1

> bds("SOL SJ Equity", "EQY_DVD_ADJUST_FACT")
  Adjustment Date Adjustment Factor Adjustment Factor Flag Adjustment Factor Operator Type
1      1995-07-24          0.963111                      1                               2
2      1992-02-17          1.000000                      3                               2

> bds(c("AGL SJ Equity", "SOL SJ Equity"), "EQY_DVD_ADJUST_FACT")
  Adjustment Date Adjustment Factor Adjustment Factor Flag Adjustment Factor Operator Type
1      1995-07-24          0.963111                      1                               2
2      1992-02-17          1.000000                      3                               2

> blpDisconnect(cn)
```

**Comment by armstrtw** [comment]
I'll have to check, but I believe that bds is only meant to be called w/ one security argument.  Since the output of bds is not uniform (i.e. we don't always get back a timeseries as w/ bdh, or a vector as with bdp) it is hard to know how to properly combine it for multiple securities.

However, we should either convert a multiple security call to bds into an lapply on the bds_impl, or just throw.

Thanks for raising the issue.

**Comment by johnlaing** [comment]
I think we should throw. I don't like implicit conversion for vector arguments. If the user wants to get a list back, let them call lapply themselves.

**Comment by eddelbuettel** [comment]
The `throw` is fine by me.

**Comment by armstrtw** [comment]
we can just change this to check for length==1L
https://github.com/Rblp/Rblpapi/blob/master/R/bds.R#L50
if (any(duplicated(securities))) stop("Duplicated securities submitted.", call.=FALSE)

I can do it, unless someone has a preference for something else.

**Comment by eddelbuettel** [comment]
That also works and I was thinking of `stop()`. May be easier / cleaner.

**Comment by johnlaing** [comment]
Maybe I'm missing something, but can't we just change the impl signature to take a scalar instead of a vector? Then won't Rcpp just handle it for us?

**Comment by eddelbuettel** [comment]
Not on the R side.  We need to check length==1 which is what Whit just proposed.

**Comment by tseaward** [comment]
Thanks for the quick response. I'll use `lapply`.

**Comment by armstrtw** [comment]
I think this has it managed:
> library(Rblpapi)
> bds(c("AGL SJ Equity", "SOL SJ Equity"), "EQY_DVD_ADJUST_FACT")
Error: more than one security submitted.
> bds("AGL SJ Equity", "EQY_DVD_ADJUST_FACT")
  Adjustment Date Adjustment Factor Adjustment Factor Flag Adjustment Factor Operator Type
1      2007-07-02          0.910000                      3                               1
2      2007-07-02          0.937085                      1                               2
3      2007-07-02          1.000000                      1                               2
4      2001-05-08          4.000000                      3                               1
> 

If we really want to clean it up, we should rename the 'securities' arg to 'security' to be clear that it's only mean to be one...  However, I'm not sure if this rename will break the Rcpp tooling. or if the binding needs to be rebuilt from a script.

**Comment by eddelbuettel** [comment]
You would need to call `Rcpp::compileAttributes()` and also make sure roxygen runs -- but I'd rather leave the interface.

**Comment by armstrtw** [comment]
Ok. I think the documentation should eventually be updated, but not really a big deal. I'll leave it alone for now.

##' @param securities A character vector with security symbols in
##' Bloomberg notation.

**Comment by eddelbuettel** [comment]
No, please do.  You just need a manual run compileAttributes and roxygen. I have scripts for that; RStudio can do it for you if you prefer.   

Please also add a ChangeLog entry.
