### ISSUE TITLE
Build Rblpapi

### ISSUE THREAD

**Issue by csrvermaak** [Rblp/Rblpapi#75]
Hi

I've forked the code, to add the functionality for BEQS(), and checked it out of GitHub to C:\Rblpapi\ folder.

Before making any changes to the project, I would like to try to build the package on my machine. To build, I run the following command from my C:\ root folder:

R CMD build Rblpapi/trunk

These are my PATH settings to R: 
C:\Program Files\RRO\R-3.2.2\bin\x64;

I get the following result/error:

C:\>R CMD build Rblpapi/trunk
* checking for file 'Rblpapi/trunk/DESCRIPTION' ... OK
* preparing 'Rblpapi':
* checking DESCRIPTION meta-information ... OK
* cleaning src
Warning in cleanup_pkg(pkgdir, Log) :
  unable to run 'make clean' in 'src'
* installing the package to build vignettes
Warning: running command '"C:/PROGRA~1/RRO/R-32~1.1/bin/x64/Rcmd.exe" INSTALL -l
 "C:\Users\Rvermaak\AppData\Local\Temp\Rtmp0OjXaB\Rinst34603e6b4550" --no-multia
rch "C:/Users/Rvermaak/AppData/Local/Temp/Rtmp0OjXaB/Rbuild346041c57475/Rblpapi"
' had status 1
      -----------------------------------
* installing *source* package 'Rblpapi' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/RRO/R-32~1.1/et
c/x64/Makeconf" -f "C:/PROGRA~1/RRO/R-32~1.1/share/make/winshlib.mk" CXX='$(CXX1
X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LD
FLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="Rblpapi.dll" WI
N=64 TCLBIN=64 OBJECTS="RcppExports.o authenticate.o bdh.o bdp.o bds.o blpConnec
t.o blpapi_utils.o fieldsearch.o getBars.o getTicks.o"' had status 127
ERROR: compilation failed for package 'Rblpapi'
* removing 'C:/Users/Rvermaak/AppData/Local/Temp/Rtmp0OjXaB/Rinst34603e6b4550/Rb
lpapi'
      -----------------------------------
ERROR: package installation failed

Apologies for asking a basic question - I've written the code for EQS in C++ already, but it currently exports to csv. I don't have the bandwidth to learn package deployment right now, but I can build on the existing Rblpapi code to add the functionality. Please advise?

**Comment by eddelbuettel** [comment]
What is your directory structure?  Why is there `Rblpapi/trunk`?

The package builds on Windows, but neither one of us uses Windows to develop.  I can try to fire up the virtual machine once at work...  Else, you could look into using [the win-builder machine](http://win-builder.r-project.org) but not that you **must** set the Maintainer: field in `DESCRIPTION` to your address or else I get the result emailed.  

Otherwise, google 'building an R package on Windows' and just pick a simpler / smaller one (maybe my older [digest](https://github.com/eddelbuettel/digest) package), or another simple package to get a feel for these mechanics.

**Comment by eddelbuettel** [comment]
I also just noticed the [issue you opened for devtools](https://github.com/hadley/devtools/issues/942).  You seem to have some very basic and generic issues about building R packages on Windows.  

Maybe you need administrator mode, or maybe some other tricks.  

Please do sort those issues out before proceeding with more complicated packages.   See [the R manuals](https://cran.r-project.org/manuals.html) particular _Installation & Administration_ for its Windows appendix, and _Writing R Extensions_ for mechanics of package building.   This is painful at the beginning, once you are set up it will for all things R.

**Comment by csrvermaak** [comment]
Thanks @eddelbuettel for the suggestions, I will do that. 

Just as background, there is a Rblpapi/trunk, as I checked it out from Github using svn, and it automatically generated the directory structure. From your comment, it would seem as if this is not what should have happened. I will investigate.

Thanks

**Comment by eddelbuettel** [comment]
Why use GitHub via svn?   There are plenty of good git clients.

**Comment by csrvermaak** [comment]
@eddelbuettel - I believe svn is supported by Git? Too wary to risk an issue with a parallel installation of svn and git. The svn checkout worked, I've got the code forked, and can commit as well. Should be fine, as I will only commit C++ source, and do a pull request, right?

Below is for future reference, should anybody need to build on a Windows machine:

I've installed RTools, and followed the instructions on Building a Package (https://support.rstudio.com/hc/en-us/articles/200486508-Building-Testing-and-Distributing-Packages). Managed to build a basic "Hello World" package, and it works. Thus, I now have all the tools to build an R package. 

I retried building Rblpapi, and get the following error: "curl not found"

Then installed cygwin (and curl) using this information:
http://www.oracle.com/webfolder/technetwork/tutorials/obe/cloud/objectstorage/installing_cURL/installing_cURL_on_Cygwin_on_Windows.html

I'm now able to build Rblpapi on my windows machine. :-)

**Comment by armstrtw** [comment]
not trying to force you to do something you don't want to do, but the world has migrated to git.
http://www.wired.com/2015/03/github-conquered-google-microsoft-everyone-else/

I believe you are correct that you can use some kind of interface layer to work w/ a git repo in svn, but in terms of what we are doing in this project, I have to think that it is going to be more difficult for you if you are using svn.

my 2c.

**Comment by eddelbuettel** [comment]
Drop svn if you want to participate here.  Github works with git.  We will take _git_ pull requests.

The curl dependency is a buglet with @jeroenooms already pointed out.  We could rewrite the use via `R -e download.file(....)`.

But at long last, heartfelt congratulations to being able to build. That is where you should have been before you sent a dozen or more messages to three different people and filing two different (and as it turns out, spurious) tickets.  

Rblpapi is not a trivial package due to the build dance, Rcpp and what not.  You went in for a hard start.  Now that you're there everything will be a (comparative) breeze.  But do switch to git.

**Comment by csrvermaak** [comment]
@armstrtw @eddelbuettel comments on git noted, thanks.

**Comment by eddelbuettel** [comment]
That said if you get your patches in via svn, more power to you.  But note that we all use git,  and github is build around it.   It may work via svn but you'd be very much on your own.
