### ISSUE TITLE
beqs - Date input error ('invalid trim argument')

### ISSUE THREAD

**Issue by csrvermaak** [Rblp/Rblpapi#85]
When I try to run one of the example screens:

```
beqs("Global Oil Companies YTD Return","GLOBAL","ENGLISH","GENERAL","20150930")
```

This error is returned:
```
Error in format.default(date, "%Y%m%d") : invalid 'trim' argument
```

Suspect it might be in the wrapper function.

**Comment by csrvermaak** [comment]
OK, so the problem just lies with the example in the documentation, expects a Data, but in the example, it is a string.

**Comment by eddelbuettel** [comment]
Dang.  'R CMD check ...' would have caught that if only we could run the example at, say, Travis :-/

**Comment by csrvermaak** [comment]
@eddelbuettel  Update the example, or the code - your preference?

**Comment by eddelbuettel** [comment]
Fix coming in one minute...

**Comment by csrvermaak** [comment]
Ah .. OK, I was about to submit a pull request for a patch :-)
