### ISSUE TITLE
bdp bug for query fields: "60DAY_IMPVOL_100.0%MNY_DF" and "3MTH_IMPVOL_100.0%MNY_DF"

### ISSUE THREAD

**Issue by siddeuce** [Rblp/Rblpapi#86]
code:
```r
library(Rblpapi)
connect<-blpConnect() # connect to bloomberg terminal
indexName <- 'SPX INDEX'
queryFieldsImpliedVol <- c("60DAY_IMPVOL_100.0%MNY_DF","3MTH_IMPVOL_100.0%MNY_DF")
impliedVolSPX <- bdp(indexName,queryFieldsImpliedVol,con=connect)
```
output:

```
SPX INDEX                                          
60DAY IMPLIED VOL: 14.5635
90DAY IMPLIED VOL: 14.07569         
```
However, per Bloomberg Terminal with function call used in Excel:
=BDP(SPX INDEX,60DAY_IMPVOL_100.0%MNY_DF)

AND

=BDP(SPX INDEX,3MTH_IMPVOL_100.0%MNY_DF)

The output is:
   
```                             
SPX INDEX                                          
60DAY IMPLIED VOL: 14.07569
90DAY IMPLIED VOL: 14.5635
```

I believe there is an error for these two query fields, since they appear to be swapped. Please help is possible. Thank you.

**Comment by eddelbuettel** [comment]
Hi, and thanks for the note.   

We just 'unspool' the results the way we get them from Bloomberg.  You could just try to sort them based on whatever way you prefer it.  But consider the simpler `SPY Equiry` and asking for `PX_LAST` and `VOLUME`.  No matter how I send the request I always get `PX_LAST` first.

So I really think you need to post-process at your end.

**Comment by barcadad** [comment]
Hi Dirk, if I understood the problem - it's that the variable names aren't align with the data below, in which case post-processing wouldn't be able to fix it.  It is more than the full columns being disordered.

**Comment by eddelbuettel** [comment]
I beg to differ:

```r
R> bdp("SPY US Equity", c("PX_LAST", "VOLUME"))
              PX_LAST   VOLUME
SPY US Equity  207.42 10911151
R> bdp("SPY US Equity", c("VOLUME", "PX_LAST"))
              PX_LAST   VOLUME
SPY US Equity  207.36 10942156
R> 
```
