### ISSUE TITLE
How I can get all the ISIN list from RblpAPI?

### ISSUE THREAD

**Issue by bushiyundeyu** [Rblp/Rblpapi#92]
Hello,

      Could you please tell me how I can get all the ISIN list by this API? I see that I can get the details by /isin/XXXXXXXXX. But for now I want get all the ISIN first. 
Many thanks for you help.

BR,

Liang

**Comment by eddelbuettel** [comment]
What makes you think we know?

**Comment by bushiyundeyu** [comment]
Hi eddelbuettel,

    I just want get all the Scurity from the BloomBerg application. Do you know is there any interface can do that? Many thanks.

Br,
Liang

**Comment by shrektan** [comment]
Maybe you should ask the help desk first ?


发自网易邮箱大师
在2015年11月11日 11:46，bushiyundeyu 写道:

Hi eddelbuettel,

I just want get all the Scurity from the BloomBerg application. Do you know is there any interface can do that? Many thanks.


Br,
Liang

**Comment by bushiyundeyu** [comment]
I have found some information to get the ISIN list as below

            var securtyName="//blp/mktlist/secids/isin/isin";
            Service service = session.GetService("//blp/mktlist");
            Request request = service.CreateRequest("SnapshotRequest");
            request.Set("security", securtyName);

           session.SendRequest(request, null);

            while (true)
            {
                try
                {
                    Event eventObj = session.NextEvent();
                    foreach (Message msg in eventObj)
                    {
                        if (eventObj.Type != Event.EventType.RESPONSE &&
                            eventObj.Type != Event.EventType.PARTIAL_RESPONSE)
                        {
                            continue;
                        }
                        Element fields = msg.GetElement("resultCode");
                        Element snapshot = msg.GetElement("snapshot");
                        int numElements = snapshot.NumElements;
                        for (int i = 0; i < numElements; i++)
                        {
                         Element dataItem=   snapshot.GetElement(i);
                         string isinName = fields.GetValueAsString();
                         Console.WriteLine("ISIN:" + isinName);
                        }
               }
       }
But unlucky it's can't works well. I can't get the ISIN list. is there anybody know how to get the data?

**Comment by n-e-w** [comment]
This really isn't the forum to ask these questions. This is for specific
issues related to the Rblpapi package. The package authors have substantial
full time job commitments on top of their very generous efforts on this
project. Please respect their (and other contributors) efforts by finding
the correct forum to post these kinds of questions.

**Comment by shrektan** [comment]
I would agree with @n-e-w. I really think this is kind of question that should ask the bloomberg's help desk~

**Comment by eddelbuettel** [comment]
Agreed.  And random snippets of C# code (if I have to guess the language) don't really help either.

So closing this now.
