### ISSUE TITLE
On OS X curl fails with blp* download 

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#95]
Per a CRAN email:

> I investigated
> 
> https://www.r-project.org/nosvn/R.check/r-devel-osx-x86_64-clang/Rblpapi-00check.html
>
> which is fairly new.  As you suppress error messages with curl -s and do
> not check the return code you do not report
> 
> tawny% curl -k -L -O
> https://github.com/Rblp/blp/raw/master/headers/osx/blpHeaders.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time
>  Current
>                                 Dload  Upload   Total   Spent    Left
>  Speed
> 100   145  100   145    0     0    134      0  0:00:01  0:00:01 --:--:--
>   134
> curl: (35) Unknown SSL protocol error in connection to
> raw.githubusercontent.com:-9805
> 
> So it seems github is now incompatible with OS X's curl (the URL works
> in browsers).

**Comment by armstrtw** [comment]
osx is fcking irritating.

**Comment by eddelbuettel** [comment]
That'll be a pretty trivial fix in the (bash script) `configure` to use R itself to download.

**Comment by armstrtw** [comment]
wget?

**Comment by eddelbuettel** [comment]
I so agree on your sentiment re OS X.  Nevertheless it seems to have an astonishingly large number of fans.

We use wget on Linux. I do not think we can assume it present. And

```sh
Rscript -s 'download.file(url, tgt, quiet=TRUE)'
```

work so I just make it a shell function which supplies `url` with `basename` computing `tgt` as the trailing piece.  No biggie.

**Comment by armstrtw** [comment]
right, so wget would just be another dependency...

that looks good, and I assume it works on mac...?  excellent.

**Comment by eddelbuettel** [comment]
And once again forgot to add a 'closes #...' tag to the commit message...
