### ISSUE TITLE
Minimal unit tests against Bloomberg?

### ISSUE THREAD

**Issue by eddelbuettel** [Rblp/Rblpapi#98]
I keep thinking we should have something.   

I tend to have enough environment variables around to autoconnect so I could basically test whether
- blpHost is set
- blpConnect is set
- I can ping the host
- I can connect successfully
and if and only if all that is true run a unit test.  

These would of course be off at Travis and CRAN as those have bare `~/.Rprofile` files.  

Am I making sense?

**Comment by armstrtw** [comment]
Yes, I agree.  Having actual unit tests against the real service would be great.

**Comment by eddelbuettel** [comment]
We need to do *something*.  The `bdh()` breakage is a little embarrassing.

**Comment by armstrtw** [comment]
it's not on cran, just the repo?

I suggest we have a minimal live test we run before push.   can we keep this in inst somewhere?

I've got my hands full today, but I can look later this evening.

**Comment by eddelbuettel** [comment]
Yes, conditioning on _something_ is entirely doable.  Rcpp has been doing it for years -- if we are in 'dev mode' (defined as having version numbers matching a.b.c.d) we run all tests where as on CRAN / release mode (defined as having version numbers a.b.c without a fourth part d) then subsets are running.

I just don't quite know yet how to condition this.  We _could_ do what I do at work anyway and depends on the autoconnect options.   Or maybe just set a new `option("blpRunTests")`.    Bloody hard to do anything with a Bbg at hand ...

**Comment by eddelbuettel** [comment]
> I suggest we have a minimal live test we run before push.

On all other projects, Travis helps with this.  Here we can't.  So we have to run `R CMD check`, and then we may as well through real tests in there.

**Comment by eddelbuettel** [comment]
Slight snag: It seems R does _not_ read `~/.Rprofile` during tests :-/

**Comment by armstrtw** [comment]
so, I need to add my unit tests here: inst/unitTests ?

**Comment by eddelbuettel** [comment]
Yes.  Do you want to do a quick hangout so that I walk you through?  Or phone call?  It may be painful over mail / tickets.

**Comment by eddelbuettel** [comment]
This is now coming together at last.
