### ISSUE TITLE
BEQS - Empty columns 

### ISSUE THREAD

**Issue by csrvermaak** [Rblp/Rblpapi#99]
The BEQS function fails under the following two circumstances:
 * When the first 25 rows of the returned data is NA
 * When the entire column returned is NA

**Comment by eddelbuettel** [comment]
Do we have examples for cases one or two?

**Comment by eddelbuettel** [comment]
Also, does #99 address case one 'by making it case two'?  May mention that...

**Comment by eddelbuettel** [comment]
Ok, I am _really_ dense this morning.  Should not read issue tickets with less than six hours of sleep.  I now see how you got rid of the '25' as a max.  That is better. 

Will merge, and then add the ChangeLog and NEWS you omitted, and make the NA columns numeric.
